### ISSUE TITLE
用户详情页面头部消失

### ISSUE THREAD

**Issue by TQHYG** [guozhigq/pilipala#1000]
### 问题描述
进入任意一个用户/UP主的详情页面，头像，关注按钮，发消息按钮闪现一下后消失

### 复现步骤
从个人关注列表或搜索页面进入用户主页都可以稳定复现，我已经尝试切换账号/清除数据重装等措施，问题均未解决

### 预期行为
修复以上问题

### 系统信息
设备型号一加Ace3V
系统ColorOS14，PJF110 14.0.1.710(CNO1U140P02)

### 相关截图或日志

https://github.com/user-attachments/assets/1f8be0e5-1f84-4b49-89c7-90f3aea74242

**Comment by yandqlex** [comment]
附议

**Comment by guozhigq** [comment]
#985
