### ISSUE TITLE
合集订阅功能

### ISSUE THREAD

**Issue by GorNx** [guozhigq/pilipala#1003]
### 功能描述
视频播放页增加订阅合集按钮

### 目标
请描述你希望通过这个功能实现的目标。

### 其他
![IMG_20241013_150524.jpg](https://github.com/user-attachments/assets/ae8f6939-7088-477d-ba98-9acd88585702)

**Comment by Rzdpai** [comment]
这个有人申请过了

**Comment by guozhigq** [comment]
最新版已支持
