### ISSUE TITLE
主页Bug

### ISSUE THREAD

**Issue by RzdPai** [guozhigq/pilipala#1004]
![Screenshot_2024-10-15-12-19-42-87_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/c7cc87b6-c0d6-4d4b-b560-3fb152ca233c)

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: SP1A.210812.016
board: RM6833
bootloader: unknown
brand: realme
device: RE584B
display: RMX3619_11_A.24
fingerprint: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202407051924:user/release-keys
hardware: mt6833
host: kvm-slave-build-s-system-02772520
isPhysicalDevice: true
manufacturer: realme
model: RMX3619
product: RMX3619
tags: release-keys
type: user
versionBaseOs: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202308101122:user/release-keys
versionCodename: REL
versionIncremental: 202407051924
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2024-07-05
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
Line0      StatView.build (package:pilipala/common/widgets/stat/view.dart:26)
Line1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
Line2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
Line3      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line4      StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line5      Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line6      Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line10     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line11     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line12     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line13     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line17     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line19     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line20     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line21     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line22     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line26     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line29     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line30     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line31     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line34     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line35     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line37     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line39     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line40     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line41     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line43     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line44     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line45     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line47     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line48     SingleChildRen

**Comment by guozhigq** [comment]
试试这个 https://drive.google.com/file/d/1QhJrnu1r1W65WgXvCh4ezvV9RHC5Mt3E/view?usp=sharing

**Comment by Rzdpai** [comment]
> 试试这个 https://drive.google.com/file/d/1QhJrnu1r1W65WgXvCh4ezvV9RHC5Mt3E/view?usp=sharing

![Screenshot_2024-10-29-12-20-04-64_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/897c2966-f363-4071-9794-65a622f1c5b7)

我有遇到了此问题，但它不再会出现渲染错误
