### ISSUE TITLE
在通知中打开视频错误

### ISSUE THREAD

**Issue by Rzdpai** [guozhigq/pilipala#1006]
视频可以正常打开，但在消息通知中则不行
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: SP1A.210812.016
board: RM6833
bootloader: unknown
brand: realme
device: RE584B
display: RMX3619_11_A.24
fingerprint: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202407051924:user/release-keys
hardware: mt6833
host: kvm-slave-build-s-system-02772520
isPhysicalDevice: true
manufacturer: realme
model: RMX3619
product: RMX3619
tags: release-keys
type: user
versionBaseOs: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202308101122:user/release-keys
versionCodename: REL
versionIncremental: 202407051924
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2024-07-05
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
Line0      _StreamController.add (dart:async/stream_controller.dart:605)
Line1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
什么类型的通知呢

**Comment by Rzdpai** [comment]
> 什么类型的通知呢

我遇到的是点赞弹幕的通知，并且右边也没有显示我的弹幕

**Comment by guozhigq** [comment]
试试 #1004 测试包

**Comment by Rzdpai** [comment]
> 试试 #1004 测试包

正常了
