### ISSUE TITLE
关于动态页的一个小建议

### ISSUE THREAD

**Issue by wenxuanjun** [guozhigq/pilipala#101]
### 功能描述
动态页 `最常访问` 部分的样式建议

### 解决方案
希望动态页的最常访问能仿照原版，在 UP 头像上面有一个 `最常访问` 的标题，并将全部（或更多）按钮与标题平行居右，这样替代目前巨大的全部按钮，能给内容更多展示空间。

另外希望 `最常访问` 部分与下方的动态能有一个分割栏，就像动态与动态之间的分割栏一样。

**Comment by guozhigq** [comment]
确实可以，等我找找以前的代码 🤪
