### ISSUE TITLE
能否加个记忆弹幕设置的功能开关，现在调完之后点个新的视频又恢复默认弹幕设置了

### ISSUE THREAD

**Issue by xianren152** [guozhigq/pilipala#1010]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by hstonc** [comment]
好像是有的，我设置完之后，关掉应用再打开发现保存了

**Comment by guozhigq** [comment]
最新版已修复
