### ISSUE TITLE
tg群里的评论区版本消息有bug

### ISSUE THREAD

**Issue by Kemiaojun** [guozhigq/pilipala#1012]
### 问题描述
请提供一个清晰而简明的问题描述。
打开消息通知有白屏

### 复现步骤
请提供复现该问题所需的具体步骤。
打开消息通知

### 预期行为
请描述你期望的正确行为或结果。
消息栏恢复正常

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: UP1A.231005.007
board: kalama
bootloader: unknown
brand: vivo
device: PD2243
display: PD2243_A_14.1.13.0.W10.V000L1
fingerprint: vivo/PD2243/PD2243:14/UP1A.231005.007/compiler09061157:user/release-keys
hardware: qcom
host: comdg01150031
isPhysicalDevice: true
manufacturer: vivo
model: V2243A
product: PD2243
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: eng.compil.20240906.115722
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-08-01
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
NoSuchMethodError: The getter 'face' was called on null.
Receiver: null
Tried calling: face
------- 错误堆栈 -------
Line0      SessionItem.build (package:pilipala/pages/whisper/view.dart:247)
Line1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
Line2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
Line3      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line7      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line10     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line16     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line21     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line23     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line27     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line29     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line33     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line36     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line41     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line43     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line47     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line48     SliverMultiBoxAdaptorElement.updateChild (package:flu
![Screenshot_2024_1024_125816.png](https://github.com/user-attachments/assets/b14b0ee4-bac8-4b9b-9484-2b80f9f40934)

**Comment by cnstruggler** [comment]
fix1027版本修复了吗？
