### ISSUE TITLE
用户信息无法加载头部

### ISSUE THREAD

**Issue by XHJXHJXHJXHJ** [guozhigq/pilipala#1013]
加载用户信息时，顶部信息无法加载，包括关注，私信等
Android9.0 huaweiJKMAL00
**请尽快修复，严重影响用户体验**

**Comment by Chisato-C** [comment]
对，我这也是，原本打开可以加载，但是闪一下就没了

**Comment by guozhigq** [comment]
https://drive.google.com/file/d/1zHJD6f53_oEN-0gpv-Q8AcYcMrEm2aVV/view?usp=sharing
