### ISSUE TITLE
评论发图片

### ISSUE THREAD

**Issue by XHJXHJXHJXHJ** [guozhigq/pilipala#1017]
添加评论发图片功能

**Comment by cnstruggler** [comment]
Telegram群里边的fix1027版本增加了这个功能。

**Comment by 201307** [comment]
> Telegram群里边的fix1027版本增加了这个功能。

朋友，能分享下你说的整个版本吗？

**Comment by cnstruggler** [comment]
> > Telegram群里边的fix1027版本增加了这个功能。
> 
> 朋友，能分享下你说的整个版本吗？

不是，你没有进Telegram群吗？

**Comment by 201307** [comment]
> > > Telegram群里边的fix1027版本增加了这个功能。
> > 
> > 
> > 朋友，能分享下你说的整个版本吗？
> 
> 不是，你没有进Telegram群吗？

没有在Telegram群里，我研究下怎么注册

**Comment by cnstruggler** [comment]
@201307 你可以试试这个接码平台，https://smstome.com 。

**Comment by guozhigq** [comment]
https://drive.google.com/file/d/1zHJD6f53_oEN-0gpv-Q8AcYcMrEm2aVV/view?usp=sharing

**Comment by guozhigq** [comment]
最新版已支持
