### ISSUE TITLE
番剧观看进度不同步

### ISSUE THREAD

**Issue by BenAlan1** [guozhigq/pilipala#1020]
### 问题描述
在番剧栏点进番剧时，每次都是从第一集开始播

### 复现步骤
番剧栏，任意番剧点进

### 预期行为
进入播放页面同步上次或其它设备播放记录

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
最新版已修复
