### ISSUE TITLE
动态页查看单个up全部动态时，动态筛选标签未全隐藏

### ISSUE THREAD

**Issue by wildwinld** [guozhigq/pilipala#1022]
### 问题描述
在动态列表点击具体单个up动态时，原来得【全部动态|投稿|番剧|专栏】未隐藏成功，内容和up头像重叠显示

### 复现步骤
点击动态，点击具体某一up头像

### 预期行为
隐藏【全部动态|投稿|番剧|专栏】

### 系统信息
hyperos 1.0.6.0

### 相关截图或日志
![Screenshot_2024-10-28-08-38-16-859_com guozhigq pilipala-edit](https://github.com/user-attachments/assets/71396090-b8c5-419b-92aa-511ec5df935c)

**Comment by guozhigq** [comment]
最新版已修复
