### ISSUE TITLE
视频界面全灰

### ISSUE THREAD

**Issue by RzdPai** [guozhigq/pilipala#1027]
![Screenshot_2024-10-30-13-13-11-93_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/e9412e6b-527d-47d5-be9f-d31d7d55651a)

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: SP1A.210812.016
board: RM6833
bootloader: unknown
brand: realme
device: RE584B
display: RMX3619_11_A.24
fingerprint: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202407051924:user/release-keys
hardware: mt6833
host: kvm-slave-build-s-system-02772520
isPhysicalDevice: true
manufacturer: realme
model: RMX3619
product: RMX3619
tags: release-keys
type: user
versionBaseOs: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202308101122:user/release-keys
versionCodename: REL
versionIncremental: 202407051924
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2024-07-05
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
RangeError (length): Invalid value: Valid value range is empty: 3
------- 错误堆栈 -------
Line0      IdUtils.bv2av (package:pilipala/utils/id_utils.dart)
Line1      VideoDetailController.onInit (package:pilipala/pages/video/detail/controller.dart:161)
Line2      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66)
Line3      InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12)
Line4      GetInstance._startController (package:get/get_instance/src/get_instance.dart:254)
Line5      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:205)
Line6      GetInstance.find (package:get/get_instance/src/get_instance.dart:302)
Line7      GetInstance.put (package:get/get_instance/src/get_instance.dart:87)
Line8      Inst.put (package:get/get_instance/src/extension_instance.dart:89)
Line9      _VideoDetailPageState.initState (package:pilipala/pages/video/detail/view.dart:77)
Line10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611)
Line11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line18     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line25     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line28     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line31     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line36     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line39     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line42     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line47     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line53     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line58     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line61     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line66     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line69     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line72     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line77     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line80     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line83     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line88     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line91     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line96     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line98     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line102    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line105    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line110    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line113    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line115    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line119    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line122    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line125    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line130    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line132    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line136    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line138    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line142    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line145    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line150    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line152    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line156    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line158    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line162    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line163    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line165    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line167    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line171    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line173    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line177    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line179    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line180    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line182    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line185    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line188    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line190    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line193    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line196    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line201    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line202    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line204    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line206    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line210    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line212    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line216    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line218    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line219    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line224    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line227    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line232    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
Line233    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line234    Element.updateChildren (package:flutter/src/widgets/framework.dart:4033)
Line235    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line236    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line239    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line240    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line241    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line243    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line244    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line245    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line247    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line248    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line249    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
Line250    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line252    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line253    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line254    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line255    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line257    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line258    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line259    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
Line260    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line262    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line263    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line264    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line265    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line268    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line269    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line270    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line271    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line272    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line273    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line274    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line276    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line277    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line278    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line280    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line281    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line282    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line283    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line284    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line285    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line286    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
Line287    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
Line288    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
Line289    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
Line290    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
Line291    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
Line292    _invoke (dart:ui/hooks.dart:312)
Line293    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
Line294    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
从哪里跳转进去的呢

**Comment by Rzdpai** [comment]
> 从哪里跳转进去的呢
> 

主页
