### ISSUE TITLE
提供关闭双击快进/快退的选项

### ISSUE THREAD

**Issue by CrystFish** [guozhigq/pilipala#1037]
### 功能描述
全屏观看视频时，想要双击暂停，却总是容易快进/快退

### 目标
能够让用户选择关闭该功能

### 解决方案
在设置处提供选项开关

### 其他
无

**Comment by zpoyqx** [comment]
播放设置 -- 手势设置 -- 双击快退/快进

**Comment by CrystFish** [comment]
> 播放设置 -- 手势设置 -- 双击快退/快进

哦哦，之前没有翻到，谢谢了
