### ISSUE TITLE
up主详情页显示异常

### ISSUE THREAD

**Issue by 610364023** [guozhigq/pilipala#1038]
### 问题描述
①点进UP主头像进入详情页，up主信息会出现一瞬间然后消失
②点进投稿有几率显示一片空白，此时返回就会显示一片灰色

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

https://github.com/user-attachments/assets/1c7bc89c-ac67-4b2c-91ed-bec02c5981e6

**Comment by guozhigq** [comment]
试试 https://drive.google.com/file/d/19NDFltAvfFyM9Zwn58vTdP3SCLjS9JgF/view?usp=sharing

**Comment by guozhigq** [comment]
最新版已修复
