### ISSUE TITLE
字幕错误匹配

### ISSUE THREAD

**Issue by NotInfinity9** [guozhigq/pilipala#1039]
### 问题描述
用cc字幕大部分时候会有字幕跟视频不匹配的情况

### 复现步骤
突然出现，有随机性
全是，感觉是个体特例
不清楚是不是跟删除后重新安装1.0.25.1102有关

### 预期行为
字幕与视频匹配

### 系统信息
android origin 4
系统浏览器内核
移动流量

### 相关截图或日志
![Screenshot_20241103_103407](https://github.com/user-attachments/assets/aa2cb0c8-d242-40a3-b8ed-862453c807d5)
![Screenshot_20241103_103411](https://github.com/user-attachments/assets/48e769a2-490f-4ce1-9cd5-53f0c3b599bd)
![Screenshot_20241103_103416](https://github.com/user-attachments/assets/3a97a452-9653-49b2-ae8b-cf4f52601f4b)

出戏（）

**Comment by guozhigq** [comment]
试试 https://drive.google.com/file/d/19NDFltAvfFyM9Zwn58vTdP3SCLjS9JgF/view?usp=sharing

**Comment by NotInfinity9** [comment]
好的，已解决
