### ISSUE TITLE
在动态那一栏里，只要点了以为up的头像，左滑返回之后，再下拉刷新动态，所有up的头像都会变灰

### ISSUE THREAD

**Issue by baiheiamns** [guozhigq/pilipala#1045]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by baiheiamns** [comment]
![Screenshot_20241103_220120.jpg](https://github.com/user-attachments/assets/7a5a8f7c-2072-4765-adae-2140b34cc14c)

像这样

**Comment by guozhigq** [comment]
试试 https://drive.google.com/file/d/19NDFltAvfFyM9Zwn58vTdP3SCLjS9JgF/view?usp=sharing

**Comment by guozhigq** [comment]
最新版已修复
