### ISSUE TITLE
进度条拖动

### ISSUE THREAD

**Issue by 503leo** [guozhigq/pilipala#105]
### 功能描述
1.07版本感觉手指滑动的距离是对应了一个固定的时间，比如说拖动1cm就是对应进度条一分钟，无论视频长短都是如此，个人感觉在看一些比较短的视频时，屏幕中间左右滑动调节进度时过于灵敏，稍微一动就把进度条拖到尾部了。

### 目标
希望可以增加一个能够按照进度条百分比拖动的选项来设置，或者说针对比较短的视频进度条调节做些调整。希望

### 解决方案
可以给用户提供一个自己设置调节进度灵敏度的选项
。
### 其他
希望能提供些参考和帮助，十分感谢。

**Comment by MystFeng** [comment]
进度条、音量、亮度都灵敏过头了，把它们设置得稍迟钝些，有助于使用体验
