### ISSUE TITLE
视频与字幕不匹配

### ISSUE THREAD

**Issue by Alinges3** [guozhigq/pilipala#1050]
### 问题描述
请提供一个清晰而简明的问题描述。
视频打开字幕开关出现的字幕与视频不符，重新打开软件再进行相同操作字幕直接消失了

### 复现步骤
请提供复现该问题所需的具体步骤。
打开一个有字幕的视频，开启字幕，有概率无响应，重复几次操作，出现的字幕与视频不符

### 预期行为
请描述你期望的正确行为或结果。
打开的字幕与视频匹配，不会消失和错乱

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
第一代骁龙8+ MIUI14.0.9 浏览器via5.8.1

### 相关截图或日志
暂无

**Comment by guozhigq** [comment]
试试 https://drive.google.com/file/d/19NDFltAvfFyM9Zwn58vTdP3SCLjS9JgF/view?usp=sharing

**Comment by guozhigq** [comment]
最新版已修复
