### ISSUE TITLE
用户主页不显示用户头像和关注按键以及粉丝量

### ISSUE THREAD

**Issue by wzyear** [guozhigq/pilipala#1058]
### 问题描述
用户主页用户头像和关注按键以及粉丝量不显示，且无法关注或取关该用户，无法查看该用户的粉丝量

### 复现步骤
随机打开一名用户的主页，该用户的主页上面的头像和关注按键和粉丝量显示一秒后消失

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_2024-11-05-23-45-16-132_com guozhigq pilipala](https://github.com/user-attachments/assets/db7ed619-88aa-4650-8572-fcf26cf2c62a)
![Screenshot_2024-11-05-23-45-19-455_com guozhigq pilipala](https://github.com/user-attachments/assets/808b49d3-7268-44ec-bc3d-52d12bfcb485)
![Screenshot_2024-11-05-23-53-29-128_com guozhigq pilipala](https://github.com/user-attachments/assets/14ece9c3-5a8d-480f-a3bd-4b64bd9f0710)

**Comment by joechan-cq** [comment]
![image](https://github.com/user-attachments/assets/afe43236-8491-4750-99d9-769f3430223a)

触发风控了，估计API失效了

**Comment by guozhigq** [comment]
#985
