### ISSUE TITLE
最近啊b添加了对分p视频放入合集中的支持，合集切换这类视频时会发生分p和合集部分的灰屏bug

### ISSUE THREAD

**Issue by komori-flag** [guozhigq/pilipala#1060]
### 问题描述
最近啊b添加了对分p视频放入合集中的支持，合集切换这类视频时会发生分p和合集部分的灰屏bug。

### 复现步骤
视频地址：https://www.bilibili.com/video/av465326386/
如下图所示，直接通过 bv/av 号进入页面时是正常的
![fe35c3668c0f075e379707a2ca46356](https://github.com/user-attachments/assets/3f8be9a4-9be1-4520-94b1-932f6e8aec85)

一旦在合集中切换视频或从历史记录中进入这类视频便会发生此类 bug。
![c9c6e7715401a68d49cb453f8045d82](https://github.com/user-attachments/assets/025ff2e0-a469-488f-9db5-221f250b50d1)

### 预期行为
正常切换视频，并显示出分p集数。

### 系统信息
日志上有记录应该不需要重复提交了，如果需要的话可以说一声。
使用的是 beta 1.0.25.1102 版本。

### 相关截图或日志

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TP1A.220624.014
board: chopin
bootloader: unknown
brand: Redmi
device: chopin
display: TP1A.220624.014
fingerprint: Redmi/chopin/chopin:13/TP1A.220624.014/V14.0.8.0.TKPCNXM:user/release-keys
hardware: mt6893
host: pangu-build-component-system-483193-n410h-7jhc3-5tn67
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2104K10AC
product: chopin
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.8.0.TKPCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-11-01
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
RangeError (length): Invalid value: Not in inclusive range 0..6: -1
------- 错误堆栈 -------
Line0      State.widget (package:flutter/src/widgets/framework.dart)
Line1      _PagesPanelState.build.<anonymous closure> (package:pilipala/pages/video/detail/introduction/widgets/page_panel.dart:96)
Line2      GestureRecognizerFactoryWithHandlers.constructor (package:flutter/src/widgets/gesture_detector.dart:101)
Line3      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26)
Line4      ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:56)
Line5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
Line6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
Line7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
Line10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
Line11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
Line12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
Line13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
Line14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
Line15     _invoke (dart:ui/hooks.dart:312)
Line16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
Line17     _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TP1A.220624.014
board: chopin
bootloader: unknown
brand: Redmi
device: chopin
display: TP1A.220624.014
fingerprint: Redmi/chopin/chopin:13/TP1A.220624.014/V14.0.8.0.TKPCNXM:user/release-keys
hardware: mt6893
host: pangu-build-component-system-483193-n410h-7jhc3-5tn67
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2104K10AC
product: chopin
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.8.0.TKPCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-11-01
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
RangeError (length): Invalid value: Not in inclusive range 0..3: -1
------- 错误堆栈 -------
Line0      State.widget (package:flutter/src/widgets/framework.dart)
Line1      _PagesPanelState.build.<anonymous closure> (package:pilipala/pages/video/detail/introduction/widgets/page_panel.dart:96)
Line2      GestureRecognizerFactoryWithHandlers.constructor (package:flutter/src/widgets/gesture_detector.dart:101)
Line3      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26)
Line4      ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:56)
Line5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
Line6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
Line7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line10     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line12     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line13     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line14     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line15     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line17     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line19     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line20     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line22     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line25     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line26     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line27     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line31     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line33     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line34     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line35     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line37     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line39     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line42     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line43     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line44     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line46     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line47     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line48     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
Line49     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
Line50     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
Line51     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
Line52     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
Line53     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
Line54     _invoke (dart:ui/hooks.dart:312)
Line55     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
Line56     _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
最新版已修复
