### ISSUE TITLE
不知道叫什么

### ISSUE THREAD

**Issue by RzdPai** [guozhigq/pilipala#1071]
当我打开一个up主的投稿页面时，什么也没有，我想返回刷新，结果界面全灰![Screenshot_2024-11-10-14-01-13-08_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/4e48f14e-e2c3-400f-8284-1eae4845d1d6)

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: SP1A.210812.016
board: RM6833
bootloader: unknown
brand: realme
device: RE584B
display: RMX3619_11_A.24
fingerprint: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202407051924:user/release-keys
hardware: mt6833
host: kvm-slave-build-s-system-02772520
isPhysicalDevice: true
manufacturer: realme
model: RMX3619
product: RMX3619
tags: release-keys
type: user
versionBaseOs: realme/RMX3619/RE584B:12/SP1A.210812.016/S.202308101122:user/release-keys
versionCodename: REL
versionIncremental: 202407051924
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2024-07-05
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
Line0      _StreamController.add (dart:async/stream_controller.dart:605)
Line1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
哪个up呢

**Comment by Rzdpai** [comment]
> 哪个up呢

上官北丶 - https://space.bilibili.com/1335461955

全灰过后返回会恢复正常
