### ISSUE TITLE
编译时遇到：Error: Type 'UnmodifiableUint8ListView' not found.

### ISSUE THREAD

**Issue by mhduiy** [guozhigq/pilipala#1073]
![image](https://github.com/user-attachments/assets/6fd71011-2ff3-4a9f-b1a6-b9ad5bb61c17)
请问该怎么解决

**Comment by unti1you** [comment]
请问解决了么，我用的3.32.4flutter  3.8.1Dart  xcode16  遇到同样的问题

**Comment by mhduiy** [comment]
> 请问解决了么，我用的3.32.4flutter 3.8.1Dart xcode16 遇到同样的问题

没有解决。。。

**Comment by guozhigq** [comment]
切换pub源地址试试
