### ISSUE TITLE
可否添加一个在up主投稿中播放全部的按钮？自动连播问题

### ISSUE THREAD

**Issue by ZhangEmo** [guozhigq/pilipala#1077]
### 功能描述
1 类似在收藏夹中右下角的播放全部按钮，可否在up主全部投稿中也添加一个

2 在播放界面下不会自动连播稿件下推荐的稿件
### 目标
1 能够顺序播放up主的全部稿件

2 能够自动连播稿件以及稿件下方推荐的稿件

### 解决方案
无

### 其他
官方bilibili客户端

辛苦作者

**Comment by guozhigq** [comment]
最新版已支持
