### ISSUE TITLE
画面比例更方便的切换

### ISSUE THREAD

**Issue by hstonc** [guozhigq/pilipala#1080]
### 功能描述
希望画面比例是按一下切换一种，然后长按才出现这个页面，或者是双指缩放放大或填满
![Screenshot_20241112_080934](https://github.com/user-attachments/assets/6e1a89f7-6810-4222-9e0f-c6be72966e9d)

### 其他
vlc是点击一下更变一次画面比例，而YouTube是双指缩放

**Comment by guozhigq** [comment]
最新版已支持
