### ISSUE TITLE
进入专栏页面点进去后显示网络错误，加载不出来，切换数据网络和流量也没有用，而且返回后在主页上也开始显示没有网络，尽管其他模块能正常加载但底部的提示没有消失

### ISSUE THREAD

**Issue by yuzuojianbayun** [guozhigq/pilipala#1084]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by 2XSWKL** [comment]
华为mate20 HarmonyOS 4.0也有这个问题

**Comment by guozhigq** [comment]
最新版已修复
