### ISSUE TITLE
顶部白色

### ISSUE THREAD

**Issue by RzdPai** [guozhigq/pilipala#1087]
最新测试版
(fix: 字幕匹配异常fix: 专栏异常opt: 竖屏视频查看)(https://t.me/c/1380351980/54556)
顶部一片白![Screenshot_2024-11-17-21-14-10-01_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/d185978c-907d-4237-8068-f79ff13b86f5)

**可以通过改为浅色模式再改为深色模式解决**

**Comment by guozhigq** [comment]
ok

**Comment by Lucas04-nhr** [comment]
遇到同样的问题，插个锚点，目前是下面几个页面有问题：动态首页，点击相关UP主的动态页面，以及动态评论区页面。似乎“我的”页也会有概率出现

![Screenshot_2024_1118_213531.png](https://github.com/user-attachments/assets/4fa2c12d-8199-45b3-bb33-fa015c66e1a1)

![Screenshot_2024_1118_213550.png](https://github.com/user-attachments/assets/80a1a56e-5dbf-4d39-b1fe-5e53043eb3a3)

![Screenshot_2024_1118_213817.png](https://github.com/user-attachments/assets/18c6770d-b927-4a72-9641-5440ddce4e47)

**Comment by Lucas04-nhr** [comment]
作者在最新的beta版本中已经修复了这个问题
