### ISSUE TITLE
视频投币背景灰屏

### ISSUE THREAD

**Issue by 321yida** [guozhigq/pilipala#109]
### 问题描述
视频投币背景灰屏

### 复现步骤
点击任意视频，投币，过程中导致背景灰屏

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
手机设备：IQQO neo6 se
Pilipala 1.0.7
Android 13

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![3348ba35ec7cc88dfa4e487a27d89d07](https://github.com/guozhigq/pilipala/assets/67246596/edf646a0-495d-404c-b6ae-d6e5032326fb)

**Comment by guozhigq** [comment]
重新下载release中的1.0.7版本吧，这个bug修复了
