### ISSUE TITLE
视频与动态无法点赞

### ISSUE THREAD

**Issue by 321yida** [guozhigq/pilipala#110]
### 问题描述
在pilipala动态栏，视频与动态无法点赞，提示connected with wifi network 网络异常，请稍后重试

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
手机设备：IQQO neo6 se
Pilipala 1.0.7
Android 13

### 相关截图或日志

![2c4a71c0bf6ab3db10747fe2a06dd6e3](https://github.com/guozhigq/pilipala/assets/67246596/03d4b96f-3f7b-474b-a982-029d721a2e0b)

**Comment by guozhigq** [comment]
重新下载release中的1.0.7版本吧，这个bug修复了
