### ISSUE TITLE
直播横屏播放下进入画中画然后再全屏化会显示灰屏

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#1100]
如标题所述

https://github.com/user-attachments/assets/950b47f7-8231-4a87-a8b8-c626f596f5f7

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
      [Get] the improper use of a GetX has been detected. 
      You should only use GetX or Obx for the specific widget that will be updated.
      If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
      or insert them outside the scope that GetX considers suitable for an update 
      (example: GetX => HeavyWidget => variableObservable).
      If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.
------- 错误堆栈 -------
Line0      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:29)
Line1      ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:56)
Line2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
Line3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
Line4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line6      StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line7      Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line10     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line11     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line12     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line13     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line16     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line18     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line20     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line21     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line22     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line24     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line25     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
Line26     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line28     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line29     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line30     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line32     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line34     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line35     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
Line36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line37     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line39     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line40     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line41     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line44     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line45     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line46     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line49     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line50     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line51     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line53     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line55     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line58     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line59     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line60     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line62     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line64     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line65     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line66     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line68     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line71     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line72     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line73     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line76     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line77     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line78     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line80     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line82     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line84     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line85     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line86     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line88     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line89     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line90     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line92     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line93     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line94     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line95     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line97     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line99     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line101    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line103    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line104    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line106    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line107    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line108    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line109    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line112    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line113    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line114    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line117    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line118    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
Line119    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
Line120    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
Line121    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
Line122    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
Line123    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
Line124    _invoke (dart:ui/hooks.dart:312)
Line125    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
Line126    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
最新版已修复
