### ISSUE TITLE
进主页不显示头像，无法发消息给up

### ISSUE THREAD

**Issue by mekimali** [guozhigq/pilipala#1101]
![Screenshot_2024-11-22-13-42-21-42_130b0d7520509a75c6a4102c4ba0249d](https://github.com/user-attachments/assets/26ed1e8e-e168-4020-b43e-308e4269e48e)
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by FlootingDream** [comment]
点自己的头像同样不展示个人信息

**Comment by Lucas04-nhr** [comment]
作者似乎在最新的beta版本已经修复，可以在telegram频道下载

**Comment by guozhigq** [comment]
最新版已修复
