### ISSUE TITLE
未找到暗黑模式设置

### ISSUE THREAD

**Issue by WhitLor** [guozhigq/pilipala#1102]
### 功能描述
深色模式是否考虑添加暗黑模式（纯黑）

**Comment by xihale** [comment]
![Screenshot_20241207_134451.jpg](https://github.com/user-attachments/assets/68bb5f03-8a16-47e9-a6bf-212172747c9d)

点击头像后这里有转换开关。

**Comment by WhitLor** [comment]
谢谢，我想反馈的是没有A屏纯黑模式

**Comment by guozhigq** [comment]
最新版已支持
