### ISSUE TITLE
关于评论区、视频收藏、个人空间的BUG反馈

### ISSUE THREAD

**Issue by FlootingDream** [guozhigq/pilipala#1105]
### 问题描述
1. 未找到评论删除功能
2. 未找到新建收藏夹功能
3. 点击自己或up头像进入个人空间，不能正常展示个人信息 (短暂展示后直接消失)
4. 个人空间中的搜索功能不能使用

**Comment by guozhigq** [comment]
3 4重复

**Comment by HongXuan55** [comment]
评论为啥没有删除功能嘞？🙃

**Comment by guozhigq** [comment]
最新版已支持
