### ISSUE TITLE
部分页面导航栏不沉浸

### ISSUE THREAD

**Issue by fddzwm-bit** [guozhigq/pilipala#1109]
### 问题描述
部分页面导航栏不沉浸

### 复现步骤
清除后台，第一次进入软件，主页下导航栏沉浸；进入视频详情页，导航栏不沉浸；退出视频详情页，主页下导航栏也变为不沉浸

### 预期行为
每个页面的尽量使导航栏沉浸

### 系统信息
小米14Pro Android15 hyperOS2.0.7.3
pilipala 1.0.25

### 相关截图或日志
![IMG_20241125_220628](https://github.com/user-attachments/assets/2223e986-0fc0-4c9f-8b0f-eeb4b56f6bd3)

**Comment by guozhigq** [comment]
最新版已修复
