### ISSUE TITLE
关注功能优化

### ISSUE THREAD

**Issue by Lucas04-nhr** [guozhigq/pilipala#1110]
### 功能描述
目前在关注列表页面点击已关注只能修改分组，在用户主页点击已关注则只能取消关注，感觉逻辑有点割裂

### 目标
希望将这两个操作统一，即不管在哪个页面点击已关注都能便捷地进行取消关注/修改分组操作

### 解决方案
~~暂无~~

### 其他
可以参考官方App在这个功能上的操作逻辑

**Comment by guozhigq** [comment]
最新版已支持
