### ISSUE TITLE
弹幕设置问题

### ISSUE THREAD

**Issue by Wt1953** [guozhigq/pilipala#1114]
### 问题描述
修改过弹幕速度后，长按倍速松开，弹幕速度会重置。设置完弹幕，退出视频再进入所有的弹幕设置都会重置。

### 复现步骤
在播放视频里进行弹幕时间设置，修改后长按视频倍速播放，松开后弹幕时间重置回默认速度。
修改完弹幕设置退出视频，重新进入弹幕设置全部会重置。

### 预期行为
设置完弹幕速度后会记忆，长按倍速不会重置。
弹幕设置能够记忆，不会重置。

**Comment by Wt1953** [comment]
翻了下提问区，发现只要设置完直接退出软件，再重新进入就可以记忆了，希望加个提示😁

**Comment by guozhigq** [comment]
> 翻了下提问区，发现只要设置完直接退出软件，再重新进入就可以记忆了，希望加个提示😁

不是，确实是bug 🤣
