### ISSUE TITLE
出现两个相同评论

### ISSUE THREAD

**Issue by RzdPai** [guozhigq/pilipala#1115]
![Screenshot_2024-11-26-23-21-31-94_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/2fcca2d4-c3d8-482a-b607-e3769c313108)

需跳转到原视频打开评论会出现

**Comment by guozhigq** [comment]
怎么可以复现呢

**Comment by RzdPai** [comment]
> 怎么可以复现呢

![IMG_20241129_062223.jpg](https://github.com/user-attachments/assets/97ac3a69-7aa0-40cd-b517-d15dbf6238bc)

在回复我的–打开原视频–找到自己的评论

**Comment by guozhigq** [comment]
我这一直没复现，可以试试最新版

**Comment by RzdPai** [comment]
> 我这一直没复现，可以试试最新版

最新版还是这样

**Comment by RzdPai** [comment]
> 我这一直没复现，可以试试最新版

https://t.me/c/1380351980/56563
