### ISSUE TITLE
无法保存弹幕设置

### ISSUE THREAD

**Issue by Louise-Valliere** [guozhigq/pilipala#1122]
### 问题描述
在一个视频中调整弹幕透明度、速度设置后，打开新视频弹幕设置会自动充值到默认状态

### 复现步骤
打开某视频→弹幕设置→更改透明度速度→关闭视频→打开任意视频→发现设置被重置

### 预期行为
打开新视频后更改过的设置保留

### 系统信息
Vivo iQOO Z6 (安卓14/Origin OS 4)

### 相关截图或日志
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: UP1A.231005.007
board: lahaina
bootloader: unknown
brand: vivo
device: PD2220
display: PD2220_A_14.2.7.0.W10.V000L1
fingerprint: vivo/PD2220/PD2220:14/UP1A.231005.007/compiler10182220:user/release-keys
hardware: qcom
host: comdg01146198
isPhysicalDevice: true
manufacturer: vivo
model: V2220A
product: PD2220
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: compiler10182220
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-09-01
------- 应用信息 -------
environment: release
version: 1.0.25
appName: PiliPala
buildNumber: 10253
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
Line0      _StreamController.add (dart:async/stream_controller.dart:605)
Line1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
最新版已修复
