### ISSUE TITLE
希望可以加入私信功能呢

### ISSUE THREAD

**Issue by weiDpang** [guozhigq/pilipala#113]
### 功能描述
如果方便，还麻烦加上私信功能，以方便回复评论之类的。

**Comment by guozhigq** [comment]
目前开发进度主要是视频播放、动态、个人菜单，私信功能在**计划内**但优先级不高，

**Comment by Dough-su** [comment]
> 目前开发进度主要是视频播放、动态、个人菜单，私信功能在**计划内**但优先级不高，

如果私信开发，我之前有些过一个项目可以发送b站的私信[](https://github.com/Dough-su/bilibili_message)

**Comment by orz12** [comment]
> > 目前开发进度主要是视频播放、动态、个人菜单，私信功能在**计划内**但优先级不高，
> 
> 如果私信开发，我之前有些过一个项目可以发送b站的私信

私信我在做了 但我目前进度很慢

**Comment by guozhigq** [comment]
已实现
