### ISSUE TITLE
隐藏“首页”栏后因为设置要点击头像进入，无法进入设置

### ISSUE THREAD

**Issue by kxuahkcifjnw** [guozhigq/pilipala#1131]
### 问题描述
在设置里隐藏首页栏后，因为设置界面似乎是和首页栏的头像（登录账号）绑定在一起的，导致无法进入设置

#604 # 预期行为
在其他栏里增加设置的入口，或者如果首页栏隐藏所有的推荐、直播等内容，就直接显示用户界面和进入设置的入口

### 系统信息
ios16.2

**Comment by guozhigq** [comment]
最新版已支持
