### ISSUE TITLE
能不能加一个功能呢？

### ISSUE THREAD

**Issue by ohtfbbxy33** [guozhigq/pilipala#1132]
### 问题描述
![Screenshot_20241206_211212.jpg](https://github.com/user-attachments/assets/39e9325c-64b2-409a-a239-b5bba1286b4b)

如图b站这个投稿这里有个继续播放，可以按时间正序或者倒叙播放up所有的视频。这种音乐类的很好用

**Comment by xihale** [comment]
建议把标题改成：功能索求：继续播放
把tag改成：feature wants

**Comment by guozhigq** [comment]
最新版已支持
