### ISSUE TITLE
对学习版的请求

### ISSUE THREAD

**Issue by Zorlivan** [guozhigq/pilipala#1135]
### 功能描述
希望可以对包括但不限于直播,弹幕,热搜推荐,评论区等功能进行阉割,实现一个比原版哔哩哔哩更好的学习效果,原版哔哩哔哩的课堂模式和青少年模式过于繁琐和困难,甚至限制了很多不该限制的功能,有的限制功能甚至是做了一半就抛开不管的.
比如课堂模式下,"我的"页面无法点击进入关注列表,而在"我的"页面进入"我的空间"后,却可以点击进入关注列表,虽然会弹出课堂模式的提示页面,但是点击返回就可以正常查看关注列表.
### 目标
渴望拥有一个没有弹幕,评论区,热搜等功能,甚至可以根据算法优化不断推送学习内容的pilipala.
### 致谢
对作者和各位不断提供改进优化的coders,表达最诚恳的感谢!

**Comment by xihale** [comment]
据我所知，数据推送是服务器的事情，pilipala只是作为数据展示，算法优化学习内容对于pilipala是不可能做到的。
其次，弹幕可以关，而热门也并不是默认打开的，评论也是不点击就不会展示，我觉得没有必要做什么阉割版，也许你可以clone一份源码自己删除对应的组件（毕竟你只要最基础的功能就满足了）。

**Comment by Zorlivan** [comment]
醍醐灌顶了,感谢您,其实还是自己自制力不够好,很多时候不能总想着让别人给自己做什么,要自己对自己负责.

**Comment by xihale** [comment]
没事，加油吧，一步一脚印，慢慢来！

**Comment by KervynH** [comment]
希望可以增加移除首页、移除动态、移除所有推荐视频的开关，哔哩漫游模块都有做的

**Comment by guozhigq** [comment]
最新版可以只保留【我的】页面，评论区也支持关闭

**Comment by Zorlivan** [comment]
> 最新版可以只保留【我的】页面，评论区也支持关闭
感谢您！
我在发布issue后，才注意到设置里的选项类型，可以手动关闭包括直播，首页等等在内的功能。
再次向作者和各位开发人员致以诚恳的感谢！
