### ISSUE TITLE
希望添加评论区用户查成分功能 

### ISSUE THREAD

**Issue by dandandedd** [guozhigq/pilipala#1138]
### 功能描述
B站评论区自动标注成分，例如⚪神，抽奖等

### 目标
现如今互联网低龄化严重😨，此项功能可以鉴别烦人的小鬼😒
如图：
<img width="803" alt="666" src="https://github.com/user-attachments/assets/d345bce4-6e84-45f8-95a0-6782729420cf">

### 解决方案
另一位大佬开发了网页端的解决方案
油猴链接：https://greasyfork.org/zh-CN/scripts/462288-%E6%94%B9-b%E7%AB%99%E6%88%90%E5%88%86%E6%A3%80%E6%B5%8B%E5%99%A8
GitHub链接：https://github.com/hmjz100/bilibili-comment-checker

### 其他
补充说明：目前B站充斥着大量的人机评论与人机up主，初步判断方式为：用户关注数往往高达成百上千，希望有功能可以精准识别，我想出的解决办法是关注数超过一定数值即可判断为人机
人机如图：
![image](https://github.com/user-attachments/assets/446ef17b-2fc7-418f-8494-8c46ba6f5e6c)

作者大佬辛苦了，给你点个小星星

**Comment by ZHAOsir05** [comment]
我持反对意见，该功能本质上是一种贴标签行为，而且原理实现上很浪费资源，建议你分清虚拟与现实，不要在网上跟人对线

**Comment by ZHAOsir05** [comment]
我持反对意见，该功能本质上是一种贴标签行为，而且原理实现上很浪费资源，建议你分清虚拟与现实，不要天天在网上跟人对线
