### ISSUE TITLE
希望添加强制刷新率

### ISSUE THREAD

**Issue by OH016** [guozhigq/pilipala#115]
每次自动都是60hz 用起来很难受 希望能添加一个强制刷新率的选项

**Comment by guozhigq** [comment]
了解，正在找解决办法

**Comment by OH016** [comment]
https://github.com/wgh136/PicaComic/issues/113 这个项目解决了这个问题 推荐看看这个项目怎么实现的

**Comment by guozhigq** [comment]
> [wgh136/PicaComic#113](https://github.com/wgh136/PicaComic/issues/113) 这个项目解决了这个问题 推荐看看这个项目怎么实现的

好的，抽空看看
