### ISSUE TITLE
无法连接网络

### ISSUE THREAD

**Issue by Ivanzishidai** [guozhigq/pilipala#1151]
### 问题描述
在网络状态正常的情况下打开客户端显示无法连接网络。
### 手机型号与操作系统
红米k40pro Android14
### 相关截图1
![Screenshot_2024-12-16-13-40-27-010_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/ac6ebca0-b11b-4d2b-b2ab-617a9f4244e9)
### 相关截图2
连接代理后显示正在使用移动流量...
![Screenshot_2024-12-16-13-48-20-461_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/5652968d-0659-47b8-bce1-6d6b627b0ef8)

**Comment by guozhigq** [comment]
关闭港澳台试试

**Comment by Ivanzishidai** [comment]
> 关闭港澳台试试

###关闭港澳台模式后动态页面显示我未登录，但实际上我已经登陆了😂
![Screenshot_2024-12-16-17-20-47-718_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/e4e5655a-9e87-4b42-b030-054f02ae6657)
