### ISSUE TITLE
新视频不应显示上一个的画面

### ISSUE THREAD

**Issue by lenny20** [guozhigq/pilipala#118]
### 问题描述
播放某个视频，缓冲时较慢，初始画面时上一个视频结束的静止画面，甚至长视频缓冲时还会有残响。好像网速比用官版慢。

### 复现步骤
只要点击一个新视频，开头缓冲时就会呈现上次播过的画面，长视频缓冲时还会有残响。

### 预期行为
希望重用对应视频的封面图，或者黑屏，不要显示上次播放的画面；最好还能加快连接速度。

### 系统信息
Mate20，HOS 3.0，Pili 1.0.7

### 相关截图或日志
我搜“沧海一声笑”笛子的几个视频发现的。
“脖子保卫战”切换多集视频时会出现上个视频的残响。

**Comment by do02fw** [comment]
我也感觉视频加载速度比官方版慢，不知道为什么

**Comment by guozhigq** [comment]
「显示上一个的画面 」是播放器插件的问题，待解决。
「视频加载速度比官方版慢」还在找原因

**Comment by do02fw** [comment]
有没有可能是DNS解析或者HTTP协议的问题，官方是HTTP2

**Comment by guozhigq** [comment]
> 有没有可能是DNS解析或者HTTP协议的问题，官方是HTTP2

目前用的就是HTTP2，可能是视频解析慢

**Comment by guozhigq** [comment]
最近还有这个问题吗
