### ISSUE TITLE
看视频的时候点击up主页再返回播放页面播放进度会清零

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#121]
### 问题描述
请提供一个清晰而简明的问题描述。
看视频的时候点击up主页再返回播放页面播放进度会清零且重新加载
### 复现步骤
请提供复现该问题所需的具体步骤。
看视频的时候点击up主页再返回播放页面播放进度会清零
### 预期行为
请描述你期望的正确行为或结果。
不清零不重新加载
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android14最新版
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230915_210739](https://github.com/guozhigq/pilipala/assets/138294823/9e7df2f3-ca86-451c-a18b-82b703a92086)

**Comment by guozhigq** [comment]
没有复现，持续观察 👀 中

**Comment by Nottodaymore** [comment]
> 没有复现，持续观察 👀 中

有个类似的bug，复现了。关闭进入详情页自动播放设置，进入第一个视频详情页，不点击播放按钮，点击下方的关联视频，进入第二个视频详情页，再点击下方关联视频，进入第三个视频的详情页，这时返回主页，查看历史记录，第一个和第二个视频虽然没有播放，但在历史记录中出现，进度0：00

**Comment by guozhigq** [comment]
最新还有这个问题吗
