### ISSUE TITLE
大家都在搜变空白了

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#122]
### 问题描述
请提供一个清晰而简明的问题描述。
大家都在搜变空白了
### 复现步骤
请提供复现该问题所需的具体步骤。
不知道，点击搜索就这样了
### 预期行为
请描述你期望的正确行为或结果。
正常的
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android14最新版
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230915_211553](https://github.com/guozhigq/pilipala/assets/138294823/bf039f6e-aa85-4203-add5-0376af449af5)

**Comment by guozhigq** [comment]
了解，这个问题正在修复。我看了一下105跟106版本都空白了，好像是接口数据格式改了
