### ISSUE TITLE
视频图片无法点开

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#128]
视频BV1834y1T75W中的一条文字为“超狹窄通勤電車站”的评论中的部分图片点击后会直接进入评论详情而不是图片预览。
视频：https://github.com/guozhigq/pilipala/assets/106989902/fa6ce683-838b-4583-aa8b-1216d6e05e9f

**Comment by guozhigq** [comment]
没有复现，等更新了1.0.8再观察一下吧

**Comment by guozhigq** [comment]
先关闭了
