### ISSUE TITLE
点头像进自己主页 主页的内容和投稿都是空白打不开

### ISSUE THREAD

**Issue by Bawts** [guozhigq/pilipala#131]
### 问题描述
主页打不开 关注人的列表也打不开是空白 我习惯先点赞之后再看 现在打不开没办法看之前点赞的视频了

### 预期行为
修复内容页

### 系统信息
lg 安卓11 内核版本4.14.186+ 

### 相关截图或日志
![QQ图片20230918015004](https://github.com/guozhigq/pilipala/assets/74176852/59a2cf37-216e-46d7-83e1-783ccd071819)
![Screenshot_20230918-014226](https://github.com/guozhigq/pilipala/assets/74176852/e5cbda67-d17b-47c4-82e9-5a327d970c6a)

**Comment by guozhigq** [comment]
已修复，下载最新的108.0918版本安装即可

**Comment by Bawts** [comment]
> 已修复，下载最新的108.0918版本安装即可

已下载 投稿问题修复了 主页还是空白只有主页两个字 包括自己和别人的主页都打不开 是我的设备的问题吗

**Comment by guozhigq** [comment]
主页还没有开发2023年9月18日 17:42，Bawts ***@***.***>写道：

已修复，下载最新的108.0918版本安装即可

已下载 投稿问题修复了 主页还是空白只有主页两个字 包括自己和别人的主页都打不开 是我的设备的问题吗
