### ISSUE TITLE
解除搜索的过滤

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#139]
### 功能描述
请提供对所请求功能的清晰描述。
解除搜索的过滤，比如搜索萝莉之类的词，如果是官方版的话搜不出来，希望这里可以让搜出来
### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
因为PiliPala的数据是请求官方api而来的，所以无法实现该功能
