### ISSUE TITLE
评论框增加emoji表情

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#141]
### 功能描述
请提供对所请求功能的清晰描述。
评论框增加emoji表情，手机里的输入法emoji表情并不完整，希望可以把所有以及最新的emoji表情加进去，这样更方便使用emoji表情，以及更好的抽象和阴阳怪气，https://getemoji.com/
### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
