### ISSUE TITLE
增加过滤起飞推广和创作推广视频的功能

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#142]
### 功能描述
请提供对所请求功能的清晰描述。
增加过滤起飞推广和创作推广视频的功能，并且默认保持开启状态
![Screenshot_20230918_183057](https://github.com/guozhigq/pilipala/assets/138294823/87856777-2b47-4257-b8f4-6c45293f9347)
![Screenshot_20230918_183105](https://github.com/guozhigq/pilipala/assets/138294823/67d9146b-b773-444d-b491-239907be46f1)

### 目标
请描述你希望通过这个功能实现的目标。
过滤起飞推广和创作推广的视频
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
现在默认是过滤的
