### ISSUE TITLE
无法直接查看被转发动态的评论

### ISSUE THREAD

**Issue by AnyoeDove** [guozhigq/pilipala#147]
### 问题描述
无法直接查看被转发动态的评论，点击跳转至原动态时评论区显示请求错误。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
能够查看原动态评论。

### 系统信息
iQOO z7x, Android 13.

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/10519576/3fcadf69-e6c4-4d43-a213-aed04f0fb117

**Comment by guozhigq** [comment]
最近还有这个问题吗
