### ISSUE TITLE
使用try_look参数实现免登录观看1080P视频

### ISSUE THREAD

**Issue by HashLiver** [guozhigq/pilipala#149]
### 功能描述

免登录观看1080P视频的解决方案

### 目标

* 免登录观看1080P视频

### 解决方案

网页端的试看按钮其实就是在Playurl api上加上`try_look`参数，使用该参数便可获取1080P的视频链接。

![试看按钮](https://github.com/guozhigq/pilipala/assets/42889797/190cd9ba-4970-4639-b9d0-238287878c38)
![try_look](https://github.com/guozhigq/pilipala/assets/42889797/af82e041-6d62-4521-9e08-13afd3b09e26)

Playurl api 加上`try_look`参数前后的对比（请在隐身窗口下打开）：
* https://api.bilibili.com/x/player/playurl?bvid=BV1G94y1p7t8&cid=1271640352&qn=80&fnver=0&fnval=4048&fourk=1

* https://api.bilibili.com/x/player/playurl?bvid=BV1G94y1p7t8&cid=1271640352&qn=80&fnver=0&fnval=4048&fourk=1&try_look=1

### 其他

下面两款应用都支持免登录观看或下载1080P视频：

* 支持Bilibili、NicoNico的第三方Android应用[PipePipe](https://codeberg.org/NullPointerException/PipePipe)加入此功能的[commit](https://codeberg.org/NullPointerException/PipePipeExtractor/commit/9bc6fdd74012b73175cf36a3f77b93e730971fea);
* 命令行下载器[BBDown](https://github.com/nilaoda/BBDown)加入此功能的[commit](https://github.com/nilaoda/BBDown/commit/45d0a73ced1e5caca3684496cb59f6932745e754).

**Comment by guozhigq** [comment]
确实可以 👍
