### ISSUE TITLE
首页显示动态有图片，点进去却没有

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#153]
### 问题描述
请提供一个清晰而简明的问题描述。
首页显示动态有图片，点进去却没有
### 复现步骤
请提供复现该问题所需的具体步骤。
首页点图片的动态
### 预期行为
请描述你期望的正确行为或结果。
图片正常显示
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android14，1.0.8
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230921_020122](https://github.com/guozhigq/pilipala/assets/138294823/3f729604-01fe-432a-bb2d-d915eea342fd)

![Screenshot_20230921_020127](https://github.com/guozhigq/pilipala/assets/138294823/1c79c155-42c1-48eb-ab9d-6b420d2f18af)

**Comment by guozhigq** [comment]
最近的版本还有这个问题吗

**Comment by do02fw** [comment]
> 最近的版本还有这个问题吗

应该没有了，好久没用
