### ISSUE TITLE
旋转后播放器状态栏占位错误

### ISSUE THREAD

**Issue by JackA1ltman** [guozhigq/pilipala#161]
### 问题描述
请提供一个清晰而简明的问题描述。
如图，重力感应旋转后播放器下半部分被状态栏挤压下去了，但是按按钮选择放大则没有这个问题

### 复现步骤
请提供复现该问题所需的具体步骤。
使用重力感应旋转屏幕有可能会触发

### 预期行为
请描述你期望的正确行为或结果。
和按钮一样完整全部状态栏沉浸

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android 11，一加8

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230922-163157.jpg](https://github.com/guozhigq/pilipala/assets/82563979/e1f924c1-56da-4642-a0c4-683b67d95bff)

**Comment by guozhigq** [comment]
目前还没有做横屏时自动全屏的功能，出现上述情况只是因为在横屏状态下依然是竖屏的样式

**Comment by xfdyd** [comment]
> 目前还没有做横屏时自动全屏的功能，出现上述情况只是因为在横屏状态下依然是竖屏的样式

我想起相关的bug。如果开启自动全屏，进一个视频，再退出全屏，下面就只看到推荐视频，本视频的信息就都显示不出来了。

**Comment by guozhigq** [comment]
> > 目前还没有做横屏时自动全屏的功能，出现上述情况只是因为在横屏状态下依然是竖屏的样式
> 
> 我想起相关的bug。如果开启自动全屏，进一个视频，再退出全屏，下面就只看到推荐视频，本视频的信息就都显示不出来了。

109版本将修复

**Comment by VillagerTom** [comment]
这个问题在我的手机上曾经在v1.0.14修复了，然后到了_1.0.16测试版它又回来了🤣

**Comment by VillagerTom** [comment]
嗷，又修复了啊，那没事了（
