### ISSUE TITLE
希望横向滑动 拖的进度少一点😭

### ISSUE THREAD

**Issue by CarryLeeS** [guozhigq/pilipala#164]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by xfdyd** [comment]
我觉得有时太少了，不过总体还行。这个不同人可能有不同的需求，也可以搞个自定义。但我觉得默认的设置应该接近官方版。
