### ISSUE TITLE
“投稿”内容没有刷新

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#166]
### 问题描述
从 bilibili APP 创建的账户的桌面图标进入，再回到桌面，进入另一个账户，这时，“投稿”还是上一个账户的只不过往后刷了。

**Comment by xfdyd** [comment]
希望支持创建账户的桌面图标。

**Comment by guozhigq** [comment]
好的

**Comment by guozhigq** [comment]
> 希望支持创建账户的桌面图标。

这个可能满足不了

**Comment by xfdyd** [comment]
> > 希望支持创建账户的桌面图标。
> 
> 这个可能满足不了

那么加个账户收藏吧。

**Comment by guozhigq** [comment]
> > > 希望支持创建账户的桌面图标。
> > 
> > 
> > 这个可能满足不了
> 
> 那么加个账户收藏吧。

账户收藏等同于关注UP？
