### ISSUE TITLE
希望将up主视频与剧集分开展示

### ISSUE THREAD

**Issue by ELE-Clouds** [guozhigq/pilipala#167]
### 功能描述
当在搜索栏输入关键字并点击搜索按钮后，所有UP主提交的视频全部归类到视频标签栏展示，所有培训教程类的视频全部归类到教程或课程标签栏展示，所有动漫或其它电影、电视连续剧之类的剧集全部归类到番剧标签栏展示。

### 目标
快速搜索并查找到想要的视频。

**Comment by guozhigq** [comment]
目前实现不了或者说没必要，不同的搜索内容请求参数不一样，返回的数据格式也不一样。

拿「所有动漫或其它电影、电视连续剧之类的剧集全部归类到番剧标签栏展示」举例来说
如果搜索某一条内容，动漫有5页数据、电影有3页数据、电视连续剧有13页数据，优先展示哪个，如何完成分页都是问题。
