### ISSUE TITLE
支持关闭“推荐”页

### ISSUE THREAD

**Issue by Sciroccogti** [guozhigq/pilipala#168]
### 功能描述
经常会刷推荐刷到不能自已，感觉要是能直接关闭“推荐”页就好了！

**Comment by lenny20** [comment]
我希望能关闭“直播”页，有时候下滑会误刷至“直播”不能自已，感觉要是能设置关闭“直播”页就好了！

**Comment by Sciroccogti** [comment]
emmm看起来可能很好笑，但是对于自制力极差的人来说也是没办法的办法了。同时我也感觉自定义修改 首页Tab 应该也是一个易于实现且可能挺有需求的功能。

**Comment by psychosispy** [comment]
要是能关闭底栏首页这个tab就好了，个人一般只用搜索，感觉算法推的都不太行
