### ISSUE TITLE
合集不能自动播放下一集

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#169]
### 问题描述
比如这里：
https://www.bilibili.com/video/BV1uj411y79v
不会自动播放下一集。
而且会放完这集后会重新播放这集，这在其他地方也有出现。这就很困扰了，至少这不应该出现，就还好用。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by lenny20** [comment]
我提过这建议，好像正在开发吧，耐心等等。这不算bug，是新功能。

**Comment by guozhigq** [comment]
跟  issues #116  重复
