### ISSUE TITLE
亮度记忆，应该统一

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#170]
### 功能描述
每个视频的亮度应该统一，就不用每个视频都重新设置一次亮度了。

**Comment by xfdyd** [comment]
另外一个bug：在播放器改变清晰度，亮度记忆会消失。

**Comment by xfdyd** [comment]
还有一个bug，有时全屏时按手机回退键，没有退出，只是变成了竖屏。

**Comment by xfdyd** [comment]
还有bug：当开启自动全屏时，跳出来选择合集，就会在视频播放前执行全屏，并因此失败。

**Comment by guozhigq** [comment]
> 另外一个bug：在播放器改变清晰度，亮度记忆会消失。

试试打开  「设置」 - 「播放设置」 - 「亮度记忆」 项
