### ISSUE TITLE
软件第一次打开的第一条动态可能无法打开

### ISSUE THREAD

**Issue by JackA1ltman** [guozhigq/pilipala#174]
### 问题描述
请提供一个清晰而简明的问题描述。
如果刚刚打开app，如果第一条是动态，就会出现那个动态加载不出来

### 复现步骤
请提供复现该问题所需的具体步骤。
第一次打开app或者偶发性第一条如果是动态

### 预期行为
请描述你期望的正确行为或结果。
可以正常显示

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android 11，一加8

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230930-204121.jpg](https://github.com/guozhigq/pilipala/assets/82563979/afe2ec4c-b21a-4c6b-a82d-1bd3620bdff6)

![Screenshot_20230930-204124.jpg](https://github.com/guozhigq/pilipala/assets/82563979/de7f20c9-5f0d-4e10-b529-a3a8de58fd50)

![Screenshot_20230930-204128.jpg](https://github.com/guozhigq/pilipala/assets/82563979/5af3e34b-d813-4352-98ff-7ecc34fd9cf3)

![Screenshot_20230930-204135.jpg](https://github.com/guozhigq/pilipala/assets/82563979/2b91399d-e326-442a-b8c6-6cfe29c1d869)

**Comment by guozhigq** [comment]
最近的版本应该没这个问题了吧
