### ISSUE TITLE
退出视频页后还有声音

### ISSUE THREAD

**Issue by jinrikuaile** [guozhigq/pilipala#175]
### 问题描述
请提供一个清晰而简明的问题描述。
退出视频页后还有声音，新开视频也无法停止声音。直接变二重唱。
### 复现步骤

Uploading Screenrecorder-20231001-010439.mp4…

偶发性，不确定复现
### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by jinrikuaile** [comment]
https://github.com/guozhigq/pilipala/assets/29156508/3af8277d-3765-47c1-b2be-7e9a03ede6f4

补充视频

**Comment by lenny20** [comment]
这问题我提交过，退出视频和下次播放都有残响，而且缓冲很久不如官版迅速。
开发者说是“播放器插件的问题，待解决”。“视频加载速度比官方版慢”还在找原因。

**Comment by lenny20** [comment]
当前最强的播放器是MXplayer和MPC-BE，不知能否从中找到灵感。
