### ISSUE TITLE
于图文动态页面无法点开图片查看大图

### ISSUE THREAD

**Issue by GreyElaina** [guozhigq/pilipala#177]
### 问题描述
于图文动态页面无法点开图片查看大图，例如[这则动态](https://t.bilibili.com/847500384437010562?detail_view_bits=1)。

### 复现步骤
在问题描述中所提及的动态中可以稳定复现……除非，你没做查看图片大图的功能？那可以联系我将这个 issue 重写为 Feature Request。

### 预期行为
我能够点开缩略图查看，除此之外……希望能多考虑一下长图，左右滑动分页等用户逻辑与情景。

### 系统信息
Android 13。

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/31543961/b0ad87b8-369c-4e43-aee6-5effe1d04259

**Comment by guozhigq** [comment]
已实现

**Comment by GreyElaina** [comment]
🫠辛苦
