### ISSUE TITLE
搜索框中有推荐搜索词，但不能直接搜索

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#179]
### 问题描述
无论是回车还是点击搜索按钮，都没有反应。这个不是每次出现。

### 系统信息
安卓6，webview 106。

**Comment by xfdyd** [comment]
其实对于我，最重要的bug是视频还是会重新播放，我还不能够真正使用呢。

**Comment by xfdyd** [comment]
另外一个bug：选择合集里面的视频后，外面显示第几个视频的数字经常不刷新。

**Comment by xfdyd** [comment]
另外一个bug：视频有时候没有声音，可能是我在更改编码后，立即快进或快退了一下。

**Comment by guozhigq** [comment]
> 另外一个bug：选择合集里面的视频后，外面显示第几个视频的数字经常不刷新。

已知问题，109版本修复

**Comment by guozhigq** [comment]
> 其实对于我，最重要的bug是视频还是会重新播放，我还不能够真正使用呢。

播放到一半突然回到起始位置么

**Comment by guozhigq** [comment]
v1.0.20 中已更新，可以试试
