### ISSUE TITLE
请问，哪个版本视频不会跳回？

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#183]
### 系统信息
安卓6，骁龙435。

另外，在评论输入框中长按选择文字，上面的提示动画有点近。

**Comment by xfdyd** [comment]
似乎总是在1分钟时，出现跳回。

**Comment by guozhigq** [comment]
> 在评论输入框中长按选择文字，上面的提示动画有点近。

这个没办法修改，是框架决定的

**Comment by guozhigq** [comment]
最新版应该没问题了吧，你看看
