### ISSUE TITLE
视频播放一会儿之后会突然从头开始播放，而且是加速播放

### ISSUE THREAD

**Issue by anjinga** [guozhigq/pilipala#185]
### 问题描述
视频播放一会儿之后会突然从头开始播放，而且是加速播放，已经遇到过很多次了

### 复现步骤
似乎是在进行过快进或者快退之后会出现这种现象

### 预期行为
希望能正常播放，不要突然跳转到开头，很影响观看体验

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
老哥什么机型，还有安卓版本是？

**Comment by flaribbit** [comment]
红米 K60pro 安卓 13 快进之后遇到了，但无法稳定复现

**Comment by Daydreamer-riri** [comment]
同样的问题。复现频率较低，出现时音频依旧正常，但是画面会以加速的形式从某个位置播放，直到和音频同步后正常继续播放。
我认为这可能是上游的问题？

手机：pixel 8 pro
系统：Android 14

**Comment by anjinga** [comment]
> 老哥什么机型，还有安卓版本是？

红米note11Tpro  安卓13
最近又出现过几次，都是视频突然回退然后开始加速播放

**Comment by guozhigq** [comment]
最近的版本还有这个问题吗

**Comment by Daydreamer-riri** [comment]
> 最近的版本还有这个问题吗

感觉没有了
