### ISSUE TITLE
希望有主题图标

### ISSUE THREAD

**Issue by khzz1104** [guozhigq/pilipala#187]
### 功能描述
能给pilipala做一个主题图标吗 应用内都有动态取色但是桌面没有看起来不太协调

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by Daydreamer-riri** [comment]
我可以来支持，可以放到1.0.11？

**Comment by guozhigq** [comment]
> 我可以来支持，可以放到1.0.11？

可以的，具体可以看一下 https://github.com/fluttercommunity/flutter_launcher_icons/issues/419 ，可能需要一个纯白色背景透明的图标

**Comment by Daydreamer-riri** [comment]
已合并
