### ISSUE TITLE
动态显示问题

### ISSUE THREAD

**Issue by izoKiro** [guozhigq/pilipala#193]
### 问题描述
版本1.0.8
在下拉到指定的动态时不正常加载，显示一片灰色

### 复现步骤
下拉到指定的动态

### 预期行为
正常显示，在电脑版中显示的动态如下
![image](https://github.com/guozhigq/pilipala/assets/144582985/4576fdd9-2620-4d97-92cd-47e40366be53)

### 系统信息
三星S10 安卓12

### 相关截图或日志
![Screenshot_20231015-104020](https://github.com/guozhigq/pilipala/assets/144582985/608b231b-9e40-41f2-8269-474c8d0e26d1)

**Comment by guozhigq** [comment]
了解
