### ISSUE TITLE
I want to add a follow-up item on the homepage, and then I want to customize the columns and themes on the homepage

### ISSUE THREAD

**Issue by 00000000002** [guozhigq/pilipala#202]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
😂 看不大懂怎么回事  现在是支持自定义列数跟主题的
