### ISSUE TITLE
希望能够增加后台播放通知栏显示

### ISSUE THREAD

**Issue by 00susu00** [guozhigq/pilipala#205]
请提供对所请求功能的清晰描述。
勾选后台播放之后回到主页 每次都必须要进到软件操作播放 不太方便 可以增加一个通知栏控件

**Comment by Daydreamer-riri** [comment]
我可以尝试认领这个feature

**Comment by guozhigq** [comment]
> 我可以尝试认领这个feature @guozhigq

好啊，雪中送炭 👏，有什么问题可以通过邮件或者tg沟通
