### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [guozhigq/pilipala#206]
### 功能描述
请问本项目代码开源吗？是否可以打包发布到 F-Droid? 谢谢

### 目标
添加许可证并发布到 F-Droid。

**Comment by Daydreamer-riri** [comment]
@guozhigq Hi，我也认为分发到F-droid会更方便的分发新版本。我可以跟进这件事。

**Comment by guozhigq** [comment]
> @guozhigq Hi，我也认为分发到F-droid会更方便的分发新版本。我可以跟进这件事。

好的

**Comment by linsui** [comment]
> 好的

@guozhigq 那请问可以加一个开源许可证吗？

**Comment by Daydreamer-riri** [comment]
我这边目前无法注册gitlab账号，可能没有办法推动这件事了😂

**Comment by txyyh** [comment]
可以考虑发布到izzy或者自建个（github就能实现）作为workaround

**Comment by linsui** [comment]
Izzy 也只接受开源应用

**Comment by Integral-Tech** [comment]
建议先加个许可证，个人最喜欢 GPL，用其他许可证也行

**Comment by linsui** [comment]
作者用 GPL-3.0 开源了 :tada:

**Comment by Integral-Tech** [comment]
> 作者用 GPL-3.0 开源了 🎉

我刚刚在 F-droid Gitlab 上发了一个打包请求：https://gitlab.com/fdroid/rfp/-/issues/2616

**Comment by Integral-Tech** [comment]
> 作者用 GPL-3.0 开源了 🎉

The pull request regarding adding fastlane: https://github.com/guozhigq/pilipala/pull/372

**Comment by linsui** [comment]
F-Droid 需要 version code 递增，比如[这里](https://github.com/guozhigq/pilipala/blob/da3b781f349f56de529a4bd013ead544833bf5f2/pubspec.yaml#L19)设置为 `1.0.15+1015` 然后每个版本更新 version code。目前用的是默认的 1。

**Comment by linsui** [comment]
大概一周内会进入 F-Droid。谢谢各位帮助。

**Comment by GalaxySnail** [comment]
请问 f-droid 上的版本是不是打包得有点问题？在我的 Android 10 上安装完成后没有启动按钮，桌面也没有 app 图标，就好像是一个插件 app 一样。

**Comment by linsui** [comment]
是的，用了一个有问题的 commit。

**Comment by Jimmisama** [comment]
能顺便把Pilipala X也放到F droid上吗

**Comment by linsui** [comment]
这个 https://github.com/orz12/pilipala/issues/34 ？那得看它作者的想法。

**Comment by orz12** [comment]
> 这个 [orz12#34](https://github.com/orz12/pilipala/issues/34) ？那得看它作者的想法。

我是都可以，但目前没有时间搞这个

**Comment by linsui** [comment]
@orz12 那麻烦更新一下 https://github.com/orz12/pilipala/tree/main/fastlane/metadata/android ，然后我来打包

**Comment by orz12** [comment]
> @orz12 那麻烦更新一下 https://github.com/orz12/pilipala/tree/main/fastlane/metadata/android ，然后我来打包

行 那明天我再改一下 辛苦了

**Comment by orz12** [comment]
@linsui 对了，有一个问题，我在pubspec.yaml里写的versionCode是固定值，都是在push到github上后通过action中的CI自动修改的，如果在F-Droid更新，是否还可以用这个机制？

**Comment by linsui** [comment]
从 1.0.23 开始就没有源代码更新了，这个是暂时的吗？

**Comment by guozhigq** [comment]
> 从 1.0.23 开始就没有源代码更新了，这个是暂时的吗？

推迟一版本开源

**Comment by linsui** [comment]
就是说 1.0.24 的代码会在 1.0.25 发布的时候开源吗？

**Comment by guozhigq** [comment]
> 就是说 1.0.24 的代码会在 1.0.25 发布的时候开源吗？

是

**Comment by linsui** [comment]
因为极验插件不开源，我将 F-Droid 的所有版本都删除了。我现在打了个 patch 去掉了极验，因为新的登陆页面还没使用所以目前没有任何影响。不知道下个版本怎么样。

**Comment by Smart-SangGe** [comment]
现在关于打包发布有什么进展吗？我看谷歌商城和fdroid都停留在1.0.22的版本。
