### ISSUE TITLE
播放速度选择框不支持返回手势

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#214]
打开播放速度选择框，做一次返回手势，只会退出视频，不会关闭这个对话框
（好像之前评论区保存图片的对话框也有过这样的问题，或许可以参考一下）
![Screenshot_20231023_003524_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/106989902/1c70348d-be66-4468-8723-7a6eaee6f6a3)

**Comment by guozhigq** [comment]
ok
