### ISSUE TITLE
更新最新版且登陆后，推荐页一直刷不到之前喜欢看的视频，且基本没有关注的动态出现，较1.0.8推荐页差很多

### ISSUE THREAD

**Issue by wo90414153** [guozhigq/pilipala#233]
更新最新版且登陆后，推荐页一直刷不到之前喜欢看的视频，且基本没有关注的动态出现，较1.0.8推荐页差很多
且刷新好几页都没出现自己喜欢看的，类似登陆推荐无效
安卓9 via浏览器

**Comment by wo90414153** [comment]
更新最新版且登陆后，推荐页一直刷不到之前喜欢看的视频，且基本没有关注的动态出现，较1.0.8推荐页差很多
且刷新好几页都没出现自己喜欢看的，类似登陆推荐无效

**Comment by guozhigq** [comment]
登录出问题了，正在修复

**Comment by TheLonelinessOfHS** [comment]
帮你破信息茧房还不好？手动狗头
