### ISSUE TITLE
动态无法点开

### ISSUE THREAD

**Issue by yiobai** [guozhigq/pilipala#235]
### 问题描述
在推荐页无法点开动态类的东西

### 复现步骤
无

### 预期行为
能尽快修复

### 系统信息
客户端1.0.10，系统miui14

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
最新版应该没这个问题了，先关闭了。再遇到的话可以再打开
