### ISSUE TITLE
功能反馈：播放视频双击暂停比较麻烦 

### ISSUE THREAD

**Issue by Anhai0501** [guozhigq/pilipala#239]
### 功能描述
在随机点开一条视频进行播放 想要暂停得双击视频界面中间才行 旁边的话就会误触 导致视频快进 这点体验不是很好 希望这方面能够优化一下![Screenshot_2023-11-12-14-25-06-19_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/guozhigq/pilipala/assets/99585202/56884577-6017-4c21-9aa8-de0f6d4cc02c)

**Comment by guozhigq** [comment]
双击快进/快退可以关闭

**Comment by Anhai0501** [comment]
> 双击快进/快退可以关闭

找到了

**Comment by Anhai0501** [comment]
> 双击快进/快退可以关闭

那个锁子 可以移调吗 没啥作用阿
