### ISSUE TITLE
网页登陆成功但转到软件失败，等于登陆不了

### ISSUE THREAD

**Issue by qa12587** [guozhigq/pilipala#24]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
是的，昨天也发现了这个问题。
 相关逻辑做了些修改，明天会更新一版 。🙏 感谢反馈

**Comment by qa12587** [comment]
> 

最新的一版也和上个版本一样可以登陆但转不到软件

**Comment by guozhigq** [comment]
方便进tg沟通吗 在「关于」页面有频道链接
