### ISSUE TITLE
全屏在六分钟之后不显示任何弹幕，恢复到竖屏就会全部显示

### ISSUE THREAD

**Issue by SakiTomato822** [guozhigq/pilipala#245]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
SM-G9980，Android 13，PiliPala版本 1.0.12。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by SakiTomato822** [comment]
复现链接为https://1drv.ms/v/s!AgLevaZbsPUshbM33rnPxo2SiIidBw

**Comment by TheLonelinessOfHS** [comment]
目前问题在最新版中仍然没有解决
