### ISSUE TITLE
首页推荐内容与账号无关

### ISSUE THREAD

**Issue by lhw20000226** [guozhigq/pilipala#246]
开发者您好，请问下用pilipala刷不到喜欢的视频是怎么回事呢，账号也登陆了，退出重新登录也试过，就是刷不到平常爱看的那些，下面是一些对比图，麻烦您看一下，谢谢！
![Screenshot_2023-11-15-10-23-02-274_tv danmaku bili](https://github.com/guozhigq/pilipala/assets/114221911/a724be21-3cd3-499f-aad4-40f918d1e046)
![Screenshot_2023-11-15-10-22-47-183_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/114221911/11709334-265f-41fe-b283-91e9035a2031)

**Comment by huajiworld** [comment]
加一

**Comment by Anhai0501** [comment]
同上

**Comment by guozhigq** [comment]
关联issues #233
