### ISSUE TITLE
/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:976:36: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.

### ISSUE THREAD

**Issue by AdamZay** [guozhigq/pilipala#247]
/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/extended_image.dart:976:36: Error: The argument type
'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and
'BorderRadiusGeometry' isn't.

**Comment by AdamZay** [comment]
项目拉下来， pub get 后运行直接报这个错误

**Comment by AdamZay** [comment]
/.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13: Error: 'ImageTilingInfo' isn't a
type.

**Comment by AdamZay** [comment]
iPhone 真机和模拟器都试过了，报同样的错误

**Comment by AdamZay** [comment]
extended_image 应该是这个 lib 的版本问题，但我不知道替换为哪个版本

**Comment by guozhigq** [comment]
可能是flutter版本导致的，退到3.10.6试下
