### ISSUE TITLE
默认全屏方式自适应未能成功自适应

### ISSUE THREAD

**Issue by antitail** [guozhigq/pilipala#251]
### 问题描述
将默认全屏方式设置为自适应后，即使手机为竖屏模式，依旧会强制切换为横屏，切换为始终竖屏后，则正常竖屏播放

### 复现步骤
将默认全屏方式设置为自适应

### 预期行为
根据屏幕所使用方向默认进入竖屏全屏模式或横屏全屏模式，旋转手机后根据传感器自动切换至另一模式

### 系统信息
MIUI Fold 14.0.12/展开模式
客户端版本号1.0.12

**Comment by guozhigq** [comment]
设置里的【默认全屏方向 - 自适应】 指的是根据视频画面比例，当视频全屏播放时，是横屏还是竖屏。这里可能缺少了详细的解释

**Comment by orz12** [comment]
> 设置里的【默认全屏方向 - 自适应】 指的是根据视频画面比例，当视频全屏播放时，是横屏还是竖屏。这里可能缺少了详细的解释

#463 （改动了描述）
