### ISSUE TITLE
希望可以在详情页加一个进入全屏的按钮

### ISSUE THREAD

**Issue by yelong0951** [guozhigq/pilipala#255]
希望可以在详情页加一个进入全屏的按钮

在播放器中进入全屏要点一下呼出，再按全屏按键
很多时候点快了会暂停，不方便
希望可以在详情页加一个进入全屏的按钮，或是作个快捷手势之类的实现

**Comment by yelong0951** [comment]
能不能双击全屏，单击暂停。
可以的话，加个这样的设置挺好

**Comment by guozhigq** [comment]
播放页面上滑可以进入全屏
