### ISSUE TITLE
[BUG]切换分集时下方推荐与评论区不会刷新

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#269]
### 复现步骤
1. 打开一个带有合集的视频
2. 切换分集

### 预期行为
显示新视频的推荐与评论。
### 系统信息
Android 5.1 .1 ColorOS v2.1

**Comment by VillagerTom** [comment]
概率发生，条件未知。

**Comment by VillagerTom** [comment]
BV14j411p7Jb 稳定触发。

**Comment by guozhigq** [comment]
> BV14j411p7Jb 稳定触发。

试了一下评论区刷新了，目前还没做推荐视频刷新的功能

**Comment by VillagerTom** [comment]
@guozhigq 多切换几次试试

**Comment by VillagerTom** [comment]
看来跟哪个视频没有关系。

**Comment by VillagerTom** [comment]
https://b23.tv/BV1Kw411E7bZ 这个合集查看比较方便，up主会在每个视频置顶评论贴出网盘链接，如果评论与视频发布日期不一致就是加载错了。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
