### ISSUE TITLE
推荐页网络异常刷新功能异常

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#270]
### 问题描述
网络异常时在首页点击[点击重试]键，内容**一闪而过**，只剩下“加载更多👇”字样，点击无响应。

### 复现步骤
1. 关闭网络打开APP；
2. 打开网络；
3. 点击[点击重试]键。

### 预期行为
正确显示刷新后的内容。

### 系统信息
OS: Android 7.1.2, Funtouch OS 3.1
Webview: Google v119.0.6045.163

### 相关截图或日志
https://github.com/guozhigq/pilipala/assets/89803422/63ce5a0d-520d-4a9c-9479-d0d905c0780b

**Comment by VillagerTom** [comment]
最新版本问题依旧。

**Comment by guozhigq** [comment]
> 最新版本问题依旧。

网络异常是因为没有开流量或者连wifi ?

**Comment by VillagerTom** [comment]
我想我描述的很清楚。在关闭网络时打开app, 然后打开网络，再点击“点击重试”键。最新版表现仍与原视频相同。必须重启app才能正常刷新出内容。

**Comment by VillagerTom** [comment]
补充：下拉刷新也加载不出内容。
