### ISSUE TITLE
【功能请求】弹幕发送功能

### ISSUE THREAD

**Issue by KoolShow** [guozhigq/pilipala#273]
### 功能描述
在视频播放器内添加文本栏或编辑按钮以发送弹幕。
在编写时暂停视频播放

### 目标
能够发送普通弹幕，甚至高级弹幕

### 解决方案
https://socialsisteryi.github.io/bilibili-API-collect/docs/danmaku/action.html#发送视频弹幕

### 其他
无

**Comment by orz12** [comment]
#279 已添加

**Comment by KoolShow** [comment]
看错了没合并
