### ISSUE TITLE
功能建议| 允许“关闭首页”

### ISSUE THREAD

**Issue by JOYCELEEEEE** [guozhigq/pilipala#280]
首先，非常感谢大佬能做出这款简洁轻量的app🌞

如题，个人使用b站主要是为了查看自己关注的up是否更新，无奈本人自控力也很差，经常会被首页内容吸引，然后一发不可收拾...

于此，请问大佬能否考虑增加“关闭首页”的开关？期待回复🥳

**Comment by guozhigq** [comment]
可以

**Comment by Ansshaoh** [comment]
我也只看关注内容，主页给我的视频质量太低了，希望大佬能够添加关闭首页的功能😊 十分期待🫠🫠

**Comment by Sciroccogti** [comment]
似乎已经在 https://github.com/guozhigq/pilipala/releases/tag/v1.0.17.0125 中实现
