### ISSUE TITLE
[BUG]评论条目重复

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#284]
评论区或楼中楼有概率将所有评论显示两次，刷新后恢复。

**Comment by VillagerTom** [comment]
关注列表也偶有人员重复，但并非重复全部。

**Comment by VillagerTom** [comment]
找到一个比较稳定的复现方式：
点开楼中楼，在评论内容加载出来之前快速划到底部。

**Comment by VillagerTom** [comment]
群内反馈视频分集也有条目重复。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。

**Comment by VillagerTom** [comment]
似乎没有解决。你都没有commit提及这个issue😂

**Comment by guozhigq** [comment]
> 评论区或楼中楼有概率将所有评论显示两次，刷新后恢复。

这个还有吗

**Comment by VillagerTom** [comment]
我记得这段时间使用pilipalax仍然出现过评论重复的情况。@orz12 应该没有改动评论请求相关代码。

**Comment by VillagerTom** [comment]
> 找到一个比较稳定的复现方式： 点开楼中楼，在评论内容加载出来之前快速划到底部。

您认为这个复现方式能否证明问题？

**Comment by VillagerTom** [comment]
出现了。

https://github.com/guozhigq/pilipala/assets/89803422/49ce42fa-b88d-4cdb-9627-39cb78e9cef4
