### ISSUE TITLE
小米13Pro Android13 MIUI14，播放无声音，无通知和状态栏控件

### ISSUE THREAD

**Issue by asuszwbUbuntu** [guozhigq/pilipala#29]
### 问题描述
播放视频时没有音频，系统支持独立为每一个APP设置音频音量，即便如此，调整音量时也不见该APP的音量条，且视频没有音频输出

问题2
在Android13中，APP未申请通知权限，系统通知设置中无法独立给予APP通知权限，故导致APP通知失效，状态栏播放控件失效，不存在

### 复现步骤
播放任意视频即可，下拉系统通知栏即可

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
Android13 MIUI14 Xiaomi13Pro，（以为APP授予全部权限）

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
下载的是arm63-v8a那个版本吗？
或许可以尝试切换音质/解码格式试试

</br>

> 调整音量时也不见该APP的音量条
感觉这个应该跟是否有声音没关系

</br>
现在确实没有申请通知栏权限，而且状态栏播放控件这个功能目前还没有开发，所以属于正常情况。等待后续更新吧
