### ISSUE TITLE
动态评论区显示请求错误

### ISSUE THREAD

**Issue by AIsouler** [guozhigq/pilipala#292]
### 问题描述
点击跳转到某up转发的其他人的动态，评论区显示请求错误

### 预期行为
评论区正常显示

### 系统信息
小米10Pro，MIUI14
![Screenshot_2023-12-17-19-44-03-560_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/57941037/1c429127-b306-4278-af93-8750a0174f23)
![Screenshot_2023-12-17-19-43-53-898_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/57941037/4b8fa2b3-7fa5-4d1c-bb60-0ceeb7ef7d90)

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by AIsouler** [comment]
稳定复现
![Screenshot_2023-12-17-19-55-04-453_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/57941037/f6a0e133-c2ff-451d-a1f8-6beb76a133cb)
![Screenshot_2023-12-17-19-55-08-406_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/57941037/851f3a44-10ee-426b-a8e1-dbcc94845ac8)

**Comment by guozhigq** [comment]
关联 #147
