### ISSUE TITLE
很小但很令人难受的界面bug-评论区复制文字按钮

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [guozhigq/pilipala#297]
### 问题描述
视频评论区长按复制出现复制按钮后点击其他地方复制按钮不会消失-误触的时候会很难受

### 复现步骤
进入视频评论区->长按评论->出现复制按钮->点击其他区域->按钮不消失

### 预期行为
如果按复制按钮以外的区域复制按钮应该消失

### 系统信息
Xperia1 II — Android 11

### 相关截图或日志
N/A

**Comment by guozhigq** [comment]
v1.0.20 中已解修改评论复制逻辑，有问题可以再打开。
