### ISSUE TITLE
[BUG]评论区排序

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#298]
`最多回复`与`最热`的区别是什么？看起来两种排序是一样的。

**Comment by guozhigq** [comment]
好像是一样的，目前官方web端的评论只有【最热】【最新】两个分类了

**Comment by VillagerTom** [comment]
根据油猴脚本[Bilibili 旧播放页](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5)作者统计的【B站更新摘记】：

> - 2021 年 07 月 01 日：和谐翻页评论接口，上古按“评论数”排序评论彻底失效。

**Comment by guozhigq** [comment]
之后将取消【最多回复】 这个排序
