### ISSUE TITLE
[BUG]PiP播放切换全屏有问题

### ISSUE THREAD

**Issue by EventHorizonV** [guozhigq/pilipala#305]
### 问题描述
开启PIP画中画模式后，点击全屏按钮会闪烁一次全屏随后退回到桌面进入PIP模式，点击退出全屏按钮同样会退回桌面进入PiP模式。

### 复现步骤
开启PIP模式开关后点击横版视频的全屏按钮和取消全屏按钮。

### 预期行为
希望得到修复。

**Comment by EventHorizonV** [comment]
版本是v1.0.13.1217

**Comment by guozhigq** [comment]
最新版应该没这个问题了吧
