### ISSUE TITLE
［BUG］点击关注up后下方的提示不会消失

### ISSUE THREAD

**Issue by AIsouler** [guozhigq/pilipala#312]
![Screenshot_2023-12-19-01-03-02-658_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/57941037/1aef1251-2232-429e-83a2-b122c64902ae)

**Comment by guozhigq** [comment]
应该是因为手机开启了「无障碍」

**Comment by guozhigq** [comment]
增加了一个关闭按钮
