### ISSUE TITLE
感觉首页推荐默认没有打开个性化推荐，推送的视频相关程度远不如哔哩哔哩客户端，希望能改善。

### ISSUE THREAD

**Issue by JonhYi** [guozhigq/pilipala#313]
### 问题描述
首页推荐缺失个性化推荐算法，推荐视频与个人偏好相关度远低于哔哩哔哩客户端推荐视频，连关注的up主都很少推送，类似于默认没有开启个性化推荐，而首页热门则有个性化算法接介入痕迹。

### 复现步骤
打开pilipala并刷新视频。

### 预期行为
提高推荐视频个性化推荐算法介入或者增加是否开启个性化推荐的开关。

### 系统信息
Android 12

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
版本号？清除数据重新登录试试

**Comment by JonhYi** [comment]
> 版本号？清除数据重新登录试试

OK，解决了🥰🥰
