### ISSUE TITLE
视频合集，向下滑动 ui 显示问题

### ISSUE THREAD

**Issue by DrinkingHook** [guozhigq/pilipala#314]
### 问题描述
请提供一个清晰而简明的问题描述。
测试了一下，好像只有合集数量少的时候才会出现抽搐。
### 复现步骤
点开合集，向下小幅度滑动

### 预期行为
感觉有点抽搐，预期就是这样设计的吗

### 系统信息
安卓13 app版本1.0.13

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。https://github.com/guozhigq/pilipala/assets/113015731/b636246a-2c6f-43d4-9a77-0603a46b9354

**Comment by guozhigq** [comment]
新增的一个功能导致的bug
