### ISSUE TITLE
播放多p视频时换p弹幕和评论不刷新

### ISSUE THREAD

**Issue by TooyoungLi** [guozhigq/pilipala#326]
播放多p视频时换p弹幕和评论不刷新

**Comment by VillagerTom** [comment]
分p还是分集？分p的话评论区都是同一个，分集的话我反馈过类似问题 #269

**Comment by TooyoungLi** [comment]
分P弹幕不会刷新，分集评论和弹幕都不会



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月21日(周四) 下午2:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guozhigq/pilipala] 播放多p视频时换p弹幕和评论不刷新 (Issue #326)




 
分p还是分集？分p的话评论区都是同一个，分集的话我反馈过类似问题 #269

**Comment by guozhigq** [comment]
最新版本还有这个问题吗

**Comment by TooyoungLi** [comment]
已经解决了！谢谢
希望等缓存功能和其他区域视频解析功能上线，就可以完全替代原客户端了
&nbsp;


李毅林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月17日(星期天) 下午3:34
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guozhigq/pilipala] 播放多p视频时换p弹幕和评论不刷新 (Issue #326)





 
最新版本还有这个问题吗
