### ISSUE TITLE
[Bug]个人动态展示不匹配

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#328]
### 问题描述
从一个人的主页转到另一个人的主页，动态展示不正确。

### 复现步骤
1. 打开A的主页并打开Ta的动态；
2. 点击转发或`@`来到B的主页；
3. 打开Ta的动态

### 预期行为
展示B的动态。

**Comment by VillagerTom** [comment]
是否与#292有关？

**Comment by VillagerTom** [comment]
从所有动态（[动态]选项卡）点击转发或`@`则不会有这个问题。

**Comment by guozhigq** [comment]
> 是否与#292 有关？

无关
