### ISSUE TITLE
[Bug]关注按钮问题

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#332]
1. 个人主页的关注按钮在我的两部手机（Android 5.1 和 Android 7.1.2）上都是灰色的且没有文字，无论是否关注。在Android 5.1上点击关注/取关按钮后，显示一层灰色蒙版，之后UI不可操作（除了返回键）。
![Screenshot_2023-12-22-02-34-22-89](https://github.com/guozhigq/pilipala/assets/89803422/a9f34ed1-e397-41f8-a5c7-87db55b629fd)
![Screenshot_2023-12-22-02-39-54-89](https://github.com/guozhigq/pilipala/assets/89803422/734291e0-8175-4143-a20a-082d345c9b64)

2. 在视频播放页点击关注按钮会弹出设置分组，在主页关注则不会。

**Comment by VillagerTom** [comment]
另外建议跟随官方B站的操作逻辑，点击`已关注`后弹出选项，以避免想要更换分组时，还要取关重新操作。

**Comment by orz12** [comment]
#336 换了接口现在能显示出来了，至于灰色页没有复现；更换分组有点复杂，暂时没有实现
