### ISSUE TITLE
播放推荐视频出现的性能问题

### ISSUE THREAD

**Issue by Cmwoan** [guozhigq/pilipala#337]
### 问题描述
在开启弹幕的情况下，从视频页下方推荐中进入新的视频，多次重复上述操作后页面变卡顿。
在 videoPositionListen 处打印 log 发现在新视频播放时似乎仍有旧视频的弹幕触发 addItems。

**Comment by orz12** [comment]
#338 试试这样还会不会？

**Comment by Cmwoan** [comment]
好像还在，返回到上一级视频后会累积许多弹幕

**Comment by VillagerTom** [comment]
#361

**Comment by orz12** [comment]
#443

**Comment by guozhigq** [comment]
v1.0.20 中应该没这个问题了，可以观察一下。
