### ISSUE TITLE
[Bug]评论区关键词

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#339]
### 问题描述
一个关键词在同一评论中高亮多次。

### 复现步骤
https://b23.tv/BV1UN4y1272X

### 预期行为
1. 关键词仅高亮一次;
2. 尽量避免打断单词或网址（如果可能）。

（BiliYou把各种链接显示在评论文本下方的方案就很不错）

### 相关截图或日志
![Screenshot_2023-12-25-16-24-02-30](https://github.com/guozhigq/pilipala/assets/89803422/66d3738e-09ad-4bb8-8a3f-5ba41a09f540)

**Comment by guozhigq** [comment]
暂时无法实现
