### ISSUE TITLE
视频底部添加小进度条

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#341]
如图位置：
![Screenshot_20231226_002958](https://github.com/guozhigq/pilipala/assets/106989902/c9d62846-dc0d-4e7c-b1b7-d5704a94c90b)
之前版本是有的，新版本去掉了，希望可以添加回来或是加一个开关。

**Comment by orz12** [comment]
其实没有去掉 只是尺寸有差别 所以需要再往上挪一点才能显示出来
