### ISSUE TITLE
[Bug]评论区`@`问题

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#344]
### 问题描述
一条评论有多个`@`时，末尾多出一个没有高亮的`@`。

### 相关截图或日志
![IMG_20231226_125021](https://github.com/guozhigq/pilipala/assets/89803422/14c8006d-b903-4190-8b33-31dd38200dba)

**Comment by orz12** [comment]
有链接吗

**Comment by VillagerTom** [comment]
`BV1H64y1L7Z6`

**Comment by VillagerTom** [comment]
这条评论下面还有很多`@`没有高亮的回复。

**Comment by VillagerTom** [comment]
评论内容只有一个`@xxx`时，不会高亮。

**Comment by VillagerTom** [comment]
`BV1st4y1f7bJ`下有3个。
