### ISSUE TITLE
打开楼中楼评论时开启全屏的问题

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#347]
https://github.com/guozhigq/pilipala/assets/106989902/aa90a5be-9c6d-4d72-9f2a-1aa57469be5e

**Comment by VillagerTom** [comment]
省流：打开某一评论详情时点击视频全屏，会导致评论全屏显示。

**Comment by wanzh5** [comment]
补充：打开视频简介的时候也有同样情况

**Comment by guozhigq** [comment]
最新版已解决
