### ISSUE TITLE
硬解导致死机

### ISSUE THREAD

**Issue by puresox** [guozhigq/pilipala#354]
### 问题描述
当打开硬解，对于任意编码格式，默认画质选择8k画质看视频会直接死机，必须重启手机。关闭硬解后正常，默认画质选择1080p也正常。

### 复现步骤
打开硬解，默认画质选择8k画质，随便点开一个视频，即使这个视频最高画质只有1080p，然后就死机了。

### 预期行为
希望不要死机。

### 系统信息
手机红米k60pro，处理器8gen2，app版本1.0.14

### 相关截图或日志
无

**Comment by long1512448773** [comment]
用软解吧哥们，硬解是老电视，打过电视才用的😂😂

**Comment by puresox** [comment]
从miui14更新到澎湃os之后没问题了

**Comment by yhx0022** [comment]
> 用软解吧哥们，硬解是老电视，打过电视才用的😂😂

硬解跟软解，哪个性能表现更好同时又功耗更低呢？
以前一直听说是硬解会好一点。。。

**Comment by XPRAMT** [comment]
> > 用软解吧哥们，硬解是老电视，打过电视才用的😂😂
> 
> 硬解跟软解，哪个性能表现更好同时又功耗更低呢？ 以前一直听说是硬解会好一点。。。

硬解各方面都屌打軟解，除了部分奇怪格式無法解碼
