### ISSUE TITLE
[Bug]弹幕积压

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#361]
### 问题描述
疑似在播放第二个视频时，第一个视频的同一时间处的弹幕仍在后台渲染。

### 复现步骤
1. 打开第一个视频~~并把进度条拉到最后~~；
2. 从推荐播放第二个视频：
  a. 播放一段时间后返回第一个视频；
  b. 播放几秒后立即返回。

对比 2.a 与 2.b 发现前者比后者弹幕积压更多。
第一个视频弹幕数量过多时，会导致第二个视频播放卡顿。

**Comment by VillagerTom** [comment]
我认为这个问题包含两个Bug:
1. 未播放的视频加载了弹幕；
2. 后台加载的弹幕因为没有前进动画而在原处积压。

**Comment by VillagerTom** [comment]
最新测试版（在#408 之后）在Android 7.1.1以下以及Linux上仍存在此问题。

**Comment by VillagerTom** [comment]
我太菜了不会调试😢，请有条件的开发者帮忙看一下🙏

**Comment by VillagerTom** [comment]
@Cmwoan 这个问题在你的设备上是否仍然存在？

**Comment by Cmwoan** [comment]
是的，还在。路由中存在多个视频页时，pl_player的_positionListener中存在多个回调，我现在简单地让它只触发列表中最后一个回调来解决问题。但应该有更好的方法，在离开页面时移除回调

**Comment by orz12** [comment]
#443

**Comment by VillagerTom** [comment]
后台播放返回前台仍有积压。（没有开启pip）

**Comment by VillagerTom** [comment]
跳转到任意个人主页再播放任意视频，返回原视频仍有弹幕积压。

**Comment by VillagerTom** [comment]
v1.0.20 从第二个视频返回后，第一个视频弹幕消失，需关闭重新打开弹幕开关才能重新显示。

**Comment by guozhigq** [comment]
v1.0.23版本已修复，可以试下
