### ISSUE TITLE
进度条难用

### ISSUE THREAD

**Issue by naniccc** [guozhigq/pilipala#362]
①拖拉几次进度条，还没点到想要的位置，自己就缩回去了，应该是逻辑有问题（好像是误认为没有操作，自己就缩回去了）
②进度条触控区域太细了，经常误触进度条旁边区域，横屏更容易误触。建议加宽，或者那个锚点大一点

**Comment by orz12** [comment]
#343改了问题2
问题1没有发现

**Comment by naniccc** [comment]
> #343 改了问题2 问题1没有发现

问题1我真的100%触发，可能我没说清楚，录了一小段，就是进度条还没选好位置，自动缩回去了
https://github.com/guozhigq/pilipala/assets/57870281/8d3802ef-bdc7-4e5c-bed2-dcf35645a966

**Comment by guozhigq** [comment]
现在底部的控制条是自动收起的，你的意思是希望调整进度的时候不收起？

**Comment by orz12** [comment]
> 现在底部的控制条是自动收起的，你的意思是希望调整进度的时候不收起？

我现在调整进度过程中也不会收起呀~

**Comment by orz12** [comment]
哦我懂了 按住拖动就不会收起 如果习惯点按的话需要在点击后重置定时器的时间之类的？

**Comment by naniccc** [comment]
> 哦我懂了 按住拖动就不会收起 如果习惯点按的话需要在点击后重置定时器的时间之类的？

对的，是这个意思
