### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Fishheadrabbit** [guozhigq/pilipala#363]
### 问题描述
请提供一个清晰而简明的问题描述。
视频全屏时仍旧显示评论区

### 复现步骤
请提供复现该问题所需的具体步骤。
视频有

### 预期行为
请描述你期望的正确行为或结果。
修复这个bug

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
oppok9x Coloros13
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。 
https://github.com/guozhigq/pilipala/assets/105645188/7162f106-a6ea-4ba0-95a4-8df4fc7975a1

**Comment by Fishheadrabbit** [comment]
https://github.com/guozhigq/pilipala/assets/105645188/30804f6a-75d1-4264-aeab-f613a45cef70

**Comment by guozhigq** [comment]
最新版已修复
