### ISSUE TITLE
关于竖屏视频的bug

### ISSUE THREAD

**Issue by YueHen14** [guozhigq/pilipala#364]
### 问题描述
请提供一个清晰而简明的问题描述。
观看竖屏视频时无法全屏
### 复现步骤
请提供复现该问题所需的具体步骤。
观看任何竖屏视频都无法全屏
### 预期行为
请描述你期望的正确行为或结果。
能正常全屏
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
红米k50u，hyper系统，pilipala版本1.0.14
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by orz12** [comment]
#342
