### ISSUE TITLE
主屏幕有弹幕但全屏没弹幕

### ISSUE THREAD

**Issue by JackA1ltman** [guozhigq/pilipala#367]
### 问题描述
请提供一个清晰而简明的问题描述。
从播放到第二个长视频开始，会出现主屏幕有弹幕但全屏没弹幕，或反过来

### 复现步骤
请提供复现该问题所需的具体步骤。
自你看第二个长视频开始出现

### 预期行为
请描述你期望的正确行为或结果。
任何时候都显示弹幕

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android11，一加8，HOS11

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
https://wwmk.lanzouj.com/iXOpj1jcupwf

**Comment by guozhigq** [comment]
最新的1.0.17版本还有这个问题吗
