### ISSUE TITLE
直播全屏bug

### ISSUE THREAD

**Issue by Fishheadrabbit** [guozhigq/pilipala#368]
### 问题描述
请提供一个清晰而简明的问题描述。
直播全屏后返回主页仍然横屏

### 复现步骤
请提供复现该问题所需的具体步骤。
直播全屏后返回主页

### 预期行为
请描述你期望的正确行为或结果。
返回后为竖屏

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。Coloros13 k9x

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。https://github.com/guozhigq/pilipala/assets/105645188/73833de7-4dcc-4a08-a2f4-48d8f89ea72c

**Comment by orz12** [comment]
已经合进去了 不要重复提交issue
