### ISSUE TITLE
关闭自动播放点进视频会白屏

### ISSUE THREAD

**Issue by sangci** [guozhigq/pilipala#374]
### 问题描述
请提供一个清晰而简明的问题描述。
关闭自动播放点进视频会白屏，打开之后才能正常查看视频详情页

### 复现步骤
请提供复现该问题所需的具体步骤。
登录后开关设置自动播放

### 预期行为
请描述你期望的正确行为或结果。
修复bug

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
安卓13，v8a，1.0.15版本

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by orz12** [comment]
#376
