### ISSUE TITLE
关闭设置中自动播放后视频页面加载不出来

### ISSUE THREAD

**Issue by FTK001H** [guozhigq/pilipala#377]
### 问题描述
打开播放设置中自动播放能够正常播放视频，关闭后点开视频页面全是灰色。

### 复现步骤
关闭自动播放

### 系统信息
miui14 android13
pilipala 1.0.15

### 相关截图或日志
https://github.com/guozhigq/pilipala/assets/150403866/6d98d8f3-cf5c-4dcc-bfd1-dd254a6b9b83

**Comment by molanjingke** [comment]
同问，我也遇到了同样的问题，同样是点开视频一篇灰幕。小米12s-miui14-android 13，更新到1.0.15后出现的问题。

**Comment by orz12** [comment]
#374
