### ISSUE TITLE
评论区bug和视频bug

### ISSUE THREAD

**Issue by Fishheadrabbit** [guozhigq/pilipala#381]
### 问题描述
请提供一个清晰而简明的问题描述。
部分视频的评论区无法正常加载，部分视频无法正常加载（即使是关闭软件重新打开也加载不出来，只能加载出封面，触发概率太小，但使用官方客户端可以正常加载，）

### 复现步骤
请提供复现该问题所需的具体步骤。
这个有点看脸

### 预期行为
请描述你期望的正确行为或结果。
修复bug

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。oppo k9x color OS13

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。https://github.com/guozhigq/pilipala/assets/105645188/6e9bc4c4-e66d-46fa-b86c-fa98aac5232c

**Comment by Fishheadrabbit** [comment]
视频中展示出bug的视频https://www.bilibili.com/video/BV1Vg411i7uM

**Comment by guozhigq** [comment]
评论异常的问题修复了，视频无法加载没有复现

**Comment by Fishheadrabbit** [comment]
> 评论异常的问题修复了，视频无法加载没有复现
没法复现就没法复现把，等我再卡了这个bug再反馈

**Comment by Fishheadrabbit** [comment]
> 评论异常的问题修复了，视频无法加载没有复现

卡这个bug了
[]()https://www.bilibili.com/video/BV1he411z7ZC

**Comment by Fishheadrabbit** [comment]
> 评论异常的问题修复了，视频无法加载没有复现

@guozhigq

**Comment by Fishheadrabbit** [comment]
> > > 评论异常的问题修复了，视频无法加载没有复现
> > 
> > 卡这个bug了，这个视频无法加载 https://www.bilibili.com/video/BV1he411z7ZC https://github.com/guozhigq/pilipala/assets/105645188/2a6832b5-8386-4813-a234-ac3cd9a41f85
> 
> 漏了回了，没有复现。
> 你在浏览器里打开这个链接看看返回什么内容  [获取视频Api](https://api.bilibili.com/x/player/wbi/playurl?cid=1391047230&qn=80&fnval=4048&bvid=BV1he411z7ZC&fourk=1&voice_balance=1&gaia_source=pre-load&web_location=1550101&wts=1706360207&w_rid=1d0d9bccb2327005506b9d2252ea9860)

![Screenshot_2024-01-27-21-02-23-89.jpg](https://github.com/guozhigq/pilipala/assets/105645188/e2608f79-cc60-49f0-9891-4df1d3239868)

**Comment by Fishheadrabbit** [comment]
把CDN优化打开就好了
