### ISSUE TITLE
播放量还是精确到万吧，看的眼花

### ISSUE THREAD

**Issue by fxxf1111** [guozhigq/pilipala#382]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by VillagerTom** [comment]
我认为可以用逗号隔开
