### ISSUE TITLE
[Bug] 评论被吞掉部分内容

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#385]
### 问题描述
评论区有些链接被吞掉`https:`

**Comment by VillagerTom** [comment]
![BV1oz4y1A7VF](https://github.com/guozhigq/pilipala/assets/89803422/8d1f78ae-3bdb-4086-b468-98f05c790706)
![BV17a4y1d7oF](https://github.com/guozhigq/pilipala/assets/89803422/d775b573-962d-42f2-b85e-a73ca5ace5a4)
![BV1jP4y1b7fk](https://github.com/guozhigq/pilipala/assets/89803422/3199d9cd-16a1-4eb3-9579-c39d30046852)
![BV1iK411t7ZM](https://github.com/guozhigq/pilipala/assets/89803422/41b0c9fc-c201-4d25-b1a6-a4aa0ac8a6ee)

**Comment by VillagerTom** [comment]
还有一个问题，评论区一些HTML字符实体没有转义。

**Comment by VillagerTom** [comment]
第三个变成了这样：
![Screenshot_2024-01-09-07-53-47-61](https://github.com/guozhigq/pilipala/assets/89803422/6a0093ae-5ed4-4130-ba46-5aa317123ded)

**Comment by guozhigq** [comment]
> 第三例变成了这样： ![Screenshot_2024-01-09-07-53-47-61](https://private-user-images.githubusercontent.com/89803422/295064181-6a0093ae-5ed4-4130-ba46-5aa317123ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjAxODQsIm5iZiI6MTcwNDc1OTg4NCwicGF0aCI6Ii84OTgwMzQyMi8yOTUwNjQxODEtNmEwMDkzYWUtNWVkNC00MTMwLWJhNDYtNWFhMzE3MTIzZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAwMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNmU2YjU3MDNiZmU2OTg5YTk4MThjZmZjZmUyZDNkYTYwYTMxZmI4MDkwYWNlMGJiNWJhMzkyZGM1NzFiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x0XkGjI08WybW35V2g555QthNzq4Zl-TJqA6JXBSRoI) 第一条整条消息空白。第二条因为被@用户改名而没有高亮；官方B站的表现为高亮原用户名。

哪个视频

**Comment by VillagerTom** [comment]
BV号在图片名称上。

**Comment by guozhigq** [comment]
因为用的web端评论接口，所以具体表现参考网页端。在网页端 **被@用户改名也没有高亮**  目前接口返回的数据不支持。
空白的问题我看下

**Comment by VillagerTom** [comment]
旧版为什么解析出了新用户名？

**Comment by VillagerTom** [comment]
#470

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
