### ISSUE TITLE
看视频有声音画面黑屏

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#39]
### 问题描述
请提供一个清晰而简明的问题描述。
看视频有声音没画面
### 复现步骤
请提供复现该问题所需的具体步骤。
我看up主籽岷的ATM9火山那个视频，有声音没画面，拖动进度条也一样，画面直接黑的
### 预期行为
请描述你期望的正确行为或结果。
有声音有画面
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android13，最新版，webview是116.0.5845.92
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
为了解决「同一个视频单例导致的画面停留」问题而产生的问题 😫，
复现步骤应该是：在A视频全部缓存结束切换至视频B，再返回A时黑屏

v1.0.6 中应该会**更改解决方案** 或者 **取消当前方案**

**Comment by do02fw** [comment]
还有我看有的视频到最后几分钟就没声音了，但是有画面

**Comment by do02fw** [comment]
还有动态图文那种，老是让下载哔哩哔哩客户端

**Comment by guozhigq** [comment]
> 还有动态图文那种，老是让下载哔哩哔哩客户端

从首页推荐打开还是从动态专栏打开呢，这两种目前都是用的webview浏览器跳转，之后会换成直接渲染Html内容，不过优先级不高
