### ISSUE TITLE
只有当 `自动播放` 开启后，`自动全屏`+`自动退出` 后者才有效（才会播放完毕后退出全屏）

### ISSUE THREAD

**Issue by XIU2** [guozhigq/pilipala#394]
### 问题描述
只有当 `自动播放` 开启后，`自动全屏`+`自动退出` 后者才有效（才会播放完毕后退出全屏）
`自动退出` 功能逻辑是专门这样设计的吗？还是说这是一个小 BUG？

因为我平时一般是看到感兴趣的视频封面/标题后，点击去会先看一下简介/评论什么的，然后再决定是否要观看，点击播放按钮后就会自动全屏播放，但播放完毕后不会自动退出全屏，研究了下发现只有开启 `自动播放` 后才行，于是就跑来问问~

### 复现步骤
- 在设置 - 播放设置 - 开启 `自动播放` + `自动全屏` + `自动退出`
点进去任何视频，会 自动全屏 并且**播放完毕后也会 自动退出 全屏**。
- 在设置 - 播放设置 - 开启 `自动全屏` + `自动退出`，关闭 `自动播放`
点进去任何视频，手动点击播放会 自动全屏 但**播放完毕后不会 自动退出 全屏**。

### 预期行为
开启 `自动全屏` + `自动退出`，但关闭 `自动播放` 的情况下，全屏播放完视频后自动退出全屏。

### 系统信息
Android 13

### 相关截图或日志
没有

**Comment by orz12** [comment]
应该是bug
