### ISSUE TITLE
增加倒放功能

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#40]
### 功能描述
请提供对所请求功能的清晰描述。
比如有些视频说了阿米诺斯之类的，鬼畜区比较多，如果可以倒放就好了
### 目标
请描述你希望通过这个功能实现的目标。
开启后后面播放的视频将是倒放的
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
没有，就随便问问，毕竟这个功能不是很重要
### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
视频倒放需要把视频所有的帧放入到内存中，然后进行倒序编码，对内存压力大，而且需要将视频全部缓存结束后才可以倒放。

目前(我)应该实现不了，当前使用的播放器应该也不支持该功能。

**Comment by do02fw** [comment]
有没有办法让评论的时候IP地区随机或者指定，或者未知

**Comment by guozhigq** [comment]
> 有没有办法让评论的时候IP地区随机或者指定，或者未知

评论显示用户IP的机制是通过获取用户发起请求时所使用的网络连接的IP地址来实现的。当用户在浏览器或应用程序中发起请求访问某个网页或服务器时，服务器会记录下该请求的IP地址，并将其与评论内容一起存储在数据库或日志文件中。

 以上是粘贴自chatgpt的回复，这个应该需要通过网络代理实现。
