### ISSUE TITLE
[功能请求] 全局新样式

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#402]
### 功能描述
新的主页样式非常漂亮，可以在其他地方也运用这种样式吗？

### 目标
请描述你希望通过这个功能实现的目标。
![IMG_20240108_210526](https://github.com/guozhigq/pilipala/assets/89803422/38ffc610-1e2b-43d1-8e73-59a425f523c0)
![IMG_20240108_205315](https://github.com/guozhigq/pilipala/assets/89803422/1e0a64b0-3fae-4348-bf84-b8739cd4ebca)
![IMG_20240108_205104](https://github.com/guozhigq/pilipala/assets/89803422/44d1cd82-83da-4830-a168-1feab414bbba)

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

**Comment by guozhigq** [comment]
应该不会
