### ISSUE TITLE
【功能建议】首页-直播（功能增加）

### ISSUE THREAD

**Issue by Tartarus2014** [guozhigq/pilipala#409]
直播那里 能加个关注的主播么？
目前只有全部主播，没有很好的显示自己关注的

**Comment by orz12** [comment]
备注下：
接口可以采用
https://api.live.bilibili.com/xlive/app-interface/v1/relation/liveAnchor?need_recommend=0
方法：GET
需携带cookie（app端用access_key和appkey应该也行，不过结果差不多）
返回值：json

**Comment by guozhigq** [comment]
已支持
