### ISSUE TITLE
[Bug] 重播读取了错误的视频

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#411]
### 问题描述
见下。

### 复现步骤
1. 将一个视频播放完成；
2. 点击一个推荐视频并立即返回（在小电视动画出现之前）；
3. 点击播放；
4. 播放器播放了第二个视频。

**Comment by VillagerTom** [comment]
https://github.com/guozhigq/pilipala/assets/89803422/36f9f19f-e32b-456f-9706-b6816fc326c4

**Comment by guozhigq** [comment]
😂 还真不好解决

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
