### ISSUE TITLE
希望能增加扫码功能

### ISSUE THREAD

**Issue by 00susu00** [guozhigq/pilipala#412]
### 功能描述
个人页希望增加扫码功能 有些pc端软件只支持扫码登录

### 解决方案
调用扫码的app接口

### 其他
开发者大大很酷 这个软件用了已经回不去官版了 但是扫码是刚需 希望开发者大大有空可以实现一下

**Comment by guozhigq** [comment]
这个应该实现不了。如果有遇到其他第三方实现了的，可以说一下，我去参考参考
