### ISSUE TITLE
建议增加隐藏直播Tab的开关

### ISSUE THREAD

**Issue by alone-wolf** [guozhigq/pilipala#413]
### 功能描述
希望能在设置中增加一个隐藏主页-直播的开关

### 目标
应该会存在一些不看直播的用户吧，我应该不是一个人？希望能够通过隐藏直播Tab，减少资源占用、节约一些流量，顺便获得更简洁的界面。

### 解决方案
理论上增加几个 if 即可？我没怎么写过 Flutter ，说得不对就是我在瞎说。

### 其他
感谢项目的贡献者开发如此好用的App！！！！！！

**Comment by orz12** [comment]
不切到直播tab不会有流量
