### ISSUE TITLE
评论复制有bug

### ISSUE THREAD

**Issue by Fishheadrabbit** [guozhigq/pilipala#420]
### 问题描述
请提供一个清晰而简明的问题描述。
复制后文字的位置乱了
### 复现步骤
请提供复现该问题所需的具体步骤。
复制有表情符号的评论

### 预期行为
请描述你期望的正确行为或结果。
修复该bug

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。pilipala:1.0.16
Oppo k9x
Color os14

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。https://github.com/guozhigq/pilipala/assets/105645188/1f68f0eb-2b09-4a0d-aa16-874baee2f51d

**Comment by guozhigq** [comment]
这是哪个视频呢

**Comment by Fishheadrabbit** [comment]
> 这是哪个视频呢

BV1SW4y1c7Bt

**Comment by guozhigq** [comment]
v1.0.20 中已修改评论复制逻辑，有问题可以再打开。
