### ISSUE TITLE
关于静默时执行自动化任务的建议

### ISSUE THREAD

**Issue by P1imo** [guozhigq/pilipala#426]
### 功能描述
自动完成B站任务，也就是「养号」😁

### 目标
实现背景启动时，自动观看、分享一个视频，B币券领取，各种签到，乃至风纪委投票，和直播相关任务。

### 解决方案
以下两个项目或许可以给您提供帮助：
https://github.com/MaxSecurity/BiliExper
https://github.com/dd178/BILI_judgement

### 其他
一个可能的例子是「贴吧Lite」，她在保持自启动的前提下，可以实现每日定时自动打卡。

由于本人并不了解安卓开发，表述不当敬请谅解🙇🏻‍♂️！非常感谢您的无私奉献❤️，永远铭记您🙏

**Comment by VillagerTom** [comment]
自动任务这种我认为还是找个脚本自己玩玩比较好，在APP里实现这种功能容易招绿尸函😂

**Comment by orz12** [comment]
为防止灰产泛滥，并不会考虑支持这种功能

**Comment by VillagerTom** [comment]
对哦，自动化任务如果太方便了会导致滥用，所以才会引发争议。是我格局小了😂
