### ISSUE TITLE
[Bug] 颜文字导致评论字体变成了日文圆体（丸ゴシック体）

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#427]
好像仅限Android 5?

### 复现步骤
https://b23.tv/BV1LK4y1z7tv

### 系统信息
OS: Android 5.1.1

**Comment by VillagerTom** [comment]
![BV1LK4y1z7tv](https://github.com/guozhigq/pilipala/assets/89803422/2bd9640d-5e51-46d7-a81f-0f45d9c14cda)

**Comment by guozhigq** [comment]
这都行，不过这个问题应该是flutter本身的 🤦

**Comment by guozhigq** [comment]
> 这都行，不过这个问题应该是flutter本身的 🤦

看了一下，我手机上正常。你看看之前版本正常不

**Comment by VillagerTom** [comment]
我一路降级到初版，都是有问题的。

**Comment by VillagerTom** [comment]
查了相关资料，似乎一方面是Android 5没有使用CJK字体导致的。我的另一部Android 7没有问题。

**Comment by VillagerTom** [comment]
另外想请教一下Flutter开发中有没有公认的方法用来独立调试各个组件？比如在test目录新建一个dart文件，仿照main.dart重写一个main布局（我不知道是不是这样叫）？
