### ISSUE TITLE
iOS .ipa package

### ISSUE THREAD

**Issue by alphavvv** [guozhigq/pilipala#43]
能否提供ipa包以供自签使用

**Comment by do02fw** [comment]
可以整个test那个方式安装

**Comment by guozhigq** [comment]
> 可以整个test那个方式安装

特别大的那种包么

**Comment by 0123-smallbottle** [comment]
http://alist.qinjiu.top:8080/Pilipala/smallbottle_build/2023-8-29

**Comment by do02fw** [comment]
> > 可以整个test那个方式安装
> 
> 特别大的那种包么

不知道，反正是测试版那个应用，可以不上架商店

**Comment by alphavvv** [comment]
> > 可以整个test那个方式安装
> 
> 
> 
> 特别大的那种包么

最新上传的包自签显示缺少.app文件

**Comment by guozhigq** [comment]
更新了 老哥再试试

**Comment by guozhigq** [comment]
自v1.0.7版本起，将在release同步更新**未签名**的ipa文件，需自签食用。
