### ISSUE TITLE
免登录 1080P 没效果

### ISSUE THREAD

**Issue by ShuiHuo** [guozhigq/pilipala#432]
### 问题描述
　　播放设置里面打开“开启1080P”后，清晰度依旧只有480P，且不能点击更高清晰度。

### 复现步骤
1. 打开设置，点击“播放设置”，开启“开启1080P”。
2. 回到首页，随意点进视频，播放。
3. 点击右上角菜单，可看见“选择画质”下方描述为“当前画质 480P 清晰”。
4. 点击“选择画质”，可看见“1080P 高清”和“720P 高清”为灰色且不可点击状态。

### 预期行为
　　开启“开启 1080P”后，能使用 1080P 清晰度播放的视频。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Android 14（MyOS 14），Android System WebView 117.0.5938.60 (593806031)

### 相关截图或日志
![软件版本](https://github.com/guozhigq/pilipala/assets/7471938/dff10dde-898c-4a5c-b7ef-a3c8a513cfa7)
![播放设置](https://github.com/guozhigq/pilipala/assets/7471938/673027eb-ce53-42ad-aad5-e485f0e756e8)
![播放视频选择清晰度 =279x620](https://github.com/guozhigq/pilipala/assets/7471938/5562e40e-fe14-4704-8fcc-066bea2ce754)

**Comment by orz12** [comment]
修好了

**Comment by ShuiHuo** [comment]
[#431](https://github.com/guozhigq/pilipala/commit/c4bf7d3a3bc70e3f939114e98ca598d1a44fffe3)

**Comment by ShuiHuo** [comment]
https://github.com/guozhigq/pilipala/releases/tag/v1.0.17.0125
