### ISSUE TITLE
收藏夹内显示原版“我的收藏与订阅”

### ISSUE THREAD

**Issue by diana7127** [guozhigq/pilipala#439]
### 功能描述
原版在“我的收藏”中除了默认收藏夹和用户创建的收藏夹，还有“我的收藏与订阅”，用来收藏订阅的合集内容

### 目标
目前在pilipala无法查看已收藏的订阅，希望新版本可以添加“我的订阅合集”这个功能

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
