### ISSUE TITLE
视频内评论区回复页面全屏状态下会覆盖视频

### ISSUE THREAD

**Issue by ajdgsu** [guozhigq/pilipala#441]
### 问题描述
开启评论区回复的页面时再点击全屏按钮会导致评论区回复挡住视频，无法观看

### 复现步骤
点开任意一个视频下评论区的回复（左上方出现评论详情）时开启视频全屏模式，此时评论详情会直接挡在视频前方

### 预期行为
正常播放视频

### 系统信息
小米13 MIUI 14.0.17

### 相关截图或日志
![Screenshot_2024-01-24-04-48-43-096_com guozhigq pilipala_test](https://github.com/guozhigq/pilipala/assets/45306865/73c1d1ac-be5c-4b57-bc3b-63d182c391b3)

**Comment by ajdgsu** [comment]
PS：打开视频简介后再全屏也有同样的问题

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。

**Comment by guozhigq** [comment]
> v1.0.20 中已解决，有问题可以再打开。

目前只解决了评论的

**Comment by guozhigq** [comment]
v1.0.23 中已解决
