### ISSUE TITLE
[弹幕相关功能建议]添加几个弹幕样式

### ISSUE THREAD

**Issue by MianSoft** [guozhigq/pilipala#442]
### 功能描述
添加几个弹幕样式

### 目标
默认的弹幕样式边框有点粗过头了，希望能让用户更改样式

### 解决方案
可以加个滑块让玩家更改弹幕边框的粗细
或是给个菜单让用户选选择想要的样式，比如以前b站客户端可以改无边框和悬浮

### 其他
请提供已实现该功能或类似功能的应用

**Comment by orz12** [comment]
你说的是弹幕描边吗？

**Comment by orz12** [comment]
已更新

**Comment by MianSoft** [comment]
就是改成无描边感觉行高有点高,不过不严重够日用了,感谢

**Comment by orz12** [comment]
> 改成无描边感觉行高有点高,不过不严重够日用了,感谢

感觉有描边更适合日用一点 看字对比度大比较不费劲 不过我还是提供了无描边选项 至于行高问题有点难改 鉴于需求很少 就先放着吧

**Comment by MianSoft** [comment]
我喜欢用粗一点的自重加无边框,这个细字重加上行高感觉弹幕密度有点低,或许加个字重选择也能缓解,不过不强求了,感谢回复

**Comment by orz12** [comment]
> 我喜欢用粗一点的自重加无边框,这个细字加行高感觉弹幕密度有点散,或许加个字重选择也能缓解,不过不强求了,感谢回复

它的难点倒不在于代码有多难写 而是这个弹幕的一部分实现在另一个库里面 他没提供选项的话 我没有办法直接改到 或许你可以到引用的那个库提一下issue

**Comment by MianSoft** [comment]
明白了不强求owo
