### ISSUE TITLE
主页动态没有使用动态页而是网页

### ISSUE THREAD

**Issue by DarkCWK** [guozhigq/pilipala#45]
### 问题描述
主页点击动态进入的是网页而不是设计好的动态页

### 复现步骤
在主页点击动态

### 预期行为
进入设计好的动态页

### 系统信息
Android 12

### 相关截图或日志
![Screenshot_20230830-090056_PiliPala](https://github.com/guozhigq/pilipala/assets/20531116/a9456ccb-ccd1-4799-b57a-3712e018fc01)
![Screenshot_20230830-090059_PiliPala](https://github.com/guozhigq/pilipala/assets/20531116/a0fd3ec3-0757-40c5-91b1-7d3fd628a6c9)

**Comment by do02fw** [comment]
对，我也说过这个问题，提示下载哔哩哔哩客户端

**Comment by do02fw** [comment]
还有你的Android12太低了，升级到Android13吧，现在Android14都出来了

**Comment by guozhigq** [comment]
预计在1.0.7中设计为app内渲染

**Comment by guozhigq** [comment]
> 还有你的Android12太低了，升级到Android13吧，现在Android14都出来了

不低吧  后面版本也没啥大的功能更新，我也用的12🤣

**Comment by DarkCWK** [comment]
> 还有你的Android12太低了，升级到Android13吧，现在Android14都出来了

做应用不是跟着版本做的……是看使用率的，Google的6月份信息表示12是第三使用率16.3%，第一是11，第二是10，我不觉得12有什么问题

**Comment by do02fw** [comment]
> > 还有你的Android12太低了，升级到Android13吧，现在Android14都出来了
> 
> 做应用不是跟着版本做的……是看使用率的，Google的6月份信息表示12是第三使用率16.3%，第一是11，第二是10，我不觉得12有什么问题

新版本优化更好

**Comment by DarkCWK** [comment]
暂时没有足够吸引我的理由上去, 12 挺好

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by do02fw** [comment]
ONE ui 6马上就发布了，我要更新
