### ISSUE TITLE
专栏相关问题

### ISSUE THREAD

**Issue by morning-start** [guozhigq/pilipala#465]
### 问题描述

专栏里一些图片不清晰，一些头像无法显示。

### 预期行为

希望修复问题，并对图片增加**点击放大查看**功能。增加**文字选中复制**功能

### 系统信息

Android

### 相关截图或日志

www.bilibili.com/read/cv29920557/

![Screenshot_2024-01-27-09-47-28-748_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/76601464/2f158186-e414-4664-a596-d2cffe00f942)
![Screenshot_2024-01-27-09-47-41-021_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/76601464/11767b24-b2f7-4fac-8100-f2f9608a0a05)
![Screenshot_2024-01-27-09-49-54-646_com guozhigq pilipala-edit](https://github.com/guozhigq/pilipala/assets/76601464/5b9c5715-0c0b-4004-9525-5d4bc4687a07)

**Comment by guozhigq** [comment]
1.0.25版本已增加
