### ISSUE TITLE
v1.0.17无法登录

### ISSUE THREAD

**Issue by Oneton429** [guozhigq/pilipala#474]
### 问题描述
请提供一个清晰而简明的问题描述。
从1.0.8升级到1.0.17后，点了清除access key后，登录网页后报错（见下）。降级后登录再升级恢复正常

### 复现步骤
请提供复现该问题所需的具体步骤。
同上

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
小米13 Pro，HyperOS 1.0.4.0
Android 14; 2210132C Build/UKQ1.230804.001

Kiwi Browser 120.0.6099.116

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
```
NoSuchMethodError: Class '_Map<String, dynamic>' has no instance getter 'msg'.
Receiver: _Map len:2
Tried calling: msg
```

**Comment by VillagerTom** [comment]
据@orz12 在tg群内说，v1.0.17更改了缓存数据格式。如果遇到任何问题，请清除APP数据或卸载重装后使用。

**Comment by guozhigq** [comment]
新的登录方式应该可以解决这个问题了
