### ISSUE TITLE
楼中楼部分评论内容空白

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#477]
楼中楼里某评论被删除或发送者改名，回复它的评论会变成空白。
例：BV1v34y1Z7R2，评论“因为A那边独播，而且不用花钱看”的楼中楼，下面其他几个评论里也有
截图（前：pilipala，后：其他客户端）
![Screenshot_20240128_193617_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/106989902/86e93e6e-7504-4bcf-a7c6-b2abf947f18a)
![Screenshot_20240128_193646_com a10miaomiao bilimiao](https://github.com/guozhigq/pilipala/assets/106989902/927f9280-77fb-402f-b3c6-efce0fd74bc3)

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
