### ISSUE TITLE
功能请求：希望可以在搜索结果页面出来的视频底部加入日期显示

### ISSUE THREAD

**Issue by Anhai0501** [guozhigq/pilipala#479]
![Screenshot_2024-01-29-11-13-33-101_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/99585202/34747a2e-a20c-4a7e-903b-38847493f0dc)

**Comment by Anhai0501** [comment]
![Screenshot_2024-01-29-11-13-33-101_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/99585202/9a7f535b-3090-429e-878f-270fb8de9ad2)

如图

**Comment by orz12** [comment]
#458

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
