### ISSUE TITLE
大佬，点击全屏按钮的时候容易误触进度条

### ISSUE THREAD

**Issue by HaseozZ** [guozhigq/pilipala#48]
![IMG_20230831_031035](https://github.com/guozhigq/pilipala/assets/81415247/4d8ed21d-cd6e-45ca-89ad-5d504c552e5b)

**Comment by HaseozZ** [comment]
全屏按钮和进度条有点近，大佬你觉得放到下面会怎么样

**Comment by guozhigq** [comment]
1.0.6这部分间距会大点，减少误触。全屏可以用手势，屏幕中间上滑进入全屏，下滑退出

**Comment by guozhigq** [comment]
v1.0.6中已修改
