### ISSUE TITLE
media_kit: arm64-v8a JAR verification failed.

### ISSUE THREAD

**Issue by yzc90912** [guozhigq/pilipala#480]
运行报错 A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.

**Comment by orz12** [comment]
可能是jar文件没下载完，可以点进这个gradle文件里看看下载地址和路径，想办法手动下载一个完整的覆盖进去。欢迎加群讨论。

**Comment by guozhigq** [comment]
参考一下 https://github.com/media-kit/media-kit/issues/681#issuecomment-1912740197 这个issues试试
