### ISSUE TITLE
解锁画质

### ISSUE THREAD

**Issue by Chen017** [guozhigq/pilipala#481]
### 功能描述
请提供对所请求功能的清晰描述。
哔哩哔哩画质解锁 支持4k hdr
### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by orz12** [comment]
为了规避风险，不会计划支持类似功能

**Comment by VillagerTom** [comment]
快进到有人开发xposed模块用来破解pilipala（

**Comment by Chen017** [comment]
那能不能整一个解锁画质模块 伪装一下作者嘶
