### ISSUE TITLE
「功能请求」动态相关

### ISSUE THREAD

**Issue by ououtstanding** [guozhigq/pilipala#483]
十分感谢您点开我的请求，开发辛苦了

### 功能描述
底部栏位只保留动态和媒体库，将最左侧推荐，直播等等去除掉
或者是进入软件后，首先展示的页面是动态
因为，只要一看推荐，点开一个，就会不知不觉消耗大量时间。

### 目标
进入APP后，不显示推荐及直播等，直接显示动态

### 解决方案
暂无

### 其他
暂无

**Comment by ououtstanding** [comment]
> 十分感谢您点开我的请求，开发辛苦了
> 
> ### 功能描述
> 底部栏位只保留动态和媒体库，将最左侧推荐，直播等等去除掉 或者是进入软件后，首先展示的页面是动态 因为，只要一看推荐，点开一个，就会不知不觉消耗大量时间。
> 保留搜索
> ### 目标
> 进入APP后，不显示推荐及直播等，直接显示动态
> 并且保留搜索
> ### 解决方案
> 暂无
> 
> ### 其他
> 暂无

**Comment by orz12** [comment]
目前这个功能不会优先得到支持，不过你可以先在外观设置-首页tabbar关掉推荐和直播

**Comment by VillagerTom** [comment]
> 目前这个功能不会优先得到支持，不过你可以先在外观设置-首页tabbar关掉推荐和直播

或者可以添加一个默认首页的设置？

**Comment by ououtstanding** [comment]
十分感谢！！
