### ISSUE TITLE
[Bug] 部分视频从首页播放404，从其他地方播放无法请求评论区

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#484]
### 问题描述
部分视频从首页播放404，从其他地方播放无法请求评论区

### 复现步骤
https://www.bilibili.com/video/BV1j6421379q
https://www.bilibili.com/video/BV1BK421y7FL
1. 对首页进行单元测试
2. 直接搜索BV号播放

### 预期行为
正常播放视频或正常加载评论区

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by VillagerTom** [comment]
https://github.com/guozhigq/pilipala/assets/89803422/2fddcf24-da8e-4df6-a581-2e8c4d09bfdd


https://github.com/guozhigq/pilipala/assets/89803422/41dead00-13f5-4237-8c17-ac457024e8dd

**Comment by VillagerTom** [comment]
@cxw620 是否与API风控有关？

**Comment by guozhigq** [comment]
今天发布的视频的bv在转av的时候出现问题了

**Comment by VillagerTom** [comment]
> 今天发布的视频的bv在转av的时候出现问题了

是的，不能播放的部分视频av号被添加了短横线`-`
![Screenshot_2024-01-30-14-28-03-17](https://github.com/guozhigq/pilipala/assets/89803422/882b2a78-9359-461b-9b49-211c0cf805d0)

**Comment by VillagerTom** [comment]
坏了，首页推荐视频开始大片大片不能放了

**Comment by guozhigq** [comment]
晚上回去修

**Comment by cxw620** [comment]
看起来修好了

**Comment by cxw620** [comment]
好像还没修好()

**Comment by guozhigq** [comment]
试一试最新的release

**Comment by VillagerTom** [comment]
一切正常！
