### ISSUE TITLE
视频播放相关BUG

### ISSUE THREAD

**Issue by oliverance** [guozhigq/pilipala#485]
### 问题描述
1.接连观看视频后页面明显掉帧（包括视频也掉帧）
2.偶尔的闪退问题
3.手势调整亮度和音量时调整不太好操作，很不稳定

### 复现步骤
1.点开一视频，然后再在页面中点击第二个、第三个......
2.无
3.打开视频，然后用手势调整音频亮度

### 预期行为
1.无卡顿
2.无闪退
3.手势流畅调整稳定

### 系统信息
pilipala1.0.17
红米K40Pro+
MIUI14.0.7正式版
联通5G WIFI6网

**Comment by orz12** [comment]
亮度音量可以录屏看一下吗？我这边调整很正常
