### ISSUE TITLE
type 'Null' is not a subtype of type 'Map<String,  dynamic>

### ISSUE THREAD

**Issue by qazgp** [guozhigq/pilipala#487]
### 问题描述
有的视频点开会报错这个提示信息

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
试试最新的release？

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
