### ISSUE TITLE
NoSuchMethodError: The method 'map' was called on null.

### ISSUE THREAD

**Issue by 0xarch** [guozhigq/pilipala#488]
### 问题描述
卡死

### 复现步骤
未知

### 系统信息
Redmi K70E
HyperOS 1.0.8
Android 14
SDK 34

### 相关截图或日志
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: UP1A.230905.011
board: duchamp
bootloader: unknown
brand: Redmi
device: duchamp
display: UP1A.230905.011
fingerprint: Redmi/duchamp/duchamp:14/UP1A.230905.011/V816.0.8.0.UNLCNXM:user/release-keys
hardware: mt6897
host: pangu-build-component-system-231178-rtkv0-48b1r-9hs82
isPhysicalDevice: true
manufacturer: Xiaomi
model: 2311DRK48C
product: duchamp
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.8.0.UNLCNXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2023-12-01
------- 应用信息 -------
environment: release
version: 1.0.18
appName: PiliPala
buildNumber: 10183
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<AssetItem>(Closure: (dynamic) => AssetItem)
------- 错误堆栈 -------
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      new LatestDataModel.fromJson (package:pilipala/models/github/latest.dart:21)
#3      AboutController.getRemoteApp (package:pilipala/pages/about/index.dart:187)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
刚进入就卡死吗？试试最新的release。看着像是检测更新的时候出了问题

**Comment by 0xarch** [comment]
1.0.19暂时没有出现卡死问题，似乎这个日志和卡死无关
