### ISSUE TITLE
开启 pip 画中画模式后下拉通知栏导致的问题

### ISSUE THREAD

**Issue by DrinkingHook** [guozhigq/pilipala#489]
### 问题描述
开启pip播放 画中画功能，下拉通知栏，再回到视频主页，评论区会丢失，应该是bug吧

### 复现步骤
见视频

### 系统信息
redmi k50 
hyperos

### 相关截图或日志
大于10m无上上传，压了一下画质
https://github.com/guozhigq/pilipala/assets/113015731/07b9b55d-4dae-493c-8375-d3295d5ae957

**Comment by guozhigq** [comment]
已完成
