### ISSUE TITLE
视频加载问题

### ISSUE THREAD

**Issue by Fishheadrabbit** [guozhigq/pilipala#491]
### 问题描述
请提供一个清晰而简明的问题描述。
点击视频提示视频资源失效（在哔哩哔哩里能正常播放），无论开启还是关闭CDN优化都这样（在pilipala里的搜索栏输入视频的BV能正常播放

### 复现步骤
请提供复现该问题所需的具体步骤。
点击首页推荐里的视频有概率复现

### 预期行为
请描述你期望的正确行为或结果。
修复bug

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。oppok9x color os 13 pilipala:1.0.18

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。https://github.com/guozhigq/pilipala/assets/105645188/c2cc6574-0e6e-4339-869c-5d38e9ac1ea2

**Comment by wanzh5** [comment]
补充：首页无法点开的视频也无法收藏，视频：BV12A4m1L7Vn

**Comment by Fishheadrabbit** [comment]
补充：在搜索栏搜索后打开在首页打不开的视频返回主页再打开那个视频会崩溃

**Comment by Fishheadrabbit** [comment]
这位大佬，你好，1.0.19版本更严重了，以前是大概率复现象，该版本是100%复现，希望修复，谢谢

**Comment by guozhigq** [comment]
> 这位大佬，你好，1.0.19版本更严重了，以前是大概率复现象，该版本是100%复现，希望修复，谢谢（提示请求错误）

试一试最新的release，昨晚覆盖更新了一版

**Comment by Fishheadrabbit** [comment]
> > 这位大佬，你好，1.0.19版本更严重了，以前是大概率复现象，该版本是100%复现，希望修复，谢谢（提示请求错误）
> 
> 试一试最新的release，昨晚覆盖更新了一版

好了，谢谢
