### ISSUE TITLE
首页关注的up主视频无法播放

### ISSUE THREAD

**Issue by 125835** [guozhigq/pilipala#492]
### 问题描述
首页关注的up主视频无法播放
### 复现步骤
首页，点击关注的up的视频。

### 预期行为
正常播放视频。

### 系统信息
miui14.0.5
红米K40游戏增强版
pilipala 1.0.18 。

### 相关截图或日志
![Screenshot_2024-01-31-18-54-23-721_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/84666014/49182b8a-15fc-4db2-8e40-cfc15edcb8b7)

https://github.com/guozhigq/pilipala/assets/84666014/89d8e23c-fb61-421f-8bf2-0298bb7e6177

。

**Comment by guozhigq** [comment]
试一试最新的release

**Comment by 125835** [comment]
您有信

**Comment by 125835** [comment]
ok🙂
