### ISSUE TITLE
无法收藏视频

### ISSUE THREAD

**Issue by dpkg123** [guozhigq/pilipala#493]
### 问题描述
无法收藏视频，表现为点击添加到收藏夹后转圈没有返回到视频详情页，收藏夹也没有收藏视频。

### 复现步骤
下载最新版本安装包
安装并登录
打开并收藏视频

### 预期行为
收藏视频成功

### 系统信息
OPPO PEQM00
ColorOS12.1 Android12
kernel version 4.14.186
Android Webview 117.0.5938.44
Pili 1.18
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
试一试最新的release
