### ISSUE TITLE
动态一栏的默认tab的个人选项

### ISSUE THREAD

**Issue by cgcel** [guozhigq/pilipala#499]
### 功能描述
动态栏有4个tab，全部，投稿，番剧，专栏，希望可以让用户自己设置默认显示哪一项，比如点击动态后，默认显示投稿，这样可以过滤很多up的恰饭广告。

### 目标
用户可以自行决定默认显示哪一个tab。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by Wxq703** [comment]
设置-其他设置-动态展示，可以设置优先展示哪个
