### ISSUE TITLE
[Bug] 视频详情加载失败导致播放器崩溃（灰屏）

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#506]
### 问题描述
网络问题视频详情加载失败，恢复后再次打开播放器灰屏。

### 复现步骤
1. 打开APP首页，等待推荐加载完成；
2. 关闭手机网络；
3. 点击任意视频播放，得到请求异常警告；
4. 返回首页，打开网络（点击重试也会闪退回首页）；
5. 再次点击**原视频**播放；
6. 播放器灰屏；
7. 杀死重启后恢复。

### 预期行为
点击重试后视频详情能够正常重新加载；再次打开播放器能够正常播放视频。

### 系统信息
OPPO A33 Android 5.1.1

**Comment by VillagerTom** [comment]
#554 似乎解决了该问题。

**Comment by guozhigq** [comment]
> #554 似乎解决了该问题。

再出现类型情况的时候，播放/暂停按钮是不是会消失

**Comment by VillagerTom** [comment]
播放器组件完全灰屏，没有任何按钮和进度条。
