### ISSUE TITLE
[功能请求] 交换全屏与退出全屏的手势

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#517]
### 功能描述
在播放器上，下滑手势可以表示让播放器占满屏幕，上滑手势可以表示让播放器回归原来的大小。目前的全屏手势有些违反直觉。

### 目标
使全屏与退出全屏手势更加符合直觉。

### 其他
另外，上滑手势有时会误触详情页或评论区，导致本来想要全屏却滑动了视频推荐或评论。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
