### ISSUE TITLE
关于专栏的一些建议

### ISSUE THREAD

**Issue by Entaligaa** [guozhigq/pilipala#529]
希望浏览专栏的体验可以好一点

1、文本
- 希望可以给出文章排版的自定义选项
- 文本可以复制（原版b站复制内容之后会标注来源的标识，这个作者你看看要不要也与官方一样？）

2、图片
- 具体是竖版图片缩放显示，横版图片适当缩放+裁切
- 图片保存可以如 小红书 那种，直接长按图片蹦出交互菜单（感觉更有效率一点啦）

大概就是这些，辛苦作者那么长时间的开发
新年快乐。

**Comment by guozhigq** [comment]
1.0.25版本已增加
