### ISSUE TITLE
希望今天的视频显示具体时间

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#533]
### 功能描述
今天的视频显示具体几点几分，至少显示几小时前。然而现在只显示今天。

### 目标
其他客户端显示的是几小时前。有这些更具体的信息，才能知道追剧更新的时间，知道今晚能不能看到，该不该睡觉。详情页却不是最详细，这谁能想到。

### 解决方案
在详情页前，无论是搜索结果页，还是投稿页，都显示了几小时前。估计是能获取具体时间的。或者功能照搬过来也行。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
