### ISSUE TITLE
收藏的删除按钮经常点不到

### ISSUE THREAD

**Issue by xfdyd** [guozhigq/pilipala#534]
### 问题描述
收藏的删除按钮经常点不到，变成了打开视频。稍后再来在官方客户端上有数量限制，我已经满了，所以经常要增删收藏夹来替代这个功能。

### 预期行为
按钮往里面来一点，控件范围大一点。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
