### ISSUE TITLE
状态栏不正常地被隐藏

### ISSUE THREAD

**Issue by skymkmk** [guozhigq/pilipala#537]
### 问题描述
视频在非全屏状态下播放完成后，界面会抖动，并且状态栏消失

### 复现步骤
1. 点击任意视频播放
2. 在非全屏状态下播放完成
3. 状态栏消失

### 预期行为
状态栏正常显示，画面不抖动

### 系统信息
操作系统：Android 14
Android 皮肤：HyperOS 1.0.3.0

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/62805286/d562ad14-da6a-4dd9-a32d-31aa9ee64640

**Comment by guozhigq** [comment]
播放完成自动退出全屏导致

**Comment by guozhigq** [comment]
最新版已修复
