### ISSUE TITLE
分支feature-liveRoomRender出现直播间重复播放

### ISSUE THREAD

**Issue by orz12** [guozhigq/pilipala#540]
该commit：https://github.com/guozhigq/pilipala/commit/d5134f972d9ef8c5ba96015993732e33d51231c2
会导致直播间出现多次播放，步骤：点进某个直播间，返回，再次点进该直播间，会听到两个声音，且返回后app崩溃。revert该commit可以修复此问题。咱俩的版本都出现了，我暂时没有看出问题的原因。

**Comment by VillagerTom** [comment]
我这里点进一次就会出现两个声音。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
