### ISSUE TITLE
增加仅播放音频功能

### ISSUE THREAD

**Issue by zzzqh** [guozhigq/pilipala#541]
### 功能描述
当前版本（1.0.19）挂同一视频在后台，静置桌面，关闭浮窗后耗电量是2-2.3w，比前台播放1.5-1.7w还高。
出于节省电量和流量方面的考量，希望能提供仅听音频功能。

### 目标
1、节省电量，节省流量。
2、让收藏夹兼顾半个歌单功能。

### 解决方案
0、内置一个简易的音乐播放界面。
1、在视频的**详情界面**提供仅听音乐按钮。
2、媒体库中长按**收藏夹**弹出作为音乐播放按钮，并使收藏夹内音乐连续播放。

### 其他
请提供已实现该功能或类似功能的应用
[APM](https://github.com/lovegaoshi/azusa-player-mobile?tab=readme-ov-file)

感谢作者，目前app已经基本可以替换臃肿的b站app了，期待进一步发展。

**Comment by guozhigq** [comment]
重复 issues #222
