### ISSUE TITLE
首页 稍后再看 失效

### ISSUE THREAD

**Issue by ryanlian08** [guozhigq/pilipala#546]
### 问题描述
首页视频通过点击视频框右下角三个点加入稍后再看时无反应（没有弹窗也没有加入稍后再看列表），而通过动态页视频右上角三个点加入 或进入视频播放页再加入稍后再看则没问题。

### 复现步骤
刚安装时正常，使用app几分钟后自动失效，清除app所有数据或卸载重装后正常，几分钟后自动失效。

### 预期行为
首页视频通过点击视频框右下角三个点加入稍后再看时可以正常加入。

### 系统信息
MIUI13.0.8

**Comment by ryanlian08** [comment]
更正：使用web端推荐时正常，使用app端推荐时可以复现上述问题。
之前没发现 抱歉了

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
