### ISSUE TITLE
弹幕速度可以慢一些

### ISSUE THREAD

**Issue by bigshans** [guozhigq/pilipala#547]
### 功能描述
希望能够调节视频播放时弹幕的速度，放慢一些。

### 目标
当前弹幕的速度对我来说有些太快了，来不及看就过去了。感觉官方的应用弹幕速度好很多。希望

### 解决方案
或者提供弹幕速度可以调节的选项也可以。

### 其他
无。

**Comment by VillagerTom** [comment]
播放器内**弹幕设置**有**弹幕时长**滑动条

**Comment by bigshans** [comment]
多谢！弹幕设置我没发现下拉还有。
