### ISSUE TITLE
iOS动态中的图片打开后无法返回上一级

### ISSUE THREAD

**Issue by Liuyiyang888888** [guozhigq/pilipala#557]
### 问题描述
iOS动态中的图片打开后无法返回上一级

### 复现步骤
打开一个有图片的动态，点击查看图片

### 预期行为
可以返回上一级

### 系统信息
IOS16

### 相关截图或日志
无

### 建议
添加返回按钮

**Comment by guozhigq** [comment]
试下下滑手势可以关闭不，近期的版本应该会先加个关闭按钮

**Comment by Liuyiyang888888** [comment]
行

**Comment by guozhigq** [comment]
v1.0.21版本增加了关闭按钮
