### ISSUE TITLE
[BUG 反馈] 已读成功重复出现

### ISSUE THREAD

**Issue by xiangfa-test** [guozhigq/pilipala#559]
### 问题描述
在应用状态（也可能是活动）改变后会重复弹出已读成功的toast

### 复现步骤
从信息中的任意一个up主 进入他（她）被b站推送的视频
然后尝试改变状态（如全屏 退出全屏 从合集切换视频）
问题已复现

### 预期行为
不再弹出已读成功的toast

### 系统信息
OPPO a9
Android 10
Android System WebView 122.0.6261.43

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/106453502/1e22b906-08a6-484d-87b8-2b7c047a3590

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/21ed67e5691b6e10334e951b7f25be88173ffa01

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
