### ISSUE TITLE
1.0.6 设置界面，有两个自动播放

### ISSUE THREAD

**Issue by jlu511** [guozhigq/pilipala#56]
### 问题描述
1.0.6 设置界面，有两个自动播放

### 复现步骤
1.0.6 设置界面，有两个自动播放

### 预期行为
删除一个？

### 系统信息
鸿蒙4

### 相关截图或日志
![05e36c2dbc9708e3463732c548de7f4](https://github.com/guozhigq/pilipala/assets/64378673/fa5d6d63-c83e-43e2-87fe-0d31f0d67869)

**Comment by guozhigq** [comment]
挪了位置后忘了删除原来的了 😂

**Comment by guozhigq** [comment]
可以从网盘重新下载
https://www.123pan.com/s/9sVqVv-flu0A.html
提取码:pili
