### ISSUE TITLE
希望增加选项首页推荐使用pc网页端数据

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [guozhigq/pilipala#565]
### 功能描述
如题，b站app端首页推荐算法实在太烂了10个视频9个辣鸡，web端好不少

### 目标
增加使用pc端推荐的选项。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
推荐设置里 **web端推荐** 就是用的pc网页端的接口
