### ISSUE TITLE
希望增加更改推荐信息流来源的功能

### ISSUE THREAD

**Issue by ulysseswake** [guozhigq/pilipala#579]
### 功能描述
在日常使用中发现，『哔哩哔哩』和『bilibili』(特指play store版本的B站)在「推荐」的信息流中存在很大差异，不了解具体原因，猜测可能是『bilibili』中不会推送一些流量扶持的UP。而在使用『Pilipala』的过程中发现应用的信息流中大量穿插着一些我不感兴趣的大UP，同时也无法屏蔽或者点不感兴趣。因此希望可能增加使得「推荐」信息流和『bilibili』保持相对一致的功能，不知道能不能实现(

### 目标
「推荐」信息流和『bilibili』(特指play store版本的B站)保持相对一致，提高信息流内容质量。

### 解决方案
不太懂。是调用API的问题吗？『Pilipara』目前可以选择首页推荐类型为「网页端」和「app端」，不知道能不能加上play store的app端推荐qwq.

### 其他
无

**Comment by guozhigq** [comment]
目前没有找到谷歌版的推荐接口

**Comment by NeKoOuO** [comment]
原來推薦的接口有分 難怪刷到的東西變難看了QAQ

**Comment by orz12** [comment]
我抓过 play版用的推荐接口也是https://app.bilibili.com/x/v2/feed/index
