### ISSUE TITLE
增加排行榜或使用排行榜替代热门页

### ISSUE THREAD

**Issue by Crazyokd** [guozhigq/pilipala#584]
### 功能描述
b站在某次更新后热门页不再是真正的热门页，而是一些个性化推荐相关的热门视频，真正的全区排行榜也就是以前的热门需要再点击一次排行榜。
![image](https://github.com/guozhigq/pilipala/assets/74645100/fa2fbec6-5066-4c1e-8537-9cbcc94106af)
上图中的综合热门标签也就是app中热门标签默认展示的内容，但是真正的全站热门在排行榜中。（播放量前者一般是几十万，后者是几百万）

### 目标
希望能够在app中增加排行榜标签，或使用排行榜标签替代现在的热门标签

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
这个功能是我刷b站的刚需（一般是动态+排行榜），希望作者大大能够考虑考虑。

**Comment by GO-PIO** [comment]
署名同求

**Comment by kuzen** [comment]
希望能自定义控制底部导航，比如我希望能关闭排行榜

**Comment by guozhigq** [comment]
已支持
