### ISSUE TITLE
可以增加一个把播放详情页下边的相关视频推荐屏蔽掉的功能吗？

### ISSUE THREAD

**Issue by FalseName92** [guozhigq/pilipala#585]
### 功能描述
进入视频详情页后，下放会自动推荐很多相关的视频，这个推荐算法经常时候会推荐到一些毫无干系的垃圾视频，希望可以增加一个这样的功能屏蔽的播放页下方的视频推荐。感谢你的开发，软件很好用。

**Comment by guozhigq** [comment]
v1.0.22 中已增加
