### ISSUE TITLE
[Bug] 不能识别带参数的站内链接。

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#586]
### 问题描述
自pr #470 后，评论区带参数的B站链接不能识别为jumpUrl。

### 复现步骤
使用main分支最新编译或最新版pilipalax打开视频 https://b23.tv/BV1Zh411A7Mi 查看置顶评论。

### 预期行为
链接可以被正常识别并跳转。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
