### ISSUE TITLE
[Bug] 私信页错误地显示了表情面板

### ISSUE THREAD

**Issue by VillagerTom** [guozhigq/pilipala#588]
### 问题描述
由从私信打开的视频返回私信页，下方错误地显示了表情面板。

### 复现步骤
1. 从特别关注私信推送打开视频；
2. 打开评论输入框并关闭；
3. 返回私信页。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

https://github.com/orz12/pilipala/assets/89803422/2cf66e35-1c15-4f0f-9731-0d80e023ef73

**Comment by VillagerTom** [comment]
@orz12 说直接合并了上游的代码，所以我将原issue拷贝过来这里反馈。

**Comment by VillagerTom** [comment]
又出现了新bug，动态评论区不能展开表情面板。

**Comment by guozhigq** [comment]
v1.0.20 中已解决，有问题可以再打开。
