### ISSUE TITLE
全屏播放支持自动旋转

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#59]
即使手机没开自动旋转

**Comment by guozhigq** [comment]
手机横屏自动全屏么

**Comment by wanzh5** [comment]
不是这个意思，是在打开全屏之后支持左右旋转，这个只有在手机开了自动旋转之后才能做到，但是原版是没开也可以的

**Comment by guozhigq** [comment]
v1.0.7 已支持（由于xcode版本问题，暂不支持iOS端）
