### ISSUE TITLE
账号不能登录，也不能收藏

### ISSUE THREAD

**Issue by misijiawen** [guozhigq/pilipala#597]
### 账号不能登录
在账号登录页面进不去，并且收藏也不能用
![Screenshot_2024-03-01-15-55-15-58_130b0d7520509a75c6a4102c4ba0249d](https://github.com/guozhigq/pilipala/assets/161300704/b6ca129f-7dbc-4e03-ba16-4b09c3d89dc7)
![Screenshot_2024-03-01-15-55-37-55_130b0d7520509a75c6a4102c4ba0249d](https://github.com/guozhigq/pilipala/assets/161300704/489667da-c0b9-46f4-b75b-c4e7a5142b02)

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
能正常登录啊

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
账号登录页面进不去? 怎么说

**Comment by misijiawen** [comment]
感谢大佬 感谢大佬
