### ISSUE TITLE
播放左右两边的双击快进功能的开启关闭选项

### ISSUE THREAD

**Issue by NatsumiXD** [guozhigq/pilipala#598]
### 功能描述
请提供对所请求功能的清晰描述。
在视频播放界面，双击左边以及右边会-10s/+10s，希望可以提供开关选项，暂停视频时不是很方便
### 目标
请描述你希望通过这个功能实现的目标。
自主选择开启或关闭这个功能
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
设置开关选项

**Comment by guozhigq** [comment]
看看播放设置

**Comment by NatsumiXD** [comment]
眼瞎了
