### ISSUE TITLE
显示联合投稿的其他up

### ISSUE THREAD

**Issue by NatsumiXD** [guozhigq/pilipala#599]
### 功能描述
请提供对所请求功能的清晰描述。
当前版本中只显示了主投稿，而未显示其他up主
### 目标
请描述你希望通过这个功能实现的目标。
看到其他up主
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
可以在视频详情中显示
### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
最新版本已实现
