### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by ououtstanding** [guozhigq/pilipala#605]
### 问题描述
返回到主页之后，底边栏也没有了

### 复现步骤
关闭首页所有内容，开启即跳转到动态，随便点开一个视频，翻到评论区，找到评论区里发的图片，点开，一直返回直到回到桌面为止，底边栏消失

### 预期行为
底边栏不会消失

### 系统信息
红米k40Pro

### 相关截图
![Screenshot_20240304064025](https://github.com/guozhigq/pilipala/assets/95462759/fb49ea15-8166-49b0-9297-597a32d27604)

**Comment by guozhigq** [comment]
在外观设置里把底栏收起关掉试试
