### ISSUE TITLE
调整分 P 菜单

### ISSUE THREAD

**Issue by Nyayurn** [guozhigq/pilipala#608]
### 功能描述
现在的分 P 菜单不易区分
![image](https://github.com/guozhigq/pilipala/assets/132195516/65f6aa85-dfd5-40e3-9e38-570ef3ee375b)

### 参考
官 B: 为每个 P 增加一个带圆角的长方形
![image](https://github.com/guozhigq/pilipala/assets/132195516/d998ea68-87f3-49a2-a752-282d926b671f)

**Comment by guozhigq** [comment]
已完成
