### ISSUE TITLE
评论区惦记图片再返回会视频播放进度会清零

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#61]
### 问题描述
请提供一个清晰而简明的问题描述。
点击评论区的图片，然后再关闭图片，视频的播放进度就清零了，又得从头播放
### 复现步骤
请提供复现该问题所需的具体步骤。
视频播放一会，然后评论区点击图片，关闭图片，视频会从头播放
### 预期行为
请描述你期望的正确行为或结果。
关闭图片不会从头播放和加载
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
oneUI5.1，Android13，最新版pilipili
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230903_210232](https://github.com/guozhigq/pilipala/assets/138294823/eaf964e9-6111-457b-8f49-0dd4a5416d54)
![Screenshot_20230903_210228](https://github.com/guozhigq/pilipala/assets/138294823/2dcc979a-1c21-4601-8aef-94999b36d8e1)

**Comment by guozhigq** [comment]
了解，预计1.0.7解决。

**Comment by guozhigq** [comment]
v1.0.7 已修复
