### ISSUE TITLE
视频简介被虚拟按键遮挡

### ISSUE THREAD

**Issue by kechuan** [guozhigq/pilipala#613]
### 功能描述

视频简介会遮挡住底部虚拟按键 就不太好操作
像这样
![1709615158864](https://github.com/guozhigq/pilipala/assets/42696536/fa0da0fd-1751-4404-bea1-2c261ac83eff)

希望能增加一个widget来不遮挡虚拟按键

### 解决方案

倒也挺好实现
在我这个例子里面只需要在视频详情页里多加一个sizedBox/Padding就可以

class IntroDetail => SingleChildScrollView => column

![image](https://github.com/guozhigq/pilipala/assets/42696536/6d0201a7-7b9f-4e6b-86df-70a2ebc92ea0)

也许flutter还有监听Android底部栏高度的api之类的东西?

**Comment by guozhigq** [comment]
最新版已修复
