### ISSUE TITLE
安卓客户端上面, 如果点击历史播放的某个视频, 播放未超过一分钟, 退出后, 重新查看该播放的时候, 会从播放00:00开始, 也就是之前的播放时长记录被重置了

### ISSUE THREAD

**Issue by gzhang91** [guozhigq/pilipala#617]
### 问题描述
安卓客户端上面, 如果点击历史播放的某个视频, 播放未超过一分钟, 退出后, 重新查看该播放的时候, 会从播放00:00开始, 也就是之前的播放时长记录被重置了

### 复现步骤
随机选取一个历史播放视频，打开后播放两三秒，返回

### 预期行为
历史视频播放时长应该增加两三秒

### 系统信息
miui14
![Screenshot_2024-03-09-08-52-41-185_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/28834180/a35d931b-8d21-4263-999a-b520275b308e)

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
啊？
