### ISSUE TITLE
链接错误

### ISSUE THREAD

**Issue by aucub** [guozhigq/pilipala#618]
### 问题描述
在 [about/index.dart#L280](https://github.com/guozhigq/pilipala/blob/ed0b43eff1f6043fe00e54c141053bd7ab336794/lib/pages/about/index.dart#L280) 的代码中存在一个小错误。应该使用的 URI 是 https://github.com/guozhigq/pilipala/releases ，但实际书写成了 https://github.com/guozhigq/pilipala/release ，缺少了结尾的 s，导致链接不正确。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
哈哈 好的，感谢❤️
