### ISSUE TITLE
关于 - 清除缓存 点击取消后仍然显示清除成功

### ISSUE THREAD

**Issue by PRO-2684** [guozhigq/pilipala#619]
### 问题描述
关于 - 清除缓存 点击取消后仍然显示清除成功

### 复现步骤
进入关于，点击清除缓存，点击取消

### 预期行为
对话框关闭，不显示 toast

### 系统信息
Android 13, MIUI 14

### 相关截图或日志

![Screenshot_2024-03-07-13-25-35-645_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54608551/1eae730c-7702-4742-b445-4b1500a5a493)

**Comment by guozhigq** [comment]
最新版已修复
