### ISSUE TITLE
视频合集页面不显示且无法抵达最后一个分p视频

### ISSUE THREAD

**Issue by d3ara1n** [guozhigq/pilipala#620]
### 问题描述
对于多p或合集视频，在其中一个视频页面中会有合集列表，显示有n个视频，打开列表后之后n-1个项目，缺少最后一个分p。

### 复现步骤
APP打开https://www.bilibili.com/video/BV1qm4y1p7vr  合集列表缺少2_P5

### 预期行为
如官方APP。

### 系统信息
害怕OS，Pilipala 1.0.21

### 相关截图或日志
![Screenshot_2024-03-08-12-51-49-794_com guozhigq p](https://github.com/guozhigq/pilipala/assets/8285337/0aae6e0e-5112-4a1c-b2be-1889c203f3a4)

**Comment by guozhigq** [comment]
最新版已修复
