### ISSUE TITLE
能添加修改默认设置功能吗？

### ISSUE THREAD

**Issue by HMAX-RXF** [guozhigq/pilipala#629]
### 功能描述
请提供对所请求功能的清晰描述。
每次打开视频默认都是最高画质，弹幕关闭，需要手动调节，很麻烦，希望添加修改这些默认设置的功能。
### 目标
请描述你希望通过这个功能实现的目标。
可以通过客户端内的设置永久保存对画质，弹幕开关等的设定。

**Comment by zstd-lzmp** [comment]
这个功能我记得有的啊
点击右上角头像->右上角第二个按键就是设置，你想要的都在播放设置里

不过，这个设置按钮的位置确实有点隐蔽，我刚开始用的时候也没找到
