### ISSUE TITLE
建议增加关闭搜索历史的功能

### ISSUE THREAD

**Issue by zstd-lzmp** [guozhigq/pilipala#631]
### 功能描述
如题

### 目标
在设置->其他设置中增加不记录搜索历史的设置项

**Comment by zstd-lzmp** [comment]
最近我发现bili_you这个同样用flutter第三方客户端是支持关闭搜索历史的
项目地址在这里https://github.com/lucinhu/bili_you/

**Comment by guozhigq** [comment]
最新版已支持
