### ISSUE TITLE
建议能在非全屏播放界面隐藏系统状态栏

### ISSUE THREAD

**Issue by KayStud10** [guozhigq/pilipala#633]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
最新版已支持
