### ISSUE TITLE
收藏夹计数错误

### ISSUE THREAD

**Issue by Catfootbeats** [guozhigq/pilipala#637]
### 问题描述
打开收藏夹，共xx条视频显示的是懒加载列表视频数量，并非实际收藏夹视频数量。

### 复现步骤
打开收藏夹。

### 预期行为
显示收藏夹实际视频数

### 系统信息
Android 10

### 相关截图或日志
![Screenshot_20240314_230023_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/74121308/96988b87-92f8-4304-b00d-f8b52f66cad3)

![Screenshot_20240314_230037_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/74121308/db56e9c4-cf23-4f2f-9b76-4ac07ead826e)

**Comment by guozhigq** [comment]
最新版中已修复，可以试下
