### ISSUE TITLE
直播界面只有九分之一

### ISSUE THREAD

**Issue by ghost** [guozhigq/pilipala#639]
### 问题描述
直播界面太小，约占屏幕1/9

### 复现步骤
我看 @吃饭不着急 直播时发现界面异常小，平时不看直播。

### 预期行为
应该占满屏幕

### 系统信息
Mate20，HOS 3，Pili 1.0.21

### 相关截图或日志
![Screenshot_20240315 pilipala](https://github.com/guozhigq/pilipala/assets/47594662/30631be3-8207-4b74-bf02-4a6a6436e5aa)

**Comment by guozhigq** [comment]
已支持
