### ISSUE TITLE
（UI）在UP主投稿界面的顶部导航栏变色问题

### ISSUE THREAD

**Issue by userwljs** [guozhigq/pilipala#642]
### 问题描述
在 UP 主的“TA 的投稿”界面，滑动时顶部导航栏会突兀地变色（最顶端是纯白，下拉后突然变成主题色）
（TA 的动态界面似乎也有此 BUG）

### 复现步骤
v1.0.21.0306，打开任意 UP 主的“TA 的投稿”界面，滑动投稿列表。

### 预期行为
顶部导航栏保持一个颜色，或添加过渡动画。

### 系统信息
Android 12（HarmonyOS 4）

### 相关截图或日志
截图：
![Screenshot_20240317_095730_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/141301971/bc75b2ac-1a4b-451d-a3a6-cbcf07f35d30)
![Screenshot_20240317_095737_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/141301971/5a88d3cb-63cc-4b31-ad39-1156d9504420)
日志：不适用

**Comment by guozhigq** [comment]
正常现象，flutter中md3的默认UI样式，目前应该不会改这部分
