### ISSUE TITLE
建议添加历史记录数量，和距现在日期天数统计功能

### ISSUE THREAD

**Issue by Nottodaymore** [guozhigq/pilipala#644]
### 功能描述
由于官方把历史纪录设置了每个业务保存上限1200条，保存时间为90天，超过1200条和90天后会自动删除，且不能恢复，之前未看完的记录会找不到。建议增加历史记录数量统计，和距现在日期天数统计功能。

### 目标
达到提醒效果，及时清理不需要的记录，如果能实现把未看完的历史记录的保存时间重置更好。

### 解决方案
官方不知为何要设置这个上限，收藏夹和稍后再看也有上限。

**Comment by guozhigq** [comment]
感觉没啥必要啊，现在的历史记录是分页请求的。
日期天数统计：在没有加载到对应数据之前，是不会知道某条记录即将超过90天的，既然已经加载到了某条记录，距现在日期天数也没必要展示了。
历史记录数量统计：目前接口没有返回总数，所以同上，想知道总数就需要加载分页

<br>

> 把未看完的历史记录的保存时间重置更好

这个要轮询请求接口，太粗暴了

**Comment by BakaJzon** [comment]
那有没有可能搞一个本地的历史记录？不需要与云端同步。
偶尔（比如杀后台，不小心返回首页）但是有个想看的视频没看完~~因为我就是因此而来的~~

~~不过如果有了，可能会有更多人要求 fetch 云端~~
