### ISSUE TITLE
点击相关视频的时候很卡

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#65]
### 问题描述
请提供一个清晰而简明的问题描述。
点击视频下面的相关视频会很卡
### 复现步骤
请提供复现该问题所需的具体步骤。
点击视频下面的相关视频
### 预期行为
请描述你期望的正确行为或结果。
不卡
### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
所有东西都是最新版
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![Screenshot_20230904_085334](https://github.com/guozhigq/pilipala/assets/138294823/bcf1ac36-9db5-4b12-ab5e-bc3c95612e4b)

**Comment by guozhigq** [comment]
页面层级比较深么，比如看了很多视频出现的，还是有时候会出现

**Comment by do02fw** [comment]
第一层就出现了

**Comment by orz12** [comment]
#443
