### ISSUE TITLE
beta36小窗点击全屏后app界面全屏显示灰色

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#650]
### 问题描述
如标题，只显示灰色

### 复现步骤
视频画中画，然后点击全屏按钮

### 预期行为
显示app视频详情页

### 系统信息
Android13，MIUI14.0.20

### 相关截图或日志
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:21:45.007891

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.21-beta.36
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala

---------- ERROR ----------
RangeError (length): Invalid value: Valid value range is empty: 0

------- STACK TRACE -------
#0      WebviewController.webviewInit.<anonymous closure> (package:pilipala/pages/webview/controller.dart)
#1      new AndroidNavigationDelegate.<anonymous closure> (package:webview_flutter_android/src/android_webview_controller.dart:1297)
#2      WebViewClientFlutterApiImpl.onPageStarted (package:webview_flutter_android/src/android_webview_api_impls.dart:706)
#3      WebViewClientFlutterApi.setup.<anonymous closure> (package:webview_flutter_android/src/android_webview.g.dart:1797)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#6      _invoke2 (dart:ui/hooks.dart:344)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#8      _Channel.push (dart:ui/channel_buffers.dart:135)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:722)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:257)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:23:21.625508

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.21-beta.36
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala

---------- ERROR ----------
Bad state: Stream has already been listened to.

------- STACK TRACE -------
#0      _StreamController._subscribe (dart:async/stream_controller.dart:686)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471)
#3      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:130)
#4      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:104)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#8      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3831)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#36     _invoke (dart:ui/hooks.dart:312)
#37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#38     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:23:33.516745

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.21-beta.36
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'int' is not a subtype of type 'String'

------- STACK TRACE -------
#0      Utils.timeFormat (package:pilipala/utils/utils.dart:54)
#1      HistoryItem.build.<anonymous closure>.<anonymous closure> (package:pilipala/pages/history/widgets/item.dart:186)
#2      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:116)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150)
#5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#8      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225)
#9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#12     RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:576)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#15     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#16     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581)
#17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#20     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#21     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808)
#22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#25     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#28     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:310)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#30     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#31     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#33     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#34     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#35     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808)
#36     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
#57     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489)
#58     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#59     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#61     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
#62     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554)
#63     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463)
#64     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#65     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#66     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#67     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#68     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#69     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#70     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#71     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#72     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#73     _invoke (dart:ui/hooks.dart:312)
#74     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#75     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:23:38.778496

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.21-beta.36
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'int' is not a subtype of type 'String'

------- STACK TRACE -------
#0      Utils.timeFormat (package:pilipala/utils/utils.dart:54)
#1      HistoryItem.build.<anonymous closure>.<anonymous closure> (package:pilipala/pages/history/widgets/item.dart:186)
#2      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:116)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150)
#5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#8      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225)
#9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#19     _invoke (dart:ui/hooks.dart:312)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#21     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:23:41.983113

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.21-beta.36
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala

---------- ERROR ----------
type 'int' is not a subtype of type 'String'

------- STACK TRACE -------
#0      Utils.timeFormat (package:pilipala/utils/utils.dart:54)
#1      HistoryItem.build.<anonymous closure>.<anonymous closure> (package:pilipala/pages/history/widgets/item.dart:186)
#2      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:116)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150)
#5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#8      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225)
#9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#19     _invoke (dart:ui/hooks.dart:312)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#21     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-03-24 22:24:27.673402

------- DEVICE INFO -------
id: TKQ1.221114.001
board: thyme
bootloader: unkno

**Comment by duyraven** [comment]
补充：直接打开app也是一样效果，只要视频小窗化后再打开app就会这样

**Comment by guozhigq** [comment]
好的 我看一下

**Comment by guozhigq** [comment]
最新版中已增加，可以试下
