### ISSUE TITLE
最新beta（临时修了灰屏那版）在视频详情页简介上划视频遮挡后切换到评论区再下划视频无法恢复为正常大小

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#654]
### 问题描述
如标题

### 复现步骤
找一个视频进入，简介栏上划查看推荐视频上方视频被遮挡，切换到评论区栏下划无法恢复

### 预期行为
评论区下划时会随着页面滚动视频遮挡会逐渐恢复

### 系统信息
MIUI 14.0.20，Android 13

### 相关截图或日志
![Screenshot_2024-03-26-08-40-50-713_com guozhigq pilipala-edit](https://github.com/guozhigq/pilipala/assets/54952917/e63a6c71-2a3d-4dba-87d3-fb50a1f240f4)
![Screenshot_2024-03-26-08-41-38-390_com guozhigq pilipala-edit](https://github.com/guozhigq/pilipala/assets/54952917/347e0a28-f199-4ae5-979c-dc1cbe81eb43)

**Comment by guozhigq** [comment]
嗯  已知问题。只能切回简介页再下拉还原
错误日志中应该是另一个问题
