### ISSUE TITLE
给个字幕功能

### ISSUE THREAD

**Issue by wkr111** [guozhigq/pilipala#655]
### 功能描述
提供中英文字幕。

### 目标
由于地铁上不能开声音看视频，所以想解决在地铁上看视频的困扰。

### 解决方案
没有。

### 其他
照搬B站的字幕。

**Comment by guozhigq** [comment]
进 https://t.me/PiliPala_Beta 获取最新测试版

**Comment by guozhigq** [comment]
最新版中已增加，可以试下
