### ISSUE TITLE
增加原生通知栏显示

### ISSUE THREAD

**Issue by do02fw** [guozhigq/pilipala#66]
### 功能描述
请提供对所请求功能的清晰描述。
增加原生通知栏显示，比如像音乐通知那种，可以显示进度条和暂停
### 目标
请描述你希望通过这个功能实现的目标。
增加原生通知栏显示，比如像音乐通知那种，可以显示进度条和暂停
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用
系统自带的音乐，哔哩哔哩，YouTube

**Comment by guozhigq** [comment]
这个应该会和后台播放同步开发 #64
