### ISSUE TITLE
操作速度快了点，出现全屏灰色蒙版

### ISSUE THREAD

**Issue by BXM2** [guozhigq/pilipala#672]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: marble
bootloader: unknown
brand: Redmi
device: marble
display: TKQ1.221114.001 test-keys
fingerprint: Redmi/marble/marble:13/TKQ1.221114.001/V14.0.20.0.TMRCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-97157-2fd65-7fcsh-cgsbw
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23049RAD8C
product: marble
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMRCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-05-01
------- 应用信息 -------
environment: release
version: 1.0.21
appName: PiliPala
buildNumber: 1021
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      MemberController.actionRelationMod.<anonymous closure> (package:pilipala/pages/member/controller.dart:86)
#1      SmartDialog.show.<anonymous closure> (package:flutter_smart_dialog/src/smart_dialog.dart:191)
#2      _DialogScopeState.build (package:flutter_smart_dialog/src/widget/helper/dialog_scope.dart:47)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#29     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#49     Compo

![Screenshot_2024-04-05-08-02-35-548_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/118059671/b6588d74-6b19-4d6c-9c78-1ec8b99de4ce)

**Comment by guozhigq** [comment]
试试最新版

**Comment by BXM2** [comment]
Thank you for your reply

发送者BXM<http://bup.netlify.app>
________________________________
