### ISSUE TITLE
退出后重进，双击不能继续播放

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#68]
播放视频时退出应用，然后再打开，视频会暂停播放，此时双击屏幕，视频不会继续播放，需要再双击一次才可以。
希望可以改进，能在重进应用后第一次双击就能继续播放。

**Comment by guozhigq** [comment]
了解，已复现。预计1.0.7解决

**Comment by guozhigq** [comment]
v1.0.7 已修复
