### ISSUE TITLE
合集切换视频无效

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#681]
### 问题描述
如标题，最新14号的beta版本

### 复现步骤
找一个合集视频，切换视频

### 预期行为
跳转到选择的视频

### 系统信息
Miui14.0.20, Android13

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/54952917/8c26cf34-f2a7-47bc-9c5b-f8b06393c3c5

**Comment by guozhigq** [comment]
没有复现。跟 issues #677 一样吗

**Comment by duyraven** [comment]
> 复没有现。跟 issues #677一样吗？

不一样，就是单纯点击后不会跳转了

**Comment by duyraven** [comment]
> 没有复现。跟 issues #677 一样吗

不一样，就是点击后不会跳转了

**Comment by guozhigq** [comment]
> > 没有复现。跟 issues #677 一样吗
> 
> 不一样，就是点击后不会跳转了

看看错误日志

**Comment by duyraven** [comment]
> > > 没有复现。跟 issues #677 一样吗
> > 
> > 
> > 不一样，就是点击后不会跳转了
> 
> 看看错误日志

我全新安装复现出来了，关闭相关视频推荐就会有这个bug

![Screenshot_2024-04-14-13-54-44-542_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/54952917/d844fe5b-e15f-4863-9acf-09754f9977cd)

**Comment by duyraven** [comment]
> > > 没有复现。跟 issues #677 一样吗
> > 
> > 
> > 不一样，就是点击后不会跳转了
> 
> 看看错误日志

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01
------- 应用信息 -------
environment: release
version: 1.0.21
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
好的，了解。
