### ISSUE TITLE
视频推荐有待改进🤔

### ISSUE THREAD

**Issue by plane714** [guozhigq/pilipala#693]
视频推荐已改成app推荐。但是推送的视频，大都不是我爱看的。相比 bili_you/官方客户端 推送的视频流还是有进步空间。个人主观感受bili_you的推送和官方很像。

**Comment by xsfx0313** [comment]
这个只能由bilibili自己改，这都是调用b站自己的推送机制。b站的推送机制本来就很烂，用第三方软件也救不了。开发者他也没法替b站开发推荐算法呀！他只能调用。这个只能盼望b站自己优化了。。。
