### ISSUE TITLE
“我的订阅”点开无任何内容

### ISSUE THREAD

**Issue by fbotp** [guozhigq/pilipala#694]
### 问题描述
“我的订阅”点开无任何内容

### 复现步骤
打开pilipala-媒体库-我的订阅

### 预期行为
展示出我的订阅相关内容，比如订阅的番剧等，但实际一片空白

### 系统信息
MIUI 14.0.15，PiliPala 1.0.12

### 相关截图或日志
![c22290a5cd23289db28d0578938acc9](https://github.com/guozhigq/pilipala/assets/46618620/41260839-71b1-4dad-b5f8-349632ae2718)

### 可能原因
`pilipala/lib/http/user.dart`中的`userSubFolder`方法调用的是`/x/v3/fav/folder/collected/list`接口，但是该接口当前返回值为空
![image](https://github.com/guozhigq/pilipala/assets/46618620/5cfeb681-ad13-44ee-9368-19c164c99199)

**Comment by guozhigq** [comment]
应该有错误日志，复现后看一下？

**Comment by fbotp** [comment]
抱歉，接口没有问题，是我自己的问题，弄混了追番和订阅，再加上该页面一片空白，一度误认为是数据处理错误。当订阅列表为空时，可否给这个页面增加一个新样式或新提醒？非常感谢
