### ISSUE TITLE
27号的测试版，通过浏览器跳转到视频详情页会出现灰屏

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#697]
### 问题描述
如标题

### 复现步骤
在网页版b站打开任意视频，点击打开app会跳转到pilipala的视频详情页但是灰屏

### 预期行为
正确显示

### 相关截图或日志

https://github.com/guozhigq/pilipala/assets/54952917/c2b19055-23aa-4014-bfec-4070c6a7b49f

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01
------- 应用信息 -------
environment: release
version: 1.0.21
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
type 'Null' is not a subtype of type 'String'
------- 错误堆栈 -------
#0      VideoDetailController.onInit (package:pilipala/pages/video/detail/controller.dart:129)
#1      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66)
#2      InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12)
#3      GetInstance._startController (package:get/get_instance/src/get_instance.dart:254)
#4      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:205)
#5      GetInstance.find (package:get/get_instance/src/get_instance.dart:302)
#6      GetInstance.put (package:get/get_instance/src/get_instance.dart:87)
#7      Inst.put (package:get/get_instance/src/extension_instance.dart:89)
#8      _VideoDetailPageState.initState (package:pilipala/pages/video/detail/view.dart:69)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#54     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#73     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#92     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#123    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#126    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#145    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#146    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#147    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#162    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#181    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#186    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#188    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#189    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#194    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#195    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#196    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#197    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#201    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#217    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#218    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#219    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#220    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#225    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#228    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#231    Mult

**Comment by guozhigq** [comment]
👌 了解

**Comment by guozhigq** [comment]
最新版中已修复，可以试下

**Comment by duyraven** [comment]
> 最新版本中已修复，可以试下

我反馈的问题均已修复，非常感谢您的工作🎇
