### ISSUE TITLE
后台播放一段时间后引起的字幕堆积问题

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#698]
### 功能描述
希望能更好解决字幕问题，这会造成严重卡顿和发热

### 解决方案
在重新将应用切换到前台后从当前时间点开始拉取字幕而不是把之前切换到后台后未播放的字幕一块显示

附上截图
![Uploading Screenshot_2024-04-28-19-32-33-611_com.guozhigq.pilipala-edit.jpg…]()

**Comment by duyraven** [comment]
![Screenshot_2024-04-28-19-32-33-611_com guozhigq pilipala-edit](https://github.com/guozhigq/pilipala/assets/54952917/f97a3e7b-0eea-44a9-a82d-3c08d342afd3)
抱歉截图没上传好

**Comment by duyraven** [comment]
是弹幕来着，忘了怎么说一直打成字幕🤣

**Comment by guozhigq** [comment]
试试22版本？

**Comment by guozhigq** [comment]
在最新版 v1.0.23 中修复了，试下
