### ISSUE TITLE
字数较多的评论会在评论详情重复显示

### ISSUE THREAD

**Issue by duyraven** [guozhigq/pilipala#699]
### 问题描述
如题，评论字数少点的不会有这个问题（也不一定，有些我复现这个bug后面再点就不见了）

### 复现步骤
找个视频，找字数多的评论点击进评论详情，可以看到评论重复显示了

### 相关截图或日志
![Screenshot_2024-04-28-20-03-03-311_com guozhigq pilipala-edit](https://github.com/guozhigq/pilipala/assets/54952917/8c504427-6eed-48e4-966c-77f6927982f4)

https://github.com/guozhigq/pilipala/assets/54952917/8564d36f-3ae8-48b9-b5f8-bf905564f8d5

Pilipala错误日志 
 ********************
------- 设备信息 -------
id: TKQ1.221114.001
board: thyme
bootloader: unknown
brand: Xiaomi
device: thyme
display: TKQ1.221114.001 test-keys
fingerprint: Xiaomi/thyme/thyme:13/TKQ1.221114.001/V14.0.20.0.TMACNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-385380-m6tb5-r4th8-4zplw
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2102J2SC
product: thyme
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.20.0.TMACNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01
------- 应用信息 -------
environment: release
version: 1.0.21
appName: PiliPala
buildNumber: 10213
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:67)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guozhigq** [comment]
👌 了解
