### ISSUE TITLE
pilipala v1.0.22 底部导航栏小白条不沉浸

### ISSUE THREAD

**Issue by ericbrownz** [guozhigq/pilipala#704]
### 问题描述
同标题。

### 预期行为
正常沉浸。

### 系统信息
小米14 Android14 HyperOS 1.0.36。

### 相关截图或日志
截图如下。

![Screenshot_2024-05-01-09-00-36-634_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/34184767/2ea7587a-433f-4fa2-bc92-2cf16a56ce93)

**Comment by guozhigq** [comment]
之前21版本正常吗

**Comment by ericbrownz** [comment]
> 之前21版本正常吗

正常的，已用回21

**Comment by guozhigq** [comment]
v1.0.23 已朽骨

**Comment by Goo-Leo** [comment]
> v1.0.23 已修复

1.0.24依然出现

**Comment by ericbrownz** [comment]
全新安装1.0.24不沉浸

**Comment by guozhigq** [comment]
了解

**Comment by ericbrownz** [comment]
1.0.25主页沉浸，但点开视频后又不沉浸，并且只能退出后恢复
@guozhigq

**Comment by ayanoharuka** [comment]
> 1.0.25主页沉浸，但点开视频后又不沉浸，并且只能退出后恢复 @guozhigq

是的，Pixel原生Android15也有这个问题
版本号 15 (AP3A.241105.007)
并且希望适配Android15新的预测返回设计
以及希望适配繁体中文，感谢开发者

![Screenshot_20241118-233645](https://github.com/user-attachments/assets/0eba9f09-3bd4-45b8-a829-c197bac7cc7b)
@guozhigq

**Comment by guozhigq** [comment]
最新版已修复
