### ISSUE TITLE
22版本BUG较多

### ISSUE THREAD

**Issue by hanziteng1996** [guozhigq/pilipala#705]
### 问题描述
请提供一个清晰而简明的问题描述。
偶尔卡死，播放无法正常全屏
### 复现步骤
请提供复现该问题所需的具体步骤。
竖屏视频点击全屏无响应，横屏视频点击全屏后自动横屏后转为竖屏
### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
Mate60 harmony4.2
### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
全屏问题试试这个安装包 https://drive.google.com/file/d/1YZQRQ8ylJ6zRKn55bryAvMnNUx7HV48d/view?usp=sharing

**Comment by guozhigq** [comment]
在最新版 v1.0.23 中修复了
