### ISSUE TITLE
推荐视频增加时长过滤功能

### ISSUE THREAD

**Issue by lf6545** [guozhigq/pilipala#71]
### 功能描述
对推荐的视频列表中的视频时长就行过滤，只显示符合条件的视频，为了忽略掉一些短视频。

### 目标
添加过滤条件后，只显示推荐中符合条件的视频内容

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
感觉不是很必要，目前推荐栏用的是手机端的接口，每次返回10条数据，还要去除一条推广内容，渲染数据过少时，不够一屏可能无法触发分页加载。
可以加上时长显示，由用户自己选择看或者不看。

**Comment by guozhigq** [comment]
已在v1.0.7版本中 推荐栏加入时长显示
