### ISSUE TITLE
1.0.22.0430从浏览器跳转无法正常播放

### ISSUE THREAD

**Issue by y2485871697** [guozhigq/pilipala#713]
当我从浏览器观看b站视频跳转到应用时视频是浅灰色的，上一个版本没有这个bug，并且这个版本必须手动将系统的全屏和视频的全屏一同打开否则会被锁定为竖屏，上一个版本依然没有这个bug

**Comment by guozhigq** [comment]
在最新版 v1.0.23 中修复了
