### ISSUE TITLE
关于【媒体库】页面的调整和优化的相关建议

### ISSUE THREAD

**Issue by HumanMus1c** [guozhigq/pilipala#715]
### 功能描述
请提供对所请求功能的清晰描述。
首先我将账户个人信息【我的】页面与【媒体库】页面进行融合，并且将【媒体库】中的5个条目【我的收藏】【观看历史】【稍后再看】【订阅列表】【下载列表】调整为纵向排列。
![我的](https://github.com/guozhigq/pilipala/assets/46023154/dd5442d8-fabc-43bc-904e-d5e8e24b9ecf)

-------------------------------------------------------

点击进入【我的收藏】页面。可以在【我的收藏】【观看历史】【稍后再看】【订阅列表】【下载列表】之间进行左右切换。

![媒体库](https://github.com/guozhigq/pilipala/assets/46023154/99da6e1c-c739-41ab-a3a2-211d0c247417)

---------------------------------------------------------
点击任意条目，例如进入【默认收藏夹】页面。可以直观看到每个视频的基本信息。

![收藏夹](https://github.com/guozhigq/pilipala/assets/46023154/1e636c4d-ffc8-4113-a920-36cf1f47d22a)

-------------------------------------------------------

### 目标
请描述你希望通过这个功能实现的目标。
【如图】

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
【如图】

### 其他
请提供已实现该功能或类似功能的应用
https://github.com/anandnet/Harmony-Music
[Harmony-Music](https://github.com/anandnet/Harmony-Music)
举例该项目的音乐库条目下也可实现内容的左右切换以及搜索功能。
![SVID_20240504_160140_1_小萌GIF_20240504_160357](https://github.com/guozhigq/pilipala/assets/46023154/01c94b43-f882-4ab7-962e-2a9e13931e7c)

**Comment by guozhigq** [comment]
个人信息跟媒体库合并可行，其他的改动比较大，暂时应该不会改

**Comment by HumanMus1c** [comment]
理解
