### ISSUE TITLE
[BUG反馈]弹幕速度问题

### ISSUE THREAD

**Issue by nlsdt** [guozhigq/pilipala#716]
### 问题描述
在长按视频倍速后，弹幕速度选项失效

### 复现步骤
1.任意选择一个视频
2.将弹幕速度从4s调整为9s
3.播放视频，确认速度已经变慢
4.长按视频3倍速一段时间，发现弹幕也正确三倍速了
**5.在松开结束3倍速，弹幕速度突然变快变成默认速度(4s)或速度保持加速状态不变**
6.打开弹幕设置，发现依然显示为10s，再从新调整后或重启程序，恢复正常

已多次复现，均触发此bug

### 预期行为
恢复此功能的正常实现

可能是在解除弹幕倍速时又重新读取回到默认值?用户设置的参数被覆盖了?

#### 软件版本:
Pilipala     v1.0.22
PilipalaX v1.20+150
#### 操作系统版本:
鸿蒙4 miui14（这个应该不影响吧）

### 出现类似bug的issu: #232 #234 

---
##### ps:希望再修完bug后也帮PilipalaX修一下，我是因为在pilipalaX的使用中发现了这个问题，想来原版看一下是不是已经被修了，发现也能复现这个bug，遇于是就决定在主仓库提issu了。非常感谢各位大佬的开发，麻烦你们了！🙏🙏🙏

**Comment by Joe-8383** [comment]
pilipala无法追更合集，希望增加此功能

**Comment by nlsdt** [comment]
已修复，已close
