### ISSUE TITLE
希望可以实现稍后再看连播功能

### ISSUE THREAD

**Issue by f59375543** [guozhigq/pilipala#722]
### 功能描述
非常感谢作者的无私奉献，希望稍后再看可以播完视频后自动播放下一个

### 目标
稍后再看能够连播

### 解决方案
既然pilipala可以读取稍后再看的列表，那边应该可以按顺序播放下去吧

**Comment by guozhigq** [comment]
最新版已支持

**Comment by f59375543** [comment]
> 最新版已支持

非常感谢！
