### ISSUE TITLE
关闭弹幕的情况下，播放视频，fps无法降到30

### ISSUE THREAD

**Issue by jhf3324** [guozhigq/pilipala#74]
官方关闭弹幕的情况下fps会稳定在30，pilipala的这bug会增加手机不必要的耗电

**Comment by guozhigq** [comment]
播放视频时的帧率主要取决于视频本身的帧率，比如在**1080p60帧**跟**1080p**下播放时，帧率也会不同，前者的帧率将会保持的60FPS上下。
将在v1.0.7中修复
