### ISSUE TITLE
自动退出功能造成系统状态栏错误的进入沉浸模式

### ISSUE THREAD

**Issue by TQHYG** [guozhigq/pilipala#747]
### 问题描述
开启自动退出(播放完成后退出全屏)功能后，在非全屏状态下放完视频后，系统反而进入全屏模式(沉浸模式)

### 复现步骤
开启自动退出功能，播放一个视频直至放完

### 预期行为
放完视频后退出全屏，如果不在全屏状态则不做反应

### 系统信息
小米2，MIUI7.9，安卓5.0.1

### 相关截图或日志
正常状态与错误的进入沉浸模式后的截图
![Screenshot_2024-05-26-08-46-48](https://github.com/guozhigq/pilipala/assets/102199229/9ab0ef6d-2ceb-4be0-944b-ea0143c852b8)
![Screenshot_2024-05-26-08-45-23](https://github.com/guozhigq/pilipala/assets/102199229/86929afd-1593-4cd9-86b0-cd93fb392119)

**Comment by guozhigq** [comment]
最新版已修复
