### ISSUE TITLE
实现扫一扫功能

### ISSUE THREAD

**Issue by ChinaMinecraft24** [guozhigq/pilipala#749]
### 功能描述
请提供对所请求功能的清晰描述。
建议添加扫一扫功能，这个功能就是用来扫描二维码的。
### 目标
请描述你希望通过这个功能实现的目标。
我想他用来扫码登录电视上的Bug video，（一个电视上的第三方哔哩哔哩）他必须要客户端扫码才能登录，希望实现此功能。
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
无
### 其他
请提供已实现该功能或类似功能的应用
哔哩哔哩

**Comment by guozhigq** [comment]
目前无法实现这个
