### ISSUE TITLE
开启PIP播放后，在详情页未播放视频时进入后台也会进入画中画

### ISSUE THREAD

**Issue by Ph0to1211** [guozhigq/pilipala#752]
### 问题描述
如题

### 复现步骤
进入视频详情页后，进入后台

### 预期行为
在进入视频详情页未播放视频时进入后台，不会进入画中画

### 系统信息
v1.0.23.0505
Android 14

### 相关截图或日志
https://github.com/guozhigq/pilipala/assets/171119474/a38236b2-19b2-4030-a293-336e475e75a4

**Comment by guozhigq** [comment]
应该已修复
