### ISSUE TITLE
锁定后退出全屏，无法对视频进行操作

### ISSUE THREAD

**Issue by Ph0to1211** [guozhigq/pilipala#753]
### 问题描述
如题

### 复现步骤
进入全屏后锁定，再退出全屏

### 预期行为
锁定后退出全屏，增加解锁的按钮；或锁定后无法退出全屏

### 系统信息
v1.0.23.0505
Android 14

### 相关截图或日志
https://github.com/guozhigq/pilipala/assets/171119474/fce1ea7d-dcdc-480c-9df5-57547884d1ba

**Comment by guozhigq** [comment]
应该是用手势退出的全屏吧

**Comment by Ph0to1211** [comment]
> 应该是用手势退出的全屏吧

对的
