### ISSUE TITLE
关于无法登录的问题

### ISSUE THREAD

**Issue by Michael-Zyx** [guozhigq/pilipala#758]
### 问题描述
点击登录后界面要么是空白，要么出现人机验证后变成空白，跳转到浏览器中登录后不会跳转回来（这个我猜测是手机系统过老）

### 复现步骤
新手机不一定能复现

### 系统信息
好像是红米note3

### 相关截图或日志
![Screenshot_2024-06-01-21-27-00-896_com.guozhigq.pilipala_101604.png](https://github.com/guozhigq/pilipala/assets/116944782/35c13903-376d-4acb-8bd9-bcf98953ab44)

**Comment by Michael-Zyx** [comment]
补充一下，手机系统是安卓6.0.1

其次观看视频时，手机发烫还是有点严重

目前希望的**改进**是能否添加一个二维码登录的方式，这样不需要网页输密码登录

**Comment by guozhigq** [comment]
> 补充一下，手机系统是安卓6.0.1
> 
> 其次观看视频时，手机发烫还是有点严重
> 
> 目前希望的**改进**是能否添加一个二维码登录的方式，这样不需要网页输密码登录

试试旧版本会有登录的这个问题嘛？

**Comment by Michael-Zyx** [comment]
> > 补充一下，手机系统是安卓6.0.1
> > 
> > 其次观看视频时，手机发烫还是有点严重
> > 
> > 目前希望的**改进**是能否添加一个二维码登录的方式，这样不需要网页输密码登录
> 
> 试试旧版本会有登录的这个问题嘛？

试过的，1.0.22/21/17和1.0.7都试过，一样都是白屏
我觉得最好的**解决方法**就是加一个二维码登录的功能
