### ISSUE TITLE
功能请求：打开 bilibili.com 外部链接

### ISSUE THREAD

**Issue by Charon2050** [guozhigq/pilipala#759]
### 功能描述
使用此 App 打开 bilibili.com/ 链接时，正确跳转至对应视频/动态。

### 目标
朋友之间经常互发 bilibili.com/BVxxxxxx 的链接，虽然可以用此客户端打开链接，但只会打开首页，没有正确跳转至对应视频。希望可以根据 url 地址跳转到正确的视频/动态。

### 其他
B站官方客户端在打开 bilibili.com/ 的链接时，可以正确跳转到对应内容。

**Comment by Charon2050** [comment]
compeleted

**Comment by leij0318** [comment]
对，这个功能应该是目前我觉得最需要开发的，希望作者可以开发出来，以及各种链接跳转问题(建议可以像浏览器一样，设置里搞一个可以跳转外部链接的选项)。

**Comment by guozhigq** [comment]
1.0.25版本已增加

**Comment by leij0318** [comment]
> 1.0.25 版本已增加

我从浏览器打开b站视频，使用pilipala不能正确跳转到视频页面

**Comment by guozhigq** [comment]
> > 1.0.25 版本已增加
> 
> 我从浏览器打开b站视频，使用pilipala不能正确跳转到视频页面

比如哪个链接呢
