### ISSUE TITLE
【功能建议】建议支持TV端，电视端

### ISSUE THREAD

**Issue by lhbdhr** [guozhigq/pilipala#76]
官方的TV端**不支持弹幕**，看视频没那个味儿，人麻了。
而且电视端实在是**没有好用的第三方客户端**。
这个需求真的很强烈。请作者大佬考虑一下。

**Comment by guozhigq** [comment]
TV端BBLL跟BV怎么样呢，
TV端要适配遥控器等等，可能工作量比较大，目前不在开发计划内，开发计划是移动端、Pad端、手表端（可能）...

**Comment by lhbdhr** [comment]
感谢作者的回复，之前没听说过BBLL，尝试了一下，挺满意的。
