### ISSUE TITLE
稍后再看刷新异常

### ISSUE THREAD

**Issue by uilz** [guozhigq/pilipala#767]
### 问题描述
稍后再看不及时刷新

### 复现步骤
在网页端对任意视频点击稍后再看操作后，返回pilipala必须点刷新按钮才能显示新增加的稍后再看内容

### 预期行为
可以自动刷新

### 系统信息
鸿蒙4.0nova9pro
V1.0.23

**Comment by guozhigq** [comment]
重新进一下页面
