### ISSUE TITLE
可以在linux上使用吗，尝试编译报错。

### ISSUE THREAD

**Issue by kero990** [guozhigq/pilipala#77]
看到有linux项目文件夹，尝试在linux上编译报错。

```
lib/pages/preview/view.dart:146:19: Error: No named parameter with the name 'preloadPagesCount'.
[        ] [   +1 ms]                   preloadPagesCount: 2,
[        ] [        ]                   ^^^^^^^^^^^^^^^^^

```

**Comment by guozhigq** [comment]
可能是flutter版本不一致导致的，  我电脑上是3.10.6

**Comment by KudouKaito** [comment]
确实是版本问题，flutter 3.13.0之后，extended_image删除了preloadPagesCount，[extended_image 8.1.0 changelog](https://pub.dev/packages/extended_image/changelog)。  
如果要用3.13.0版本的flutter，extended_image需要用8.1.0之后的版本（目前最新是8.1.1），并且需要根据extended_image官方给出来的案例（[应该是这个] (https://github.com/fluttercandies/extended_image/blob/d255cc2465d83b50719d5b90eb1120e47d2bcde6/example/lib/pages/simple/simple_photo_view_demo.dart)）来修改代码。  
我看着History主要是把preloadPagesCount删了，然后在onPageChanged里面加`_preloadImage(index - 1); _preloadImage(index + 1);`    
修改之后应该是这样
```flutter
                 onPageChanged: (int index) {
                   _previewController.onChange(index);
                   _preloadImage(index - 1);
                   _preloadImage(index + 1);
                 },
```
_preloadImage方法如下
```flutter
  final List<int> _cachedIndexes = <int>[];
  void _preloadImage(int index) {
    if (_cachedIndexes.contains(index)) {
      return;
    }
    if (0 <= index && index < widget.imgList!.length) {
      final String url = widget.imgList![index];
      if (url.startsWith('https:')) {
        precacheImage(ExtendedNetworkImageProvider(url, cache: true), context);
      }

      _cachedIndexes.add(index);
    }
  }
```
我改了之后能运行，但是不知道对不对
