### ISSUE TITLE
无法新增收藏夹，无法私信Up主

### ISSUE THREAD

**Issue by LiuliuYen** [guozhigq/pilipala#771]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
1.0.24版本会增加私信功能，可以进tg群下载beta版
新增收藏夹功能可以开发，但是不能确保上线时间

**Comment by guozhigq** [comment]
1.0.25版本已增加
