### ISSUE TITLE
求更新支持安卓4.4

### ISSUE THREAD

**Issue by hoojw99** [guozhigq/pilipala#772]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
播放器插件应该是无法支持到4.4的
