### ISSUE TITLE
cc字幕行为异常

### ISSUE THREAD

**Issue by bilebee** [guozhigq/pilipala#775]
### 问题描述
视频拥有多集时，切换分集后无论哪一集视频的cc字幕都是第一集的

### 复现步骤
任意具有多集和多个字幕的视频打开cc字幕显示，在视频页内切换分集到非第一集

### 预期行为
显示当前集视频的cc字幕

### 系统信息
系统版本安卓13，设备努比亚z50u

### 相关截图或日志
![Screenshot_20240613_090358](https://github.com/guozhigq/pilipala/assets/66149991/9e8770b3-b74f-4837-afba-e587390e868e)

**Comment by bilebee** [comment]
补充说明：切换分集才会触发该问题，如果从视频链接进入字幕是正确的，但是如果在该视频页内切换分集就会出现问题
![Screenshot_20240613_090810](https://github.com/guozhigq/pilipala/assets/66149991/d1dc6d62-38d1-4ecb-90a5-5489c8bc31ac)

**Comment by guozhigq** [comment]
了解

**Comment by 759108203** [comment]
这个问题在最新的1.0.25版本依然存在，CC字幕功能非常重要，辛苦大大提高优先级尽快修复，谢谢！比心

**Comment by 759108203** [comment]
@guozhigq

**Comment by 759108203** [comment]
不对，准确的说在1.0.25版本现象和当前问题有所不同，我想反馈的问题是：
播放一个视频 → 打开CC字幕 → 字幕正常 → 关闭视频，再打开另外一个视频 → 打开CC字幕 → 展示的字幕和视频播放的音频没有关系（也不是第一个视频的音频字幕），感觉跟其他无关的视频“串台”了
@guozhigq 大大辛苦处理下哈

**Comment by guozhigq** [comment]
应该已修复
