### ISSUE TITLE
弹幕显示数量少于实际数量

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#78]
弹幕显示区域开的是满屏，不透明度调低了一些。
下面是同一个视频片段的截图对比：
pilipala：
![Screenshot_20230908_233606_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/106989902/ada87082-2d3a-41ef-9856-ffcfec90d1bc)
另一个第三方客户端：
![Screenshot_20230908_233548_com a10miaomiao bilimiao](https://github.com/guozhigq/pilipala/assets/106989902/87a80cac-33c0-47a4-8d3b-ca9afd30d151)
官网（手机）：
![Screenshot_20230908_234233_mark via](https://github.com/guozhigq/pilipala/assets/106989902/4077df75-4f46-4ea2-bf68-e5538bc6a201)
官网（手机，但是是电脑模式）：
![Screenshot_20230908_234316_mark via](https://github.com/guozhigq/pilipala/assets/106989902/d2e43d1b-791a-492e-90b9-3d2d87d3cdaa)

**Comment by guozhigq** [comment]
确实，我看了一下请求返回的数据只有70条，web端接口返回的是143条，应该是这个导致的吧

**Comment by wanzh5** [comment]
那这个可以修复吗？

**Comment by guozhigq** [comment]
尝试修复中 💪
