### ISSUE TITLE
希望在消息界面中能查看评论回复

### ISSUE THREAD

**Issue by EZ118** [guozhigq/pilipala#781]
### 功能描述
希望在消息界面中能查看评论回复

### 目标
能在点进消息界面后，列表的第一项能加入一个查看视频评论回复的入口，点进去就能查看列表

### 解决方案
找到了一个可用的接口: 
https://api.bilibili.com/x/msgfeed/reply?platform=web&build=0&mobi_app=web&ps=40

**Comment by guozhigq** [comment]
目前bata版已支持，可以进tg群试用

**Comment by EZ118** [comment]
ok,谢谢！
