### ISSUE TITLE
首页内容经常加载不出内容（首页推荐类型为app端）

### ISSUE THREAD

**Issue by imzoet** [guozhigq/pilipala#795]
### 问题描述
首页内容经常加载不出内容（首页推荐类型为app端），如截图所示，但是反复点击重试后，可以刷出推荐视频

### 复现步骤
首页推荐类型为app端，打开App即可浮现

### 预期行为
正常显示推荐视频

### 系统信息
OS：Android 14，APP：V 1.0.23

### 相关截图或日志
![Screenshot_2024-07-03-11-16-38-352_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/48322052/a0e59d0b-770c-4e8e-baa2-27ca8ade2be9)

**Comment by guozhigq** [comment]
再遇到的话，可以贴一下错误日志～

**Comment by imzoet** [comment]
![Screenshot_2024-07-08-08-58-16-807_com guozhigq pilipala](https://github.com/guozhigq/pilipala/assets/48322052/1ae1b641-dc3c-483c-8e51-ae43c244dff0)
日志显示为空

**Comment by guozhigq** [comment]
试试这个。https://drive.google.com/file/d/1plcpQdK3Vefd_GLLQpNHoTqfYAkSfdDL/view?usp=sharing   覆盖安装就可以

**Comment by imzoet** [comment]
截至目前，再未出现相关异常

**Comment by guozhigq** [comment]
最新版已修复
