### ISSUE TITLE
Google Pixel6pro 无法全屏

### ISSUE THREAD

**Issue by GaaJon** [guozhigq/pilipala#80]
### 问题描述
横屏无法全屏

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
Google Pixel6pro Android13。

### 相关截图或日志
![Uploading Screenshot_20230909-010725.png…]()

**Comment by guozhigq** [comment]
无法全屏还是全屏时画面无法铺满可视区域呢

**Comment by GaaJon** [comment]
> 

全屏画面无法铺满可视区域，也就是无法铺满状态栏
![Screenshot_20230909-222336](https://github.com/guozhigq/pilipala/assets/144479503/f5edca77-d04d-4ff3-acd4-2b02541d0d97)
