### ISSUE TITLE
消息功能->收到的赞 里面内容部分有误

### ISSUE THREAD

**Issue by kimi996z** [guozhigq/pilipala#803]
### 问题描述
消息功能->收到的赞 里面内容部分有误

### 复现步骤
![bug](https://github.com/guozhigq/pilipala/assets/65033442/176b5344-246d-4ae5-b1b5-67a472f30644)

### 预期行为
![1720677877093](https://github.com/guozhigq/pilipala/assets/65033442/52752303-f94d-4ce5-9557-a6baa7fbe1c7)

### 系统信息
pilipala v1.0.24

### 相关截图或日志
见上文。

**Comment by winix365** [comment]
图片传反了😂，pc版是预期的正确表现

**Comment by guozhigq** [comment]
了解

**Comment by cnstruggler** [comment]
> 了解

另外，我发现给我的评论点赞的用户最多也就显示5个。请问能够改进一下，使得我们能查看全部点赞用户吗？

**Comment by guozhigq** [comment]
1.0.25版本已修复
