### ISSUE TITLE
投币 Toast 未重置

### ISSUE THREAD

**Issue by Nyayurn** [guozhigq/pilipala#804]
### 问题描述
在看一个合集时，一个视频投币后通过合集选集切换视频，投币菜单并未重置，且再次点击已经选中的 item 无法投币

### 复现步骤
如上

### 预期行为
弹出投币 Toast 时状态应该重置

### 系统信息
Redmi Note 12 Turbo, Hyper OS 1.0.2.0

### 相关截图或日志
![Screenshot_2024-07-12-00-26-20-418_com.guozhigq.pilipala.jpg](https://github.com/guozhigq/pilipala/assets/132195516/268c21a9-6039-47a2-9bfa-2861d13b57a5)

**Comment by guozhigq** [comment]
好的2024年7月12日 00:31，Yurn ***@***.***>写道：
Assigned #804 to @guozhigq.

**Comment by guozhigq** [comment]
1.0.25版本已修复
