### ISSUE TITLE
ai总结为什么有些视频能用有些不能用什么时候能修复一下或者给一个更换大模型的选项

### ISSUE THREAD

**Issue by ijqn** [guozhigq/pilipala#809]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by VillagerTom** [comment]
AI总结是调用的B站API，有的视频没有因为叔叔没那么多钱。

**Comment by guozhigq** [comment]
对的，这个是官方的功能。
如果有什么第三方支持的，可以推荐一下
