### ISSUE TITLE
历史记录记忆进度继续播放问题

### ISSUE THREAD

**Issue by Nottodaymore** [guozhigq/pilipala#81]
### 问题描述
1.播放完成后，历史记录里并不能显示为已看完，记忆进度与总时长会差1秒，需要反复继续播放，才会显示已看完。biliyou也有这个问题。
2.从历史记录进行继续播放时，偶尔会音画不同步，画面会从头开始倍速播放。这个错误出现较少，不好复现。附：刚又发现弹幕时间轴也乱了一会儿，显示了上一个播放视频的弹幕。
以上是关闭“进入详情页自动播放”出现的，怀疑与此设置有关。安卓1.07版本

### 预期行为
习惯把历史记录作为稍后再看功能使用，不显示已看完，有些强迫症。另外建议增加“删除已看完的历史记录”的功能。

**Comment by Nottodaymore** [comment]
安卓1.075版

**Comment by guozhigq** [comment]
1. 我这里没出现，之后出现的话我看看
2. 同样。。。
3. 目前官方没有「删除已看完的历史记录」的功能跟接口，倒是也可以实现，不过是对已请求回来的数据进行操作。比如页面中只有20条数据，则只清空这20条内已看完的，如果10条则清空这10条内已看完的，并且需要多次请求接口。v1.0.8 或者v1.0.9添加该功能
