### ISSUE TITLE
把充电专属筛选一下把次次都要找一下我有时想只看充电专属

### ISSUE THREAD

**Issue by ijqn** [guozhigq/pilipala#813]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
目前官方好像这个分类的请求吧

**Comment by guozhigq** [comment]
看了一下，有这个分类，我看看吧

**Comment by guozhigq** [comment]
1.0.25版本已增加
