### ISSUE TITLE
增加屏蔽已拉黑用户视频的功能

### ISSUE THREAD

**Issue by dianxindianxindian** [guozhigq/pilipala#817]
### 功能描述
在使用推荐视频和搜索功能时，我发现有时候系统会推荐或搜索到一些我已拉黑用户发布的视频。这不仅影响了我浏览体验的连贯性，也让我感到有些不便。

### 目标
为了提升用户体验，我建议在应用中增加一个功能，允许用户在推荐视频和搜索结果中屏蔽那些已经拉黑的用户所发布的视频。具体来说，这个功能可以：

自动识别用户黑名单中的用户ID或用户名。
在推荐算法中排除这些用户的视频内容。
在搜索结果中提供过滤选项，让用户可以选择是否屏蔽这些用户的视频。

### 解决方案
本人比较菜不知道具体怎么做，方不方便实现

### 其他
请提供已实现该功能或类似功能的应用

**Comment by dianxindianxindian** [comment]
这个功能好像已经有了，打扰了

**Comment by dianxindianxindian** [comment]
虽然现在说有“屏蔽黑名单内用户视频”，但是我今天还是在“推荐”中 发现了一个已经被拉黑了的用户发出的视频。希望查看下现有“屏蔽黑名单内用户视频”在推荐和搜索时，是否可以屏蔽黑名单内用户所发出的视频

**Comment by guozhigq** [comment]
> 虽然现在说有“屏蔽黑名单内用户视频”，但是我今天还是在“推荐”中 发现了一个已经被拉黑了的用户发出的视频。希望查看下现有“屏蔽黑名单内用户视频”在推荐和搜索时，是否可以屏蔽黑名单内用户所发出的视频

需要进一下黑名单页面，多刷新几页数据。才会对对应数据过滤
