### ISSUE TITLE
安卓小白条适配！！

### ISSUE THREAD

**Issue by cadetcarrington** [guozhigq/pilipala#820]
### 功能描述
适配安卓小白条
### 目标
和之前的版本一样可以小白条沉浸

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
release 24跟23版本对比吗

**Comment by cadetcarrington** [comment]
和22比哦

**Comment by cadetcarrington** [comment]
> release 24跟23版本对比吗还是我下的版本不对呢

**Comment by guozhigq** [comment]
好的，我看一下

**Comment by cadetcarrington** [comment]
和22比哦最新开发版已解决

**Comment by guozhigq** [comment]
最新版已修复
