### ISSUE TITLE
视频合集无法正常显示

### ISSUE THREAD

**Issue by Nyayurin** [guozhigq/pilipala#828]
### 问题描述
任何一个up下拉找到视频合集，点进去，同 #805 一样显示为灰色

### 复现步骤
↑

### 预期行为
正常显示

### 系统信息
与 #805 一致

### 相关截图或日志
![Screenshot_2024-07-29-12-20-42-317_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/6193fb45-2f34-4c4b-a272-fe5b086f88dd)
Pilipala错误日志 
 ********************
------- 设备信息 -------
id: UKQ1.230804.001
board: marble
bootloader: unknown
brand: Redmi
device: marble
display: UKQ1.230804.001 release-keys
fingerprint: Redmi/marble/marble:14/UKQ1.230804.001/V816.0.2.0.UMRCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-543686-0c38x-smsh5-77cjj
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23049RAD8C
product: marble
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.2.0.UMRCNXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-01-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala
---------- 错误信息 ----------
FormatException: Invalid radix-10 number (at character 1)
null
^
------- 错误堆栈 -------
Line0      int._handleFormatError (dart:core-patch/integers_patch.dart:126)
Line1      int._parseRadix (dart:core-patch/integers_patch.dart:137)
Line2      int._parse (dart:core-patch/integers_patch.dart:98)
Line3      int.parse (dart:core-patch/integers_patch.dart:60)
Line4      MemberSeasonsController.onInit (package:pilipala/pages/member_seasons/controller.dart:20)
Line5      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66)
Line6      InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12)
Line7      GetInstance._startController (package:get/get_instance/src/get_instance.dart:254)
Line8      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:205)
Line9      GetInstance.find (package:get/get_instance/src/get_instance.dart:302)
Line10     GetInstance.put (package:get/get_instance/src/get_instance.dart:87)
Line11     Inst.put (package:get/get_instance/src/extension_instance.dart:89)
Line12     new _MemberSeasonsPageState (package:pilipala/pages/member_seasons/view.dart:17)
Line13     MemberSeasonsPage.createState (package:pilipala/pages/member_seasons/view.dart:12)
Line14     new StatefulElement (package:flutter/src/widgets/framework.dart:5564)
Line15     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:776)
Line16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4330)
Line17     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line20     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line26     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line29     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line32     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line35     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line40     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line43     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line51     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line54     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line57     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line62     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line65     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line70     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line73     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line76     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line81     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line82     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line84     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line87     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line92     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line95     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line100    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line106    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line109    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line111    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line114    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line117    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line119    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line123    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line124    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line126    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line128    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line129    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line131    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line134    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line136    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line140    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line142    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line146    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line149    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line151    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line154    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line156    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line160    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line162    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line166    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line167    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line169    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line171    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line175    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line177    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line179    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line181    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line184    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line189    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line191    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line192    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line194    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line197    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line199    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line200    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line202    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line203    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line204    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line205    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line206    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
Line207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line208    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line210    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line214    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line216    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line220    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line222    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line223    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line225    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line226    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line228    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line230    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line231    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line232    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
Line233    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
Line234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
Line235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
Line236    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893)
Line237    Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
Line238    Element.updateChildren (package:flutter/src/widgets/framework.dart:4033)
Line239    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
Line240    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line242    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line243    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line244    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line245    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line247    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line248    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line249    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line251    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line252    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line253    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
Line254    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line257    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line258    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line259    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line261    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line262    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line263    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
Line264    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line266    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line267    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line268    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line269    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line270    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line271    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line272    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line273    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
Line274    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line275    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line276    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line277    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
Line278    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line280    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line281    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line282    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line283    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line284    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line285    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
Line286    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
Line287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
Line288    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
Line289    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
Line290    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
Line291    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
Line292    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
Line293    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
Line294    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
Line295    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
Line296    _invoke (dart:ui/hooks.dart:312)
Line297    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
Line298    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by xuangeyouneihan** [comment]
你去看看最新的beta版？是不是已经修了？https://t.me/PiliPala_Beta

**Comment by Nyayurn** [comment]
> 你去看看最新的beta版？是不是已经修了？https://t.me/PiliPala_Beta

并没有，tg群里最新的依然有这个问题

**Comment by xuangeyouneihan** [comment]
这回我也遇到了，比较离谱的是有的up主不会出现这种情况但有的up主就会。我这没出现这种情况的是芳斯塔芙、车祸警示录、梗指南这些，出现了的是世界大抬杠，清缓存也没用😂

**Comment by guozhigq** [comment]
两种合集的类型不一样 需要另外开发

**Comment by guozhigq** [comment]
最新版已修复
