### ISSUE TITLE
动态界面，关注的up主发的文字动态看不见文字，图片和文字一起发只能看见图片

### ISSUE THREAD

**Issue by Weirdo-1224** [guozhigq/pilipala#83]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
哪个up呢
