### ISSUE TITLE
会加入直播间的弹幕功能吗

### ISSUE THREAD

**Issue by xpxxy** [guozhigq/pilipala#843]
### 功能描述
请提供对所请求功能的清晰描述。

当前直播间只有一个背景图没有弹幕

### 目标
请描述你希望通过这个功能实现的目标。

能否添加弹幕功能

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

之前有个类似大屏版本的BBLL有直播的弹幕，pilipala会考虑加入类似功能吗？

**Comment by guozhigq** [comment]
1.0.25版本已增加
