### ISSUE TITLE
评论区展示异常

### ISSUE THREAD

**Issue by PRO-2684** [guozhigq/pilipala#855]
### 问题描述
评论区展示异常

### 复现步骤
打开软件，访问 BV1DH4y1c7fK, 往下翻评论区

### 系统信息
- Android 14, HyperOS 1.0.2.0.UKACNXM
- Pilipala 1.0.24

### 相关截图或日志
![Screenshot_2024-08-10-14-43-16-982_com guozhigq pilipala](https://github.com/user-attachments/assets/f9f9984a-4511-4a6a-8add-1e6cb3197a6e)

**Comment by guozhigq** [comment]
本地没复现，可能是什么时候修复了吧
