### ISSUE TITLE
评论最热和最新异常

### ISSUE THREAD

**Issue by KENDGEN** [guozhigq/pilipala#856]
### 问题描述
最新和最热并没有改变

### 复现步骤
所有视频评论区

### 预期行为
修复

### 系统信息
MIUI 14.0.25
14.0.25.0(TMKCNXM)
Android 版本 13
应用版本1.0.24
### 相关截图或日志
![IMG_20240811_073332](https://github.com/user-attachments/assets/83f63c9c-9a0c-4e2b-92b8-323c6599d2a0)

**Comment by guozhigq** [comment]
嗯 应该是接口出了一些问题

**Comment by guozhigq** [comment]
最新版已修复
