### ISSUE TITLE
“媒体库”中的“收藏夹”中点击图片会显示灰屏，必须点击“收藏夹”三个字再点击图片才能显示

### ISSUE THREAD

**Issue by wuguimeimu** [guozhigq/pilipala#857]
### 问题描述
“媒体库”中的“收藏夹”中点击图片会显示灰屏

### 复现步骤
点击媒体库，再点“收藏夹”中的一个图片会灰屏

### 预期行为
我想要作者修复这个问题

###系统与机型
Redmi Note 8 Pro 6+128GB
MIUI 12.5

https://github.com/user-attachments/assets/d94ef273-a8ae-4a72-8c1b-350cdb253279

**Comment by unohara-fuukei** [comment]
是的，在安卓10里遇到了相同的问题。

**Comment by guozhigq** [comment]
不好意思 忘了回复了。 可以进tg使用最新测试版

**Comment by unohara-fuukei** [comment]
谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: guozhigq ***@***.***>
发送时间: Thursday, August 29, 2024 11:17:16 PM
收件人: guozhigq/pilipala ***@***.***>
抄送: Charlie.X ***@***.***>; Comment ***@***.***>
主题: Re: [guozhigq/pilipala] “媒体库”中的“收藏夹”中点击图片会显示灰屏，必须点击“收藏夹”三个字再点击图片才能显示 (Issue #857)


不好意思 忘了回复了。 可以进tg使用最新测试版

―
