### ISSUE TITLE
关闭相关视频推荐时，无法在合集中切换

### ISSUE THREAD

**Issue by Smart-SangGe** [guozhigq/pilipala#875]
### 问题描述
在关闭相关视频推荐后，合集视频不可以选集了

### 复现步骤
在设置中关闭相关视频推荐，进入一个合集视频进行选集

### 预期行为
可以正常切换选集

### 系统信息
红米k40pro，hyperos1.0.1.0，pilipala1.0.22

**Comment by guozhigq** [comment]
ok

**Comment by guozhigq** [comment]
没有复现，是全屏时还是半屏时呢？目前的最新版本是1.0.24

**Comment by Smart-SangGe** [comment]
那可能新版本修复了，我用的是fdroid下载的，版本没有更新。
