### ISSUE TITLE
希望能在历史记录里添加最近观看的直播

### ISSUE THREAD

**Issue by dcb774** [guozhigq/pilipala#901]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
目前是有的

**Comment by dcb774** [comment]
> 目前是有的

那这个要在哪里找到呢 观看记录里我发现没有

**Comment by guozhigq** [comment]
你指的是在pili里看的直播，在历史记录中没有吗

**Comment by dcb774** [comment]
> 你指的是在pili里看的直播，在历史记录中没有吗

是的 历史记录只有视频 没有直播间 我需要用其他方式观看直播才能留下历史记录吗

**Comment by guozhigq** [comment]
目前直播的记录有问题，需要改一下

**Comment by guozhigq** [comment]
1.0.25版本已增加
