### ISSUE TITLE
在动态页标识充电视频

### ISSUE THREAD

**Issue by realSilasYang** [guozhigq/pilipala#905]
现在得点进去看才知道是充电

**Comment by guozhigq** [comment]
比如 谁的动态呢

**Comment by cnstruggler** [comment]
> 比如 谁的动态呢

我来举例子！比如【思维实验室】（https://space.bilibili.com/14583962）、【世界见闻录】（https://space.bilibili.com/316627722）、【不严肃问题研究室】（https://space.bilibili.com/522262428）的动态！
![IMG_20240909_004630.jpg](https://github.com/user-attachments/assets/5cb64223-d362-471c-995f-bd6b341cc12b)

![Screenshot_20240909-004645.jpg](https://github.com/user-attachments/assets/52624dd5-1e97-47e4-81c3-07228c7d9439)

![Screenshot_20240909-004712.jpg](https://github.com/user-attachments/assets/87b21a6a-b6c7-494b-a384-56348ae49dbf)

![IMG_20240909_004537.jpg](https://github.com/user-attachments/assets/4aae02bb-ac2b-4307-bf39-bc659869921b)

![Screenshot_20240909-004552.jpg](https://github.com/user-attachments/assets/3c774f51-45b9-4095-9169-e96c0d854d33)

![IMG_20240909_004454.jpg](https://github.com/user-attachments/assets/9c912c8d-ddbe-4d36-9277-59ff4da62795)

![Screenshot_20240909-004503.jpg](https://github.com/user-attachments/assets/84cfd5c5-6440-4cc0-94db-531879d68f93)

![Screenshot_20240909-004712.jpg](https://github.com/user-attachments/assets/5886efec-9149-4e0a-b640-15e6ac38038c)

**Comment by realSilasYang** [comment]
> > 比如 谁的动态呢
> 
> 我来举例子！比如【思维实验室】（[https://space.bilibili.com/14583962）、【世界见闻录】（https://space.bilibili.com/316627722）、【不严肃问题研究室】（https://space.bilibili.com/522262428）的动态！](https://space.bilibili.com/14583962%EF%BC%89%E3%80%81%E3%80%90%E4%B8%96%E7%95%8C%E8%A7%81%E9%97%BB%E5%BD%95%E3%80%91%EF%BC%88https://space.bilibili.com/316627722%EF%BC%89%E3%80%81%E3%80%90%E4%B8%8D%E4%B8%A5%E8%82%83%E9%97%AE%E9%A2%98%E7%A0%94%E7%A9%B6%E5%AE%A4%E3%80%91%EF%BC%88https://space.bilibili.com/522262428%EF%BC%89%E7%9A%84%E5%8A%A8%E6%80%81%EF%BC%81) ![IMG_20240909_004630.jpg](https://private-user-images.githubusercontent.com/180667263/365453561-5cb64223-d362-471c-995f-bd6b341cc12b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNTYxLTVjYjY0MjIzLWQzNjItNDcxYy05OTVmLWJkNmIzNDFjYzEyYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTRhZDJiODc5ZmFhMjczOWVhMzI5OGM2MmViNzE0N2Q0Yjk2OWIwYzMwOGJjNDg1NWUxZGNkNmI2ZmRlNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uay0p2aNQmRYV6gJNJ2ueZX6OXoGzEmO62bynB4zFaY)
> 
> ![Screenshot_20240909-004645.jpg](https://private-user-images.githubusercontent.com/180667263/365453569-52624dd5-1e97-47e4-81c3-07228c7d9439.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNTY5LTUyNjI0ZGQ1LTFlOTctNDdlNC04MWMzLTA3MjI4YzdkOTQzOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTFjM2E4OGU2Y2FmMWFlZmM4MzkwYTU0Y2U0NDA4Y2Q1OTcyYzc1OTQ5Yzc1MjE1ZDQ4NTVjZjg0NjgwNmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYbJ4pR788MdeEbaVb6CbsPeByQGKjR8lT7ZvK9GYVI)
> 
> ![Screenshot_20240909-004712.jpg](https://private-user-images.githubusercontent.com/180667263/365453577-87b21a6a-b6c7-494b-a384-56348ae49dbf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNTc3LTg3YjIxYTZhLWI2YzctNDk0Yi1hMzg0LTU2MzQ4YWU0OWRiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzBiNDMzMTYzYjNlZmQwZDQ5ZGU2Yjk4YzM0OGJjNGVhMzMyZjg2NWRhNmQ1Njg4MzdmYTMwMmMxZjRiNjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwUqK2EbnxR0bn9BT59PgkRXBuI29JopfPIeV1QJSKQ)
> 
> ![IMG_20240909_004537.jpg](https://private-user-images.githubusercontent.com/180667263/365453587-4aae02bb-ac2b-4307-bf39-bc659869921b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNTg3LTRhYWUwMmJiLWFjMmItNDMwNy1iZjM5LWJjNjU5ODY5OTIxYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2EwYmVkMjA4YWYxMmFkMjFjNjBkYjgzZjNiYjFlY2JlZmY4ZDljNzViYWQ2OTQwYzE3NDdjNDU5YjRlNjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._4Ee5uC-q5MuwpNyy8LaTCYjdXscyuIV1bn20-24ei8)
> 
> ![Screenshot_20240909-004552.jpg](https://private-user-images.githubusercontent.com/180667263/365453594-3c774f51-45b9-4095-9169-e96c0d854d33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNTk0LTNjNzc0ZjUxLTQ1YjktNDA5NS05MTY5LWU5NmMwZDg1NGQzMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTg3NzUyMWM3NTAwMTc5MGM2ZmNkYWJhYzRlZTY4NTA1ODEyYzNmNmY3YzBjY2UwZjEzYTk3MzYzYjY4NTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3QFrmywHmDtiz8MJB4yxh4B0o6Ks3QwEwBNyTnHJAzw)
> 
> ![IMG_20240909_004454.jpg](https://private-user-images.githubusercontent.com/180667263/365453608-9c912c8d-ddbe-4d36-9277-59ff4da62795.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNjA4LTljOTEyYzhkLWRkYmUtNGQzNi05Mjc3LTU5ZmY0ZGE2Mjc5NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWU2ZjAxNDVlNDg4MGZlYWRiNDkzNDQ3MjcyODEzYjNiMjUxZmUwYzQ5OWY4ZmVhOGEyMzdjZmI2NmRkZjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wqd9dtOl11efDUF78EiIAlXkzzYuS78xCrl1wQj_5Uc)
> 
> ![Screenshot_20240909-004503.jpg](https://private-user-images.githubusercontent.com/180667263/365453621-84cfd5c5-6440-4cc0-94db-531879d68f93.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNjIxLTg0Y2ZkNWM1LTY0NDAtNGNjMC05NGRiLTUzMTg3OWQ2OGY5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTY1NWM5Y2JjODIwZTIzOTg0NTk5NjQwYzhmMTYxMzlmY2Q5MWNiMzIyOGUyZTE3YWRlMmVhOWE2NGUwNDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gER1WHXMHmm1mpMiUdMxEmNfx-DGZmfEXuJbeklsKGA)
> 
> ![Screenshot_20240909-004712.jpg](https://private-user-images.githubusercontent.com/180667263/365453673-5886efec-9149-4e0a-b640-15e6ac38038c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTQ1NjgsIm5iZiI6MTcyNTgxNDI2OCwicGF0aCI6Ii8xODA2NjcyNjMvMzY1NDUzNjczLTU4ODZlZmVjLTkxNDktNGUwYS1iNjQwLTE1ZTZhYzM4MDM4Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNjUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWUyMGFkNDdkZWVjMDZhNWU1Y2I3Yzk4ZWFkNjUwZjcxYTRlMjZlZTdlYmM2YWJiY2ExNzE2MjBmYzlhYzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mhmYOBCfqCTylOOVeTAZc2OGlpPom0WwYFXTBOXIJyA)

是滴！谢谢！

**Comment by guozhigq** [comment]
ok

**Comment by guozhigq** [comment]
v1.0.25版本已增加
