### ISSUE TITLE
点进去一个视频后，先进入UP主页等其他页面，再回来播放视频时，视频有声没有画。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#911]
### 问题描述
点进去一个视频后，先进入UP主页等其他页面，再回来播放视频时，视频有声没有画，而且连进度条都没有；如果点进去直接播放，则没有这种问题。

### 复现步骤
https://github.com/user-attachments/assets/d39ab5e6-2a88-422b-aaaf-f8a568fff774

### 预期行为
点进去一个视频后，先进入UP主页等其他页面，再回来播放视频时，视频正常播放。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
已提供录屏。

**Comment by guozhigq** [comment]
可以先打开视频自动播放临时解决
