### ISSUE TITLE
搜索结果Emoji表情显示异常。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#913]
### 问题描述
搜索结果视频标题Emoji表情显示为“?”，但是在稍后再看列表、收藏夹列表、合集列表中显示正常。

### 复现步骤
搜索框中输入BV1wy4y1W7WS（不是我的作品），把打开后的视频收藏并添加稍后再看并到收藏夹、稍后再看列表里查看视频标题，然后打开视频所在的合集。
你会发现![IMG_20240907_145005.jpg](https://github.com/user-attachments/assets/38532309-861b-4108-a8a8-25801d371c21)

![IMG_20240907_145110.jpg](https://github.com/user-attachments/assets/bde2ec3c-154e-46ab-897c-c11d1dc9170f)

![IMG_20240907_145129.jpg](https://github.com/user-attachments/assets/ef262509-3531-4804-bcc8-c0d26cd91935)

![IMG_20240907_145439.jpg](https://github.com/user-attachments/assets/6b11789d-b2b9-4321-8014-f6e8871fee95)

### 预期行为
搜索结果中带emoji的视频标题Emoji表情正常显示。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
已经提供了。

**Comment by guozhigq** [comment]
不是bug，跟web端一致的

**Comment by cnstruggler** [comment]
> 不是bug，跟web端一致的

好的，我这就去和B站客服对线！
