### ISSUE TITLE
消息中心收到的赞列表里的点赞用户最多只能查看5个。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#915]
### 问题描述
消息中心收到的赞列表里的点赞用户最多只能查看5个，但是B站网页版却能够全部查看。![IMG_20240907_201137.jpg](https://github.com/user-attachments/assets/b85dbf0b-e704-4696-a8a1-f72cbff5ac4c)

![IMG_20240907_201035.jpg](https://github.com/user-attachments/assets/daa094c5-ca1c-48bc-b7dd-1c332ca869c2)

### 复现步骤
消息中心→收到的赞查看赞数为5的通知，并在电脑端登录网页版B站查看收到的赞以进行对比。

### 预期行为
消息中心收到的赞列表里的点赞用户能全部看到。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
已提供。

**Comment by guozhigq** [comment]
ok
