### ISSUE TITLE
UP主认证会在开启夜间模式后消失。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#916]
### 问题描述
在夜间模式下打开一个已经认证的UP的主页，会发现其认证消失了。

### 复现步骤
在夜间模式关闭的时候打开一个已经认证了的UP的主页，会发现其认证存在；打开夜间模式再次进入此UP的主页，会发现认证消失。

### 预期行为
夜间模式下，UP的认证依旧能正常显示。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
![Screenshot_20240907-203400.jpg](https://github.com/user-attachments/assets/8d91736f-1ef0-4584-ab8c-5aec38215ee2)

![Screenshot_20240907-203412.jpg](https://github.com/user-attachments/assets/3911fa4e-0565-49ba-a262-d8a56bda7ac8)

**Comment by guozhigq** [comment]
ok
