### ISSUE TITLE
搜索结果筛选栏的分区显示不全。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#919]
### 问题描述
搜索视频时，搜索结果筛选栏的分区显示不全。

### 复现步骤
首先，搜索一个关键词。
然后点击筛选键。https://github.com/user-attachments/assets/93c0145f-4a51-433d-b759-84937c0ced61

### 预期行为
筛选搜索结果时能看到全部分区。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
![IMG_20240907_213607.jpg](https://github.com/user-attachments/assets/b4c8b980-61f9-438c-aed6-2178fd326256)

**Comment by guozhigq** [comment]
ok
