### ISSUE TITLE
关于动态的显示的小问题和建议

### ISSUE THREAD

**Issue by izoKiro** [guozhigq/pilipala#92]
### 功能描述
![Screenshot_20230910_152925](https://github.com/guozhigq/pilipala/assets/144582985/3425a36a-6a80-46c0-9d62-4b0e5a88390d)
![Screenshot_20230910_152934](https://github.com/guozhigq/pilipala/assets/144582985/7db92a32-49f9-4605-9bc4-5fa853f042c0)
动态在文字过长时会在文字后面显示省略号，但是如果在过长而且要显示省略号前边的文字是空格的话会直接不显示省略号。
过长的动态如果有图片的话图片也不会显示，而且点进动态图片时无法双指放大。
### 目标
像官方客户端改成全文两个蓝色字体，并且图片不会被省略掉。
![Screenshot_20230910_153939](https://github.com/guozhigq/pilipala/assets/144582985/a4af541a-8749-45cc-be48-09b5fb60858b)
看图时能够放大。
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
官方客户端

**Comment by guozhigq** [comment]
图片展示问题已优化

**Comment by guozhigq** [comment]
展开全文目前无法实现
