### ISSUE TITLE
系统通知已读状态异常。

### ISSUE THREAD

**Issue by cnstruggler** [guozhigq/pilipala#929]
### 问题描述
已读状态异常：当系统通知有未读消息时，消息中心系统通知图标会有红点，点进系统通知在退回消息中心，表示未读状态的红点会消失。但是如果接着退出消息中心到主页去，再从主页回到消息中心，你会发现系统通知的未读红点又出现了！如果想要彻底消除系统通知的未读红点，必须登录网页版B站，然后打开系统通知，这样才能够彻底消除消息中心系统通知项的未读红点。

### 复现步骤
先把我的GitHub头像换成B站头像（这个头像在B站违规）![共产国际标志.png](https://github.com/user-attachments/assets/b027f47f-4db3-4894-9cfb-0bf5f3427386)

等到管理员清除头像后，系统通知会有红点。![IMG_20240910_170026.jpg](https://github.com/user-attachments/assets/afc98682-8dc8-408e-9fc0-e6e3a066f508)

点进系统通知里边（没有显示清除头像的系统通知的问题我已经在https://github.com/guozhigq/pilipala/issues/925 中提到了）。![Screenshot_20240910-170534.jpg](https://github.com/user-attachments/assets/3f05305b-61ff-4dd3-9fa8-289755ec0718)

再退出来，发现系统通知红点消失。![IMG_20240910_170722.jpg](https://github.com/user-attachments/assets/c274c7bf-843c-445a-b8b2-6a73e20a7c05)

退出消息中心，到首页。![Screenshot_20240910-170830.jpg](https://github.com/user-attachments/assets/687376ff-ad11-4e80-ab9d-4642b5d8df62)

在回到消息中心，你会发现红点又出现了。![IMG_20240910_170026.jpg](https://github.com/user-attachments/assets/d4455404-daff-4d6a-a2b2-37ea86b04869)

这时候，关闭PLPL，打开网页版B站的消息中心→系统通知。![Screenshot_20240910-171212.jpg](https://github.com/user-attachments/assets/6261a73c-f4f6-4bab-be3b-7694c5db0a73)

再打开PLPL到消息中心，会发现系统通知红点消失了。![IMG_20240910_170722.jpg](https://github.com/user-attachments/assets/00a5e0ee-1a82-4520-a9df-c2c572c92909)

### 预期行为
PLPL能够正常已读系统通知。

### 系统信息
------- 设备信息 -------
id: HUAWEIWAS-AL00
board: hi6250
bootloader: unknown
brand: HUAWEI
device: HWWAS-H
display: WAS-AL00 8.0.0.358(C00)
fingerprint: HUAWEI/WAS-AL00/HWWAS-H:8.0.0/HUAWEIWAS-AL00/358(C00):user/release-keys
hardware: hi6250
host: cn-west-3a-c0fe74cfa1593630058966-844330053-3qjsv
isPhysicalDevice: true
manufacturer: HUAWEI
model: WAS-AL00
product: WAS-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 358(C00)
versionPreviewSdk: 0
versionRelease: 8.0.0
versionSdk: 26
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.24
appName: PiliPala
buildNumber: 10243
packageName: com.guozhigq.pilipala

### 相关截图或日志
已经提供。

**Comment by guozhigq** [comment]
了解
