### ISSUE TITLE
收藏夹无法打开

### ISSUE THREAD

**Issue by dengshuo1100** [guozhigq/pilipala#930]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by dengshuo1100** [comment]
收藏夹功能无法使用![Screenshot_2024-09-10-21-37-37-71_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/232a104a-f071-44f0-a682-1a010974acf4)

**Comment by cnstruggler** [comment]
> 收藏夹功能无法使用![Screenshot_2024-09-10-21-37-37-71_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/232a104a-f071-44f0-a682-1a010974acf4)
> 
> 

你是张表达这个意思吗https://github.com/guozhigq/pilipala/issues/909 ？
