### ISSUE TITLE
请求优化对关注up的搜索功能

### ISSUE THREAD

**Issue by realSilasYang** [guozhigq/pilipala#940]
希望可以在关注up列表中通过关键字、首字母缩写等搜索快速找到关注的up主。

例如，搜索“李博士”可以找到
![Screenshot_20240916_193334_com_guozhigq_pilipala_MainActivity](https://github.com/user-attachments/assets/a31d4952-7b46-4684-8186-6b10374d3a3f)

但是搜索“博士”则结果只有
![Screenshot_20240916_193325_com_guozhigq_pilipala_MainActivity](https://github.com/user-attachments/assets/a36adf02-2702-4bdf-8889-951516a688cf)

**Comment by guozhigq** [comment]
ok

**Comment by guozhigq** [comment]
1.0.25版本已增加
