### ISSUE TITLE
单纯疑惑

### ISSUE THREAD

**Issue by huajideshutiao** [guozhigq/pilipala#944]
![IMG_20240917_140819](https://github.com/user-attachments/assets/ecf9f178-aab9-46d1-848b-237a1d309caf)
图里画圆圈的地方的双横杠是干嘛用的？点了没啥反应。
只是提示视频已经暂停了吗

**Comment by cnstruggler** [comment]
你按住双横杠上下滑动试试。

**Comment by cnstruggler** [comment]
https://github.com/user-attachments/assets/48bc33e5-9f1f-4240-81b7-c63d255ccadb

**Comment by huajideshutiao** [comment]
> SVID_20240918_180302_1.mp4 
>  SVID_20240918_180444_1.mp4

给看评论区设计的吗，倒也有道理
