### ISSUE TITLE
请求支持填写 Cookies 登录

### ISSUE THREAD

**Issue by gitiray** [guozhigq/pilipala#954]
### 功能描述
自己抓包把 Cookies 填入登录

### 目标
自己抓包把 Cookies 填入登录，不需要再登录一个设备，可以实现和已登录的会话复用

### 解决方案
在登录界面加个填写 Cookies 的按钮

### 其他
https://github.com/xiaoyaocz/dart_simple_live

**Comment by guozhigq** [comment]
最新版已支持
