### ISSUE TITLE
长按加速改为三倍速

### ISSUE THREAD

**Issue by wanzh5** [guozhigq/pilipala#96]
原版是三倍速，而且三倍速感觉更符合习惯，毕竟长按加速只有两倍确实有点慢

**Comment by zzm-note** [comment]
不同意三倍速，就是因为官方默认三倍数才用第三方客户端的。
建议增加选择项，可以自定义长按倍速

**Comment by guozhigq** [comment]
> 不同意三倍速，就是因为官方默认三倍数才用第三方客户端的。 建议增加选择项，可以自定义长按倍速

已经开发完成了，支持默认倍速、默认长按倍速、自定义倍速
