### ISSUE TITLE
BUG: 搜索分区panel

### ISSUE THREAD

**Issue by testrunnerci** [guozhigq/pilipala#962]
### 问题描述
搜索视频分区面板在较小屏幕下显示不全

### 复现步骤
打开搜索视频分区

### 预期行为
显示完整

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
1.0.25版本已修复
