### ISSUE TITLE
BUG: 视频评论页面

### ISSUE THREAD

**Issue by testrunnerci** [guozhigq/pilipala#965]
### 问题描述
在简介页面单击评论tab，评论页面会返回顶部

### 预期行为
在评论页面单击tab才回到顶部

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
1.0.25版本已修复
