### ISSUE TITLE
BUG: AI总结

### ISSUE THREAD

**Issue by testrunnerci** [guozhigq/pilipala#966]
### 问题描述
个别视频AI总结显示为空白页面，实际是有内容的

### 复现步骤
比如 `BV1r1xEeLEwY`

### 预期行为
有显示内容

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
1.0.25版本已修复
