### ISSUE TITLE
BUG: 黑名单

### ISSUE THREAD

**Issue by testrunnerci** [guozhigq/pilipala#967]
### 问题描述
黑名单只有一个时不显示

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by guozhigq** [comment]
1.0.25版本已修复
