### ISSUE TITLE
添加输入建议的开关

### ISSUE THREAD

**Issue by VskAwayZ** [guozhigq/pilipala#980]
### 功能描述
在设置里添加一个关于输入建议的开关。
![Screenshot_2024-10-11-00-59-01-537_com guozhigq pilipala](https://github.com/user-attachments/assets/738a1855-8814-42f6-b991-cf2d41d76116)

### 目标
实现输入建议的自由开关。
### 解决方案
抱歉，无。

### 其他
试过其他第三方b站，都没有这个选项。

**Comment by Rzdpai** [comment]
你可以试试换个输入法

**Comment by VskAwayZ** [comment]
> 你可以尝试换个输入法

我指的输入建议是b站的输入建议（或者叫推荐），即“哈”字下面的“哈利波特”，“哈基米”，“哈苏”等条目，可能是我写的有歧义了。= =

**Comment by Rzdpai** [comment]
> > 你可以尝试换个输入法
> 
> 我指的输入建议是b站的输入建议（或者叫推荐），即“哈”字下面的“哈利波特”，“哈基米”，“哈苏”等条目，可能是我写的有歧义了。= =

X版好像有(我不确定，你可以去看看)

**Comment by guozhigq** [comment]
最新版已支持
