### ISSUE TITLE
弹幕设置Bug

### ISSUE THREAD

**Issue by Rzdpai** [guozhigq/pilipala#981]
设置弹幕后必须要退出应用，倘若没退出就点开另一个视频，会恢复默认设置

**Comment by cnstruggler** [comment]
不是哥们，你用截图或者录屏佐证一下啊！光用文字抽象表述除了你谁能看懂？

**Comment by guozhigq** [comment]
> 不是哥们，你用截图或者录屏佐证一下啊！光用文字抽象表述除了你谁能看懂？

没事，之前有人提过这个问题，我再看看

**Comment by Rzdpai** [comment]
> 不是哥们，你用截图或者录屏佐证一下啊！光用文字抽象表述除了你谁能看懂？

图片表述不了，视频Github最大只能上传2M的，反正就是设置弹幕后不退出应用设置不生效(在推荐里打开视频正常，但退出视频界面再打开视频就是原本设置)

**Comment by Rzdpai** [comment]
> > 不是哥们，你用截图或者录屏佐证一下啊！光用文字抽象表述除了你谁能看懂？
> 
> 没事，之前有人提过这个问题，我再看看

还有一点就是在播放视频的时候退出应用(不关闭，只是返回主页)再回到应用时原本那些弹幕会消失

**Comment by guozhigq** [comment]
> > > 不是哥们，你用截图或者录屏佐证一下啊！光用文字抽象表述除了你谁能看懂？
> > 
> > 
> > 没事，之前有人提过这个问题，我再看看
> 
> 还有一点就是在播放视频的时候退出应用(不关闭，只是返回主页)再回到应用时原本那些弹幕会消失

特意这么设定的
