### ISSUE TITLE
界面顶部控件显示问题

### ISSUE THREAD

**Issue by x441** [guozhigq/pilipala#984]
### 问题描述
界面顶部控件无法显示，已知多人出现该问题

### 复现步骤
更新后打开软件就这样

### 预期行为
修复控件正常显示即可

### 系统信息
Xiaomi 13 pro
澎湃1.0.12.0

### 相关截图或日志
![Screenshot_2024-10-11-14-15-10-533_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/dd266d60-66bc-4cb2-b29e-c697f8c3f2e1)

**Comment by guozhigq** [comment]
可以参考 #982  解决方案
