### ISSUE TITLE
up主页显示不全

### ISSUE THREAD

**Issue by Rzdpai** [guozhigq/pilipala#985]
![Screenshot_2024-10-11-22-28-34-71_130b0d7520509a75c6a4102c4ba0249d.jpg](https://github.com/user-attachments/assets/0b424622-3871-4b8e-bc0d-1976c53f64a9)

如果打开一个视频并且播放完成后再打开up个人主页就正常了，不过如果打开另一个视频就不正常了
打开应用，随便播放一个视频，等视频播放完成后退出视频界面就会出现这种情况

**Comment by Rzdpai** [comment]
这个是概率性出现，重启应用就没了

**Comment by guozhigq** [comment]
没懂 方便录个屏吗

**Comment by Rzdpai** [comment]
> 没懂 方便录个屏吗

Github文件大小有限制，我放网盘了
https://share.feijipan.com/s/mYCu7sf7

**Comment by guozhigq** [comment]
在视频中看到两处异常
1. up主信息被截断
2. up主信息无法显示

之前版本出现过异常1吗
异常2应该是官方接口校验引起的，没有返回up主信息
```
{
    "code":-352,
    "message":"风控校验失败",
    "ttl":1,
    "data":{
       "v_voucher":"voucher_da91978f-5204-492d-a492-65d7fc295b40"
    }
}
```

**Comment by Rzdpai** [comment]
> 在视频中看到两处异常
> 1. up主信息被截断
> 2. up主信息无法显示
> 
> 之前版本出现过异常1吗
> 异常2应该是官方接口校验引起的，没有返回up主信息
> ```
> {
>     "code":-352,
>     "message":"风控校验失败",
>     "ttl":1,
>     "data":{
>        "v_voucher":"voucher_da91978f-5204-492d-a492-65d7fc295b40"
>     }
> }
> ```
> 

之前没见过，更新125之后才发现

**Comment by guozhigq** [comment]
试试 https://drive.google.com/file/d/1oiew9P_ecEF-8FKzwvSWTXxDxgKrjKPB/view?usp=sharing

**Comment by Rzdpai** [comment]
> 试试 https://drive.google.com/file/d/1oiew9P_ecEF-8FKzwvSWTXxDxgKrjKPB/view?usp=sharing

不会出现没有信息了，但显示不全还是存在，而且我发现有的up会出现这种情况有的不会

**Comment by guozhigq** [comment]
显示不全的up是不是个人信息比较多，比如多了认证信息、个人简介比较长等等

**Comment by guozhigq** [comment]
你的手机把状态栏隐藏了么，强制全屏？

**Comment by Rzdpai** [comment]
> 显示不全的up是不是个人信息比较多，比如多了认证信息、个人简介比较长等等

不是，而且原本不会出现这种情况，必须打开一个视频播放玩(或者进度条拉到底)才会出现

**Comment by guozhigq** [comment]
> > 显示不全的up是不是个人信息比较多，比如多了认证信息、个人简介比较长等等
> 
> 不是，而且原本不会出现这种情况，必须打开一个视频播放玩(或者进度条拉到底)才会出现

开了【播放完成自动退出全屏】？

**Comment by Rzdpai** [comment]
> 你的手机把状态栏隐藏了么，强制全屏？

刚才我试了把显示顶部区域关上，还是一样，而且我又发现一个问题
https://share.feijipan.com/s/szCLDg5E

**Comment by guozhigq** [comment]
> > 显示不全的up是不是个人信息比较多，比如多了认证信息、个人简介比较长等等
> 
> 不是，而且原本不会出现这种情况，必须打开一个视频播放玩(或者进度条拉到底)才会出现

开了【播放完成自动退出全屏】？

**Comment by Rzdpai** [comment]
> > > 显示不全的up是不是个人信息比较多，比如多了认证信息、个人简介比较长等等
> > 
> > 不是，而且原本不会出现这种情况，必须打开一个视频播放玩(或者进度条拉到底)才会出现
> 
> 开了【播放完成自动退出全屏】？

对，刚才试了一下，关掉后就不会出现这种情况了

**Comment by guozhigq** [comment]
> > 你的手机把状态栏隐藏了么，强制全屏？
> 
> 刚才我试了把显示顶部区域关上，还是一样，而且我又发现一个问题 https://share.feijipan.com/s/szCLDg5E

这个应该有错误日志 你看看

**Comment by Rzdpai** [comment]
> > > 你的手机把状态栏隐藏了么，强制全屏？
> > 
> > 刚才我试了把显示顶部区域关上，还是一样，而且我又发现一个问题 https://share.feijipan.com/s/szCLDg5E
> 
> 这个应该有错误日志 你看看

错误日志里显示没有任何数据(不确定，我重启过软件，会不会重启后清除日志)

**Comment by guozhigq** [comment]
> > > > 你的手机把状态栏隐藏了么，强制全屏？
> > > 
> > > 
> > > 刚才我试了把显示顶部区域关上，还是一样，而且我又发现一个问题 https://share.feijipan.com/s/szCLDg5E
> > 
> > 
> > 这个应该有错误日志 你看看
> 
> 错误日志里显示没有任何数据(不确定，我重启过软件，会不会重启后清除日志)

重启会清除日志，等下次再遇见再看吧 。 可能是有一个推荐内容渲染异常了

**Comment by Rzdpai** [comment]
> > > > > 你的手机把状态栏隐藏了么，强制全屏？
> > > > 
> > > > 
> > > > 刚才我试了把显示顶部区域关上，还是一样，而且我又发现一个问题 https://share.feijipan.com/s/szCLDg5E
> > > 
> > > 
> > > 这个应该有错误日志 你看看
> > 
> > 错误日志里显示没有任何数据(不确定，我重启过软件，会不会重启后清除日志)
> 
> 重启会清除日志，等下次再遇见再看吧 。 可能是有一个推荐内容渲染异常了

好

**Comment by decetion** [comment]
我出现了一样的问题，不管视频有没有播放完，点击up主头像进去都显示不全，刚开始一瞬间会显示后面就没了

而且在关注的up页面点击关注无法取消关注，只能移动到分组，想取消关注还得去找ta的视频，在视频播放页面才能取消关注


https://github.com/user-attachments/assets/c7f8a3ac-d970-4116-b368-85179ee6e177

**Comment by gitbruc** [comment]
> 我出现了一样的问题，不管视频有没有播放完，点击up主头像进去都显示不全，刚开始一瞬间会显示后面就没了
> 
> 而且在关注的up页面点击关注无法取消关注，只能移动到分组，想取消关注还得去找ta的视频，在视频播放页面才能取消关注
> Record_2024-10-19-16-53-52.mp4

一样，我是24版本，之前用的好好的突然不行了
