### ISSUE TITLE
去掉底栏中的“首页”后无法进入设置

### ISSUE THREAD

**Issue by sfxfs** [guozhigq/pilipala#986]
### 问题描述
在设置中去掉底栏中的“首页”后没有方法再次进入设置

### 复现步骤
在首页头像的设置中隐藏 底栏 中的 “首页”

### 预期行为
能否在别的页面也添加设置的按钮，或者直接把设置加到底栏

### 系统信息
arm64 安卓14

**Comment by guozhigq** [comment]
最新版已支持
