### ISSUE TITLE
可以屏蔽视频下方推荐吗

### ISSUE THREAD

**Issue by 1753851153** [guozhigq/pilipala#988]
### 功能描述
视频播放页下方有许多推荐视频，可以屏蔽吗

### 目标
希望免受无关视频影响，只专注订阅的up

### 其他
如哔哩漫游![Screenshot_20241012_121122_tv.danmaku.bili.jpg](https://github.com/user-attachments/assets/9e26a1d6-1881-4836-935d-3beba57a630a)

**Comment by guozhigq** [comment]
目前支持关闭 【设置】-【其他设置 】-【相关视频推荐】
