### ISSUE TITLE
V1.0.7 屏幕帧率选择之后重启应用会变回自动

### ISSUE THREAD

**Issue by TY-LIU** [guozhigq/pilipala#99]
### 复现步骤
* 点击头像>底部弹窗右上角设置图标>外观设置>屏幕帧率>选择任意一个选项。
只能在未关闭应用前使用选择的帧率。关闭应用后帧率会重新变成自动，使用起来是低帧率。
* 另外还有一个系统问题：
当进入软件设置，也就是底部弹窗右上角进入设置页面，进入任意二级菜单，再退回到底部弹窗页，再次点击右上角设置图标，无法进入设置页面。只能点击空白处关闭底部弹窗，重新点击头像弹出弹窗，才能进入设置页面。

### 预期行为
应用退出保留选择的方案，再次打开应采用选中的帧率方案

### 系统信息
* v1.0.7 
* 安卓12
* color os 13.1正式版 一加8T

**Comment by TY-LIU** [comment]
修复问题，应该就修复了#75

**Comment by guozhigq** [comment]
> 修复这个问题，应该就修复了#75

这两个问题应该没有关联
