### ISSUE TITLE
搜索视频重复

### ISSUE THREAD

**Issue by Rzdpai** [guozhigq/pilipala#990]
![IMG_20241012_184825.jpg](https://github.com/user-attachments/assets/081ae304-292d-46f6-9c18-bc428fe18a79)

**Comment by guozhigq** [comment]
有筛选条件吗

**Comment by Rzdpai** [comment]
> 有筛选条件吗
> 

没有

**Comment by Rzdpai** [comment]
> 有筛选条件吗
> 

![IMG_20241012_202305.jpg](https://github.com/user-attachments/assets/16a82ac5-9e47-4420-8c07-8dd3e98e0f4e)

突然发现主页也有概率
