### ISSUE TITLE
Up主页面显示不全

### ISSUE THREAD

**Issue by Johncoff229** [guozhigq/pilipala#992]
### 问题描述
播放完一个视频后，点开该up主头像，个人信息页面显示不全

### 复现步骤
播放完一个视频，点击其头像

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
1.0.25 红米k70

### 相关截图或日志

https://github.com/user-attachments/assets/ece155cb-0cbe-40cb-b079-8a2db32cac27

**Comment by Rzdpai** [comment]
这个我反馈过了，把播放完自动退出全屏关了就行了

**Comment by guozhigq** [comment]
你俩说的不是一件事。
up信息不展示试试 https://github.com/guozhigq/pilipala/issues/985#issuecomment-2408504738

**Comment by guozhigq** [comment]
最新版已修复
