### ISSUE TITLE
提供手势关闭选项

### ISSUE THREAD

**Issue by mchhhhhhh** [guozhigq/pilipala#993]
### 功能描述
请提供对所请求功能的清晰描述。
希望全屏手势可以提供一个关闭选项，平时也用不到这个功能![Screenshot_2024-10-13-13-14-42-000_com.guozhigq.pilipala.jpg](https://github.com/user-attachments/assets/139d4172-bd18-48ab-a1f1-4262b5cfe7f5)

### 目标
请描述你希望通过这个功能实

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by guozhigq** [comment]
最新版已支持
