### ISSUE TITLE
直播观看问题（横屏状态白屏）

### ISSUE THREAD

**Issue by MobiusMei** [guozhigq/pilipala#997]
### 问题描述
当以横屏状态进入直播间时，会显示白屏。换为竖屏后再换回横屏则可正常播放。
直接以竖屏进入直播间则无此问题，竖屏转横屏也没有问题。

### 复现步骤
iPad以横屏状态点击任意直播间可复现本问题。

### 预期行为
无论横屏或竖屏进入都正常播放。

### 系统信息
iPadOS 17.6.1

### 相关截图或日志
![image](https://github.com/user-attachments/assets/2117a58e-3632-4295-b766-6b170ac12d7b)
以横屏状态直接进入直播间。

**Comment by guozhigq** [comment]
最新版已修复
